//! Adversarial cases against `story:event-payloads-for-folds`.
//!
//! The story's acceptance statement is the subject: "Given the event log alone, when
//! the projections for every entity with a declared transition are rebuilt by folding,
//! then each projection row can be produced from its events without reading any command
//! input or response."
//!
//! These read the contract by running `ess specify compile --path systems/mandate
//! --format json` at test time, and never `generated/`. `generated/` is regenerated by
//! the coordinator after a unit merges, so inside a unit worktree it predates the
//! contract under attack: a case that read it would be red because the tree is stale and
//! not because the contract is wrong, which proves nothing. ESS 0.25.0 is the
//! repository's contract compiler (`AGENTS.md`) and `cargo xtask check` already requires
//! it on `PATH`, so shelling out adds no dependency — this file adds none, and
//! `serde_json` is already a dependency of this crate.
//!
//! One case reads the yaml directly, with the same narrow-reader discipline as
//! `contract_adversary.rs`, to check that the hand-written source and the compiled model
//! agree field for field.

use serde_json::{Map, Value};
use std::collections::{BTreeMap, BTreeSet};
use std::process::Command;
use std::sync::OnceLock;

const SYSTEM: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../systems/mandate");
const DOMAINS: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../systems/mandate/domains");

fn compiled() -> &'static Value {
    static MODEL: OnceLock<Value> = OnceLock::new();
    MODEL.get_or_init(|| {
        let output = Command::new("ess")
            .args(["specify", "compile", "--path", SYSTEM, "--format", "json"])
            .output()
            .unwrap_or_else(|error| {
                panic!(
                    "ess specify compile --path {SYSTEM} --format json: {error}. ESS 0.25.0 \
                     compiles this repository's contract (AGENTS.md) and cargo xtask check \
                     already requires it on PATH"
                )
            });
        assert!(
            output.status.success(),
            "ess specify compile: {}",
            String::from_utf8_lossy(&output.stderr)
        );
        serde_json::from_slice(&output.stdout).expect("the compiled model is JSON")
    })
}

fn section(key: &str) -> &'static Map<String, Value> {
    compiled()[key]
        .as_object()
        .unwrap_or_else(|| panic!("the compiled model holds a {key} section"))
}

/// The canonical spelling of a type reference: `List<Optional<mandate.core.X>>`.
/// Primitives compile to their lower-case ESS name (`string`, `timestamp`).
fn canonical(reference: &Value) -> String {
    match reference.get("kind").and_then(Value::as_str) {
        Some("declared" | "primitive") => reference["name"]
            .as_str()
            .expect("a named type reference")
            .to_owned(),
        Some("optional") => format!("Optional<{}>", canonical(&reference["of"])),
        Some("list") => format!("List<{}>", canonical(&reference["of"])),
        other => panic!("unmodelled type reference kind {other:?}"),
    }
}

/// Every type name reachable through `Optional<…>` and `List<…>` wrappers.
fn type_names(reference: &Value) -> BTreeSet<String> {
    let mut names = BTreeSet::new();
    match reference.get("kind").and_then(Value::as_str) {
        Some("declared" | "primitive") => {
            names.insert(reference["name"].as_str().expect("a name").to_owned());
        }
        _ => {
            for key in ["of", "item", "inner", "value"] {
                if let Some(inner) = reference.get(key) {
                    names.extend(type_names(inner));
                }
            }
        }
    }
    names
}

fn fields_of(holder: &Value) -> Vec<(String, &Value)> {
    holder["fields"]
        .as_array()
        .expect("a fields array")
        .iter()
        .map(|field| {
            (
                field["name"].as_str().expect("a field name").to_owned(),
                &field["type_ref"],
            )
        })
        .collect()
}

fn inputs_of(command: &Value) -> Vec<(String, &Value)> {
    command["input"]
        .as_array()
        .expect("an input array")
        .iter()
        .map(|field| {
            (
                field["name"].as_str().expect("an input name").to_owned(),
                &field["type_ref"],
            )
        })
        .collect()
}

fn identity_type(entity: &Value) -> String {
    canonical(&entity["identity"]["type_ref"])
}

fn transitions(entity: &Value) -> usize {
    entity
        .get("lifecycle")
        .and_then(|lifecycle| lifecycle.get("transitions"))
        .and_then(Value::as_array)
        .map_or(0, Vec::len)
}

/// A field an entity invariant pins to a literal (`transitive == false`) is produced by
/// the fold from the invariant, not from an event.
fn pinned(entity: &Value) -> BTreeSet<String> {
    entity
        .get("invariants")
        .and_then(Value::as_array)
        .map(|invariants| {
            invariants
                .iter()
                .filter_map(Value::as_str)
                .filter_map(|text| {
                    let (left, right) = text.split_once("==")?;
                    let name = left.trim();
                    (!right.trim().is_empty()
                        && !name.is_empty()
                        && name
                            .chars()
                            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_'))
                    .then(|| name.to_owned())
                })
                .collect()
        })
        .unwrap_or_default()
}

/// Which command outcome emits which event.
fn producers() -> BTreeMap<String, Vec<String>> {
    let mut producers: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for (name, command) in section("commands") {
        for outcome in command["outcomes"].as_array().expect("outcomes") {
            for emitted in outcome["emits"].as_array().into_iter().flatten() {
                let event = emitted.as_str().expect("an emitted event name");
                producers.entry(event.to_owned()).or_default().push(format!(
                    "{name}/{}",
                    outcome["name"].as_str().unwrap_or("?")
                ));
            }
        }
    }
    producers
}

/// The event field a fold would read for `wanted`, if the carrier has one: the field of
/// that name, or the plural `<name>s` an event that writes many records at once uses.
fn carrier_field<'a>(
    fields: &BTreeMap<String, &'a Value>,
    wanted: &str,
) -> Option<(String, &'a Value)> {
    if let Some(reference) = fields.get(wanted) {
        return Some((wanted.to_owned(), reference));
    }
    let plural = format!("{wanted}s");
    fields
        .get(plural.as_str())
        .map(|reference| (plural.clone(), *reference))
}

struct Carrier {
    event: String,
    missing: Vec<String>,
}

/// The story's own class rule R2, with the four exemptions its implementor states: the
/// lifecycle `state` (which the declared `moves` supplies), `organization_id` on an event
/// carrying a `VerifiedContext` (which carries `organization`), a field an entity
/// invariant pins to a literal, and a required field carried under its plural name by an
/// event that writes many records at once. Every declared entity field is required here,
/// `Optional` included: an absent optional field is a value the fold has to produce, and
/// the contract is the only thing that can say it is `None`.
/// One level of struct descent, as `adversary_fold_inputs_2.rs` reads it: a required
/// field is carried when some field the event carries — never the `VerifiedContext` — is
/// a struct type, or a `List<>` of one, declaring a member of that exact name. Added by the
/// coordinator after correction round 2 so this reader and the exact-type reader measure
/// the same residue.
fn carried_inside_a_struct(fields: &BTreeMap<String, &Value>, wanted: &str) -> bool {
    fields.values().any(|reference| {
        type_names(reference).into_iter().any(|kind| {
            if kind == "mandate.core.VerifiedContext" {
                return false;
            }
            let Some(declared) = section("types").get(kind.as_str()) else {
                return false;
            };
            if declared["body"]["kind"].as_str() != Some("struct") {
                return false;
            }
            fields_of(&declared["body"])
                .into_iter()
                .any(|(member, _)| member == wanted)
        })
    })
}

fn best_carrier(entity: &Value) -> Option<Carrier> {
    let identity = identity_type(entity);
    let pinned = pinned(entity);
    let domain = entity["domain"].as_str().expect("an entity domain");
    let required: Vec<String> = fields_of(entity)
        .into_iter()
        .map(|(name, _)| name)
        .filter(|name| !pinned.contains(name))
        .collect();

    let mut ordered: Vec<(&String, &Value)> = section("events").iter().collect();
    ordered.sort_by_key(|(_, event)| event["domain"].as_str() != Some(domain));

    let mut best: Option<Carrier> = None;
    for (name, event) in ordered {
        let fields: BTreeMap<String, &Value> = fields_of(event).into_iter().collect();
        if !fields
            .values()
            .any(|reference| type_names(reference).contains(&identity))
        {
            continue;
        }
        let carries_context = fields
            .values()
            .any(|reference| type_names(reference).contains("mandate.core.VerifiedContext"));
        let missing: Vec<String> = required
            .iter()
            .filter(|field| {
                carrier_field(&fields, field).is_none()
                    && !carried_inside_a_struct(&fields, field)
                    && !(field.as_str() == "organization_id" && carries_context)
            })
            .cloned()
            .collect();
        let empty = missing.is_empty();
        if best
            .as_ref()
            .is_none_or(|kept| missing.len() < kept.missing.len())
        {
            best = Some(Carrier {
                event: name.clone(),
                missing,
            });
        }
        if empty {
            break;
        }
    }
    best
}

/// Not a finding of its own: a guard, so that a reader bug shows up as a reader bug and
/// never as a finding. Every number is read from `ess specify compile`, and every string
/// from the yaml under attack.
#[test]
fn the_reader_sees_the_contract_it_claims_to_see() {
    assert_eq!(section("events").len(), 72, "compiled events");
    assert_eq!(section("commands").len(), 59, "compiled commands");
    assert_eq!(section("types").len(), 110, "compiled type entries");
    assert_eq!(section("entities").len(), 36, "compiled entities");

    let opened = &section("events")["mandate.identity.SessionOpened"];
    assert_eq!(
        fields_of(opened)
            .into_iter()
            .map(|(name, reference)| (name, canonical(reference)))
            .collect::<Vec<_>>(),
        vec![
            ("id".to_owned(), "mandate.core.SessionId".to_owned()),
            (
                "principal_id".to_owned(),
                "mandate.core.PrincipalId".to_owned()
            ),
            (
                "organization_id".to_owned(),
                "mandate.core.OrganizationId".to_owned()
            ),
            (
                "connection_id".to_owned(),
                "Optional<mandate.core.FederationConnectionId>".to_owned()
            ),
            (
                "epochs".to_owned(),
                "mandate.core.EpochSnapshotRef".to_owned()
            ),
            ("expires_at".to_owned(), "timestamp".to_owned()),
        ],
        "event fields are read with their types, in order"
    );

    let session = &section("entities")["mandate.identity.Session"];
    assert_eq!(identity_type(session), "mandate.core.SessionId");
    assert_eq!(transitions(session), 1, "Session declares revoke");
    assert_eq!(
        pinned(&section("entities")["mandate.delegation.Delegation"]),
        BTreeSet::from(["transitive".to_owned()]),
        "an invariant pinning a field to a literal is read"
    );
    assert_eq!(
        producers().get("mandate.identity.SessionRevoked"),
        Some(&vec!["mandate.identity.RevokeSession/accepted".to_owned()]),
        "emitted events are read with the outcome that emits them"
    );
}

/// The story's first class rule: "every move-event carries the record's identity". An
/// outcome that declares a `moves` subject and emits an event carrying no field of the
/// moved entity's identity type leaves the fold unable to say which row moved.
#[test]
fn every_moves_outcome_emits_an_event_carrying_the_moved_record_identity() {
    let mut naming_nothing: BTreeMap<String, String> = BTreeMap::new();
    for (name, command) in section("commands") {
        for outcome in command["outcomes"].as_array().expect("outcomes") {
            let Some(subject) = outcome.get("subject") else {
                continue;
            };
            if subject["effect"].as_str() != Some("moves") {
                continue;
            }
            let entity = subject["entity"].as_str().expect("a moved entity");
            let identity = identity_type(&section("entities")[entity]);
            let transition = subject["transition"]["name"].as_str().unwrap_or("?");
            let emits = outcome["emits"].as_array().expect("emits");
            let outcome_name = outcome["name"].as_str().unwrap_or("?");
            if emits.is_empty() {
                naming_nothing.insert(
                    format!("{name}/{outcome_name}"),
                    format!("moves {entity}.{transition} and emits nothing"),
                );
                continue;
            }
            for emitted in emits {
                let event = emitted.as_str().expect("an event name");
                let fields = fields_of(&section("events")[event]);
                if !fields
                    .iter()
                    .any(|(_, reference)| type_names(reference).contains(&identity))
                {
                    naming_nothing.insert(
                        format!("{name}/{outcome_name} -> {event}"),
                        format!(
                            "moves {entity}.{transition} but carries no {identity}; fields {:?}",
                            fields.iter().map(|(name, _)| name).collect::<Vec<_>>()
                        ),
                    );
                }
            }
        }
    }
    assert_eq!(
        naming_nothing,
        BTreeMap::new(),
        "a move-event that does not carry the moved record's identity leaves the fold \
         unable to say which row moved"
    );
}

/// The residue the wave leaves against the acceptance statement, pinned by name so that
/// this file is a tripwire and not a wish: every entity below has a declared transition
/// and no event that carries its identity and its fields, so its projection cannot be
/// rebuilt from the log, measured with the exact-type reader of
/// `adversary_fold_inputs_2.rs`, which descends one level into a carried struct: nine are
/// in the seven domain files `story:event-payloads-for-folds` owns; three are in
/// `policy.yaml` and `workload.yaml`, which its Scope calls untouched. All fourteen of the
/// original set reproduce against the story's base commit. `mandate.audit.AuditEvent`
/// folds through the `mandate.core.AuditRecord` on `AuditEventRecorded` and
/// `mandate.graph.Relation` through the `mandate.core.ResourceRef` on
/// `RelationshipWritten`, so neither is residue.
///
/// Two left the set in `story:contract-creates`, which made each declared creator emit an
/// event carrying the record it creates: `mandate.credential.AccessCredential` and
/// `mandate.credential.AuthorizationCode`, through the issuance events.
/// `mandate.graph.Resource` stays: `ResourceRegistered` carries no `space_id` because
/// `RegisterResource` takes no space, and the space input is `story:declared-writers`'.
///
/// An entity leaving this set is the story's work landing and the line being deleted.
/// An entity entering it is a regression, and this case is what reports it.
const UNFOLDABLE: [(&str, &str); 12] = [
    ("mandate.credential.SigningKey", "key_reference"),
    ("mandate.delegation.Agent", "agent_type"),
    ("mandate.delegation.AgentCapabilityCeiling", "agent_id"),
    ("mandate.delegation.Approval", "subject"),
    ("mandate.delegation.Execution", "agent_id"),
    ("mandate.federation.OAuthClient", "public"),
    ("mandate.graph.Grant", "subject"),
    ("mandate.graph.Resource", "space_id"),
    ("mandate.identity.RefreshCredential", "principal_id"),
    ("mandate.policy.AuthorizationModel", "version"),
    ("mandate.policy.Policy", "version"),
    ("mandate.workload.WorkloadIdentity", "principal_id"),
];

#[test]
fn the_entities_no_event_can_rebuild_are_exactly_the_pinned_residue() {
    let mut unfoldable: BTreeMap<String, String> = BTreeMap::new();
    for (name, entity) in section("entities") {
        if transitions(entity) == 0 {
            continue;
        }
        match best_carrier(entity) {
            None => {
                unfoldable.insert(
                    name.clone(),
                    format!("no event carries {}", identity_type(entity)),
                );
            }
            Some(carrier) if !carrier.missing.is_empty() => {
                unfoldable.insert(
                    name.clone(),
                    format!(
                        "closest carrier {} misses {:?}",
                        carrier.event, carrier.missing
                    ),
                );
            }
            Some(_) => {}
        }
    }

    let found: BTreeSet<&str> = unfoldable.keys().map(String::as_str).collect();
    let pinned: BTreeSet<&str> = UNFOLDABLE.iter().map(|(name, _)| *name).collect();
    assert_eq!(
        found, pinned,
        "the set of entities whose projection cannot be rebuilt from the event log has \
         moved. Detail: {unfoldable:#?}"
    );
    for (name, example) in UNFOLDABLE {
        let detail = &unfoldable[name];
        assert!(
            detail.contains(example),
            "{name} is still unfoldable but no longer for the pinned reason: {detail}"
        );
    }
}

/// `crates/mandate-types/tests/inventory.rs:211-227` asserts this against `generated/`,
/// which is stale in a unit worktree. Asserted here against the contract as it stands, so
/// that a payload field added in a unit cannot put credential material in the log and
/// wait for regeneration to be caught.
#[test]
fn no_event_carries_credential_material() {
    let forbidden = [
        "mandate.core.CredentialSecret",
        "mandate.core.CredentialProof",
    ];
    let mut carrying: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for (name, event) in section("events") {
        for (field, reference) in fields_of(event) {
            let names = type_names(reference);
            for material in forbidden {
                if names.contains(material) {
                    carrying
                        .entry(name.clone())
                        .or_default()
                        .push(format!("{field}: {material}"));
                }
            }
        }
    }
    assert_eq!(
        carrying,
        BTreeMap::new(),
        "an event carrying credential material writes a secret into the durable log"
    );
}

/// Two commands emitting one event means a fold cannot say which command wrote a row,
/// and a payload the two disagree about is not detectable from the log at all.
#[test]
fn no_event_is_emitted_by_two_command_outcomes() {
    let duplicated: BTreeMap<String, Vec<String>> = producers()
        .into_iter()
        .filter(|(_, emitters)| emitters.len() > 1)
        .collect();
    assert_eq!(
        duplicated,
        BTreeMap::new(),
        "an event with two producers has no single writer"
    );
}

/// A declared event that no command emits is legal — `audit.yaml` declares five, and the
/// two headers this unit added (`identity.yaml:7`, `directory.yaml:5`) cite them as the
/// precedent. What makes that precedent hold is `components.yaml`: all five audit events
/// are in `mandate-worker`'s `publishes:` list, so exactly one deployment is declared to
/// write them, and `ess generate` renders that in the component's own surface.
///
/// An event that neither a command emits nor a component publishes has no declared writer
/// anywhere in the contract. `ess generate` says so in as many words — "No command in
/// this system emits it, so something outside the specification does" — while no
/// component's surface names it, so nothing a consumer can read says the event is ever
/// written. A fold that needs it cannot be shown to receive it.
#[test]
fn every_event_has_a_declared_writer() {
    let producers = producers();
    let mut published: BTreeSet<String> = BTreeSet::new();
    for component in section("components").values() {
        for event in component["publishes"].as_array().into_iter().flatten() {
            published.insert(event.as_str().expect("a published event name").to_owned());
        }
    }

    let writerless: BTreeSet<&str> = section("events")
        .keys()
        .filter(|name| !producers.contains_key(*name) && !published.contains(*name))
        .map(String::as_str)
        .collect();

    assert_eq!(
        writerless,
        BTreeSet::new(),
        "no command emits these and no component publishes them, so the contract names \
         nobody who writes them; the audit.yaml precedent their headers cite is published \
         by mandate-worker (components.yaml:157)"
    );
}

/// The yaml is the source a person edits and the compiled model is what every consumer
/// reads. `contract_adversary.rs:668` parses events with the fixed `      - name: ` and
/// `        type: ` prefixes, so a field written at any other indentation is invisible to
/// that reader while being perfectly visible to ESS — the two would disagree silently.
#[test]
fn the_yaml_event_fields_and_the_compiled_event_fields_agree() {
    fn normalize(text: &str) -> String {
        for wrapper in ["Optional", "List"] {
            if let Some(inner) = text
                .strip_prefix(wrapper)
                .and_then(|rest| rest.strip_prefix('<'))
                .and_then(|rest| rest.strip_suffix('>'))
            {
                return format!("{wrapper}<{}>", normalize(inner));
            }
        }
        if text.contains('.') {
            text.to_owned()
        } else {
            text.to_ascii_lowercase()
        }
    }

    let mut authored: BTreeMap<String, Vec<(String, String)>> = BTreeMap::new();
    let mut files: Vec<_> = std::fs::read_dir(DOMAINS)
        .unwrap_or_else(|error| panic!("{DOMAINS}: {error}"))
        .map(|entry| entry.expect("a directory entry").path())
        .filter(|path| path.extension().is_some_and(|kind| kind == "yaml"))
        .collect();
    files.sort();
    for path in files {
        let text = std::fs::read_to_string(&path)
            .unwrap_or_else(|error| panic!("{}: {error}", path.display()));
        let mut section = String::new();
        let mut key = String::new();
        let mut event = String::new();
        for line in text.lines() {
            if !line.starts_with(' ') && !line.starts_with('#') && line.ends_with(':') {
                section = line.trim_end_matches(':').to_owned();
                key.clear();
                event.clear();
                continue;
            }
            if let Some(name) = line.strip_prefix("  - name: ") {
                key.clear();
                event = if section == "events" {
                    let name = name.trim().to_owned();
                    authored.insert(name.clone(), Vec::new());
                    name
                } else {
                    String::new()
                };
                continue;
            }
            if line.starts_with("    ")
                && !line.starts_with("     ")
                && line.ends_with(':')
                && !line.trim_start().starts_with('-')
            {
                key = line.trim().trim_end_matches(':').to_owned();
                continue;
            }
            if section != "events" || key != "fields" || event.is_empty() {
                continue;
            }
            let fields = authored.get_mut(&event).expect("the event being read");
            if let Some(name) = line.strip_prefix("      - name: ") {
                fields.push((name.trim().to_owned(), String::new()));
            } else if let Some(kind) = line.strip_prefix("        type: ")
                && let Some(field) = fields.last_mut()
            {
                field.1 = normalize(kind.trim());
            }
        }
    }

    let compiled: BTreeMap<String, Vec<(String, String)>> = section("events")
        .iter()
        .map(|(name, event)| {
            (
                name.clone(),
                fields_of(event)
                    .into_iter()
                    .map(|(field, reference)| (field, canonical(reference)))
                    .collect(),
            )
        })
        .collect();

    assert_eq!(
        authored, compiled,
        "the yaml an author edits and the model every consumer reads disagree about some \
         event's fields, which means a field is written at an indentation the repository's \
         own yaml readers do not see"
    );
}

/// `generated: true` says the runtime supplies the value, and for a fresh identity or a
/// clock reading that is exactly right. It is not right for a value the caller already
/// handed the command inside a struct-typed input: the contract then says the log records
/// something the runtime invented where the caller named one, and the fold rebuilds a row
/// that no request asked for. `mandate.core.VerifiedContext` is excluded — the caller
/// identity in it is resolved by the runtime by design.
#[test]
fn no_generated_payload_field_replaces_a_value_the_caller_supplied() {
    let types = section("types");
    let mut invented: BTreeMap<String, String> = BTreeMap::new();

    for (name, command) in section("commands") {
        let mut supplied: BTreeMap<String, String> = BTreeMap::new();
        for (input, reference) in inputs_of(command) {
            for holder in type_names(reference) {
                if holder == "mandate.core.VerifiedContext" {
                    continue;
                }
                let Some(declared) = types.get(&holder) else {
                    continue;
                };
                if declared["body"]["kind"].as_str() != Some("struct") {
                    continue;
                }
                for (member, member_type) in fields_of(&declared["body"]) {
                    for carried in type_names(member_type) {
                        supplied.insert(carried, format!("input.{input}.{member}"));
                    }
                }
            }
        }
        if supplied.is_empty() {
            continue;
        }
        for outcome in command["outcomes"].as_array().expect("outcomes") {
            for payload in outcome["payload"].as_array().into_iter().flatten() {
                let event = payload["event"].as_str().expect("a payload event");
                for field in payload["fields"].as_array().expect("payload fields") {
                    if field["value"]["kind"].as_str() != Some("generated") {
                        continue;
                    }
                    let target = field["target"].as_str().expect("a payload target");
                    for carried in type_names(&field["target_type"]) {
                        if let Some(source) = supplied.get(&carried) {
                            invented.insert(
                                format!("{event}.{target}"),
                                format!(
                                    "{name} takes {source}: {carried} and generates it instead"
                                ),
                            );
                        }
                    }
                }
            }
        }
    }

    assert_eq!(
        invented,
        BTreeMap::new(),
        "a payload field the caller supplied and the contract generates makes the folded \
         row differ from the request that produced it"
    );
}

/// An event that writes many records at once carries their fields as parallel lists, and
/// nothing in the contract says the lists are the same length or that index `i` of one
/// belongs with index `i` of another. One list is a set of records; two are a join the
/// fold has to guess. The acceptance statement is per row — "each projection row can be
/// produced from its events" — and a row assembled by positional correspondence is
/// produced from an assumption, not from the log.
#[test]
fn no_projection_row_is_assembled_from_two_parallel_lists() {
    let mut guessed: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for (name, entity) in section("entities") {
        if transitions(entity) == 0 {
            continue;
        }
        let Some(carrier) = best_carrier(entity) else {
            continue;
        };
        if !carrier.missing.is_empty() {
            continue;
        }
        let event = &section("events")[&carrier.event];
        let fields: BTreeMap<String, &Value> = fields_of(event).into_iter().collect();
        let identity = identity_type(entity);

        // A list on the event where the record holds one value is a plural carrier; a
        // list on the event where the record holds a list is just that field.
        let mut plural: Vec<String> = Vec::new();
        if let Some((field, reference)) = fields
            .iter()
            .find(|(_, reference)| type_names(reference).contains(&identity))
            && canonical(reference).starts_with("List<")
        {
            plural.push(format!("{field} carries the identity of many records"));
        }
        for (field, declared) in fields_of(entity) {
            if canonical(declared).starts_with("List<") {
                continue;
            }
            if let Some((carried, reference)) = carrier_field(&fields, &field)
                && canonical(reference).starts_with("List<")
            {
                plural.push(format!("{carried} carries {field} for many records"));
            }
        }
        if plural.len() > 1 {
            guessed.insert(format!("{name} <- {}", carrier.event), plural);
        }
    }

    assert_eq!(
        guessed,
        BTreeMap::new(),
        "these projections fold only if the reader pairs two lists by position, which the \
         contract nowhere declares"
    );
}
