//! Adversary pass 1 over the `federation-verifier` unit of
//! `story:signing-and-verification`.
//!
//! Every case here drives `verifier_real.rs` against a document the unit itself cites —
//! `tests/security/cases.json`, `docs/architecture/federated-login.md`,
//! `docs/sources/original-design.md` §29.2 and §29.3 — or against a property the module's
//! own documentation claims. Nothing in this file changes an implementation.
//!
//! No key is committed: every key is generated by `aws_lc_rs` when the case runs. No case
//! reaches the network: the HTTP cases bind their own `TcpListener` on the loopback
//! interface and answer themselves.

use std::io::{BufRead, BufReader, Write};
use std::net::TcpListener;
use std::panic::AssertUnwindSafe;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, OnceLock, mpsc};
use std::thread::JoinHandle;
use std::time::{Duration, Instant};

use aws_lc_rs::encoding::{AsDer, Pkcs8V1Der};
use aws_lc_rs::rand::SystemRandom;
use aws_lc_rs::signature::{ECDSA_P256_SHA256_FIXED_SIGNING, EcdsaKeyPair};
use jsonwebtoken::jwk::Jwk;
use jsonwebtoken::{Algorithm, EncodingKey, Header, encode};
use mandate_federation::authenticate::{
    AuthenticateFederation, Authenticated, authenticate_federation,
};
use mandate_federation::record::{
    ConnectionState, FederationConnection, FederationEvent, Projection,
};
use mandate_federation::verifier_real::{
    AllowedAlgorithms, FixedClock, InMemoryJwks, JwksSource, RealVerifier, RefusalReason, UreqJwks,
};
use mandate_federation::{
    DenialClause, Denied, FederationVerifier, RecordingSessionIssuer, RequestContext,
};
use mandate_model::TenantResolutionRule;
use mandate_types::value::Uuid;
use mandate_types::{
    Audience, ClientId, CorrelationId, CredentialId, CredentialProof, DenialReason,
    ExternalLinkMethod, ExternalPrincipalId, ExternalSubject, FederationConnectionId, Issuer,
    OrganizationId, PrincipalId, SigningAlgorithm, Timestamp, VerifiedContext,
};

const ISSUER_ONE: &str = "https://idp.example/one";
const ISSUER_TWO: &str = "https://idp.example/two";
const CLIENT: &str = "configured-client";
const SUBJECT: &str = "subject-one";
const EMAIL: &str = "person@acme.example";
const RS256: &str = "RS256";
const ES256: &str = "ES256";
const NOW: u64 = 1_758_240_000;

// ---------------------------------------------------------------- key material

struct Keys {
    signing: EncodingKey,
    published: Jwk,
    algorithm: Algorithm,
    kid: String,
}

fn rsa_pkcs1() -> &'static [u8] {
    static GENERATED: OnceLock<Vec<u8>> = OnceLock::new();
    GENERATED.get_or_init(|| {
        let pair = aws_lc_rs::rsa::KeyPair::generate(aws_lc_rs::rsa::KeySize::Rsa2048)
            .expect("an RSA key");
        let pkcs8: Pkcs8V1Der<'static> = pair.as_der().expect("the generated key in PKCS#8 DER");
        pkcs1_of(pkcs8.as_ref())
    })
}

/// The RFC 8017 `RSAPrivateKey` inside a PKCS#8 wrapper.
fn pkcs1_of(pkcs8: &[u8]) -> Vec<u8> {
    let (_, body, _) = element(pkcs8);
    let (_, _, after_version) = element(body);
    let (_, _, after_algorithm) = element(after_version);
    let (_, key, _) = element(after_algorithm);
    key.to_vec()
}

fn element(input: &[u8]) -> (u8, &[u8], &[u8]) {
    let first = usize::from(input[1]);
    let (length, header) = if first < 0x80 {
        (first, 2)
    } else {
        let count = first & 0x7f;
        let mut length = 0_usize;
        for byte in &input[2..2 + count] {
            length = (length << 8) | usize::from(*byte);
        }
        (length, 2 + count)
    };
    (
        input[0],
        &input[header..header + length],
        &input[header + length..],
    )
}

fn keys(algorithm: Algorithm, kid: &str) -> Keys {
    let signing = match algorithm {
        Algorithm::RS256 => EncodingKey::from_rsa_der(rsa_pkcs1()),
        Algorithm::ES256 => EncodingKey::from_ec_der(
            EcdsaKeyPair::generate_pkcs8(&ECDSA_P256_SHA256_FIXED_SIGNING, &SystemRandom::new())
                .expect("a generated elliptic-curve key")
                .as_ref(),
        ),
        other => panic!("no key is generated for {other:?}"),
    };
    let mut published = Jwk::from_encoding_key(&signing, algorithm).expect("a public JWK");
    published.common.key_id = Some(kid.to_owned());
    Keys {
        signing,
        published,
        algorithm,
        kid: kid.to_owned(),
    }
}

fn key_set(published: &[&Keys]) -> serde_json::Value {
    serde_json::json!({
        "keys": published
            .iter()
            .map(|keys| serde_json::to_value(&keys.published).expect("a serializable JWK"))
            .collect::<Vec<_>>(),
    })
}

/// The published JWK of `keys`, as JSON, with `field` set to `value`.
fn published_with(keys: &Keys, field: &str, value: serde_json::Value) -> serde_json::Value {
    let mut jwk = serde_json::to_value(&keys.published).expect("a serializable JWK");
    jwk.as_object_mut()
        .expect("a JWK object")
        .insert(field.to_owned(), value);
    serde_json::json!({ "keys": [jwk] })
}

/// The published JWK of `keys`, as JSON, without `field`.
fn published_without(keys: &Keys, field: &str) -> serde_json::Value {
    let mut jwk = serde_json::to_value(&keys.published).expect("a serializable JWK");
    jwk.as_object_mut().expect("a JWK object").remove(field);
    serde_json::json!({ "keys": [jwk] })
}

// --------------------------------------------------------------------- tokens

fn claims(issuer: &str, subject: &str) -> serde_json::Value {
    serde_json::json!({
        "iss": issuer,
        "sub": subject,
        "aud": CLIENT,
        "iat": NOW,
        "exp": NOW + 300,
    })
}

fn with(mut claims: serde_json::Value, name: &str, value: serde_json::Value) -> serde_json::Value {
    claims
        .as_object_mut()
        .expect("a claims object")
        .insert(name.to_owned(), value);
    claims
}

fn mint(keys: &Keys, claims: &serde_json::Value) -> CredentialProof {
    let mut header = Header::new(keys.algorithm);
    header.kid = Some(keys.kid.clone());
    let token = encode(&header, claims, &keys.signing).expect("a signed token");
    CredentialProof::from_bytes(token.into_bytes())
}

/// A real signature by `keys` over a header this file assembled, which `Header` cannot
/// express.
fn minted_under(
    keys: &Keys,
    header: &serde_json::Value,
    claims: &serde_json::Value,
) -> CredentialProof {
    signed_under(keys, keys.algorithm, header, claims)
}

fn signed_under(
    keys: &Keys,
    algorithm: Algorithm,
    header: &serde_json::Value,
    claims: &serde_json::Value,
) -> CredentialProof {
    let input = format!(
        "{}.{}",
        base64url(header.to_string().as_bytes()),
        base64url(claims.to_string().as_bytes())
    );
    let signature = jsonwebtoken::crypto::sign(input.as_bytes(), &keys.signing, algorithm)
        .expect("a signature over the assembled input");
    CredentialProof::from_bytes(format!("{input}.{signature}").into_bytes())
}

/// A token signed with a shared secret, however its header names itself.
fn hmac_signed(
    secret: &[u8],
    header: &serde_json::Value,
    claims: &serde_json::Value,
) -> CredentialProof {
    let input = format!(
        "{}.{}",
        base64url(header.to_string().as_bytes()),
        base64url(claims.to_string().as_bytes())
    );
    let signature = jsonwebtoken::crypto::sign(
        input.as_bytes(),
        &EncodingKey::from_secret(secret),
        Algorithm::HS256,
    )
    .expect("an HMAC over the assembled input");
    CredentialProof::from_bytes(format!("{input}.{signature}").into_bytes())
}

fn base64url(bytes: &[u8]) -> String {
    const ALPHABET: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
    let mut encoded = String::new();
    for chunk in bytes.chunks(3) {
        let first = u32::from(chunk[0]);
        let second = u32::from(chunk.get(1).copied().unwrap_or_default());
        let third = u32::from(chunk.get(2).copied().unwrap_or_default());
        let packed = (first << 16) | (second << 8) | third;
        encoded.push(char::from(ALPHABET[((packed >> 18) & 63) as usize]));
        encoded.push(char::from(ALPHABET[((packed >> 12) & 63) as usize]));
        if chunk.len() > 1 {
            encoded.push(char::from(ALPHABET[((packed >> 6) & 63) as usize]));
        }
        if chunk.len() > 2 {
            encoded.push(char::from(ALPHABET[(packed & 63) as usize]));
        }
    }
    encoded
}

// ------------------------------------------------------------------- the crate

fn uuid(tag: u8) -> Uuid {
    Uuid::from_bytes([tag; 16])
}

fn organization(tag: u8) -> OrganizationId {
    OrganizationId::new(uuid(tag))
}

fn connection(tag: u8) -> FederationConnectionId {
    FederationConnectionId::new(uuid(tag))
}

fn principal(tag: u8) -> PrincipalId {
    PrincipalId::new(uuid(tag))
}

fn context(organization_id: OrganizationId) -> VerifiedContext {
    VerifiedContext {
        subject: principal(0x51),
        actor: None,
        organization: organization_id,
        audience: Audience::new("mandate"),
        credential: CredentialId::new(uuid(0xcd)),
        delegation: None,
        execution: None,
        correlation: CorrelationId::new("adversary-verifier-1"),
    }
}

fn on_claim(organization_id: OrganizationId, name: &str, value: &str) -> TenantResolutionRule {
    TenantResolutionRule {
        configured_organization: organization_id,
        verified_claim_name: Some(name.to_owned()),
        verified_claim_value: Some(value.to_owned()),
    }
}

fn unconditional(organization_id: OrganizationId) -> TenantResolutionRule {
    TenantResolutionRule {
        configured_organization: organization_id,
        verified_claim_name: None,
        verified_claim_value: None,
    }
}

fn created(
    connection_id: FederationConnectionId,
    organization_id: OrganizationId,
    issuer: &str,
    tenant_resolution: TenantResolutionRule,
) -> FederationEvent {
    FederationEvent::FederationConnectionCreated {
        context: context(organization_id),
        connection_id,
        issuer: Issuer::new(issuer),
        client_id: ClientId::new(CLIENT),
        tenant_resolution,
        jit_provisioning: false,
    }
}

fn linked(
    connection_id: FederationConnectionId,
    organization_id: OrganizationId,
    subject: &str,
    principal_id: PrincipalId,
) -> FederationEvent {
    FederationEvent::ExternalPrincipalLinked {
        context: context(organization_id),
        connection_id,
        principal_id,
        external_principal_id: ExternalPrincipalId::new(uuid(0x71)),
        subject: ExternalSubject::new(subject),
        link_method: ExternalLinkMethod::Administrator,
        linked_at: Timestamp::new("2026-09-18T00:00:00Z"),
    }
}

fn request() -> RequestContext {
    RequestContext {
        audience: Audience::new("mandate"),
        correlation: CorrelationId::new("adversary-verifier-1"),
        credential: CredentialId::new(uuid(0xcd)),
        at: Timestamp::new("2026-09-18T00:00:00Z"),
    }
}

fn a_connection(issuer: &str) -> FederationConnection {
    a_connection_of(connection(1), issuer)
}

fn a_connection_of(id: FederationConnectionId, issuer: &str) -> FederationConnection {
    FederationConnection {
        id,
        organization_id: organization(10),
        issuer: Issuer::new(issuer),
        client_id: ClientId::new(CLIENT),
        tenant_resolution: unconditional(organization(10)),
        jit_provisioning: false,
        state: ConnectionState::Enabled,
    }
}

fn allowlist() -> AllowedAlgorithms {
    AllowedAlgorithms::configured(&[SigningAlgorithm::new(RS256), SigningAlgorithm::new(ES256)])
        .expect("the approved allowlist is admitted")
}

fn verifier(
    source: &InMemoryJwks,
    clock: &FixedClock,
    configured: &[(FederationConnectionId, &str)],
) -> RealVerifier<InMemoryJwks, FixedClock> {
    let mut built = RealVerifier::new(allowlist(), source.clone(), clock.clone());
    for (connection_id, name) in configured {
        built = built
            .configure_connection(*connection_id, &SigningAlgorithm::new(*name))
            .expect("an admitted algorithm for this connection");
    }
    built
}

fn authenticate(
    projection: &Projection,
    connection_id: FederationConnectionId,
    verifier: &RealVerifier<InMemoryJwks, FixedClock>,
    proof: CredentialProof,
) -> Result<Authenticated, Denied> {
    let input = AuthenticateFederation {
        connection_id,
        proof,
    };
    let mut sessions = RecordingSessionIssuer::new();
    authenticate_federation(
        &input,
        &request(),
        verifier,
        projection,
        projection,
        &mut sessions,
    )
}

// =================================================== 1. the unit's own contract
//
// `tests/security/cases.json`, case `tenant-unverified`: "Org selector or email domain
// provided without verified binding" -> "deny; no fallback".
// `docs/architecture/federated-login.md:93`: "No email-domain, hostname or
// unverified-input fallback may be required at any point".

/// An `email` claim the issuer never asserted it verified is not a validated claim.
#[test]
fn an_email_claim_without_email_verified_is_not_a_validated_claim() {
    let rsa = keys(Algorithm::RS256, "one-2026-09");
    let source = InMemoryJwks::new();
    source.publish(&Issuer::new(ISSUER_ONE), key_set(&[&rsa]));
    let clock = FixedClock::at(NOW);
    let verifier = verifier(&source, &clock, &[(connection(1), RS256)]);
    // OIDC Core 5.1 defines exactly one assertion about an address: `email_verified`,
    // "True if the End-User's e-mail address has been verified". An issuer that sends no
    // companion has asserted nothing, which is not an assertion that it checked.
    let proof = mint(
        &rsa,
        &with(claims(ISSUER_ONE, SUBJECT), "email", EMAIL.into()),
    );

    let validated = verifier
        .verify(&a_connection(ISSUER_ONE), &proof)
        .expect("the signature is valid; the address's standing is not the signature's");

    assert_eq!(
        validated.verified_claim("email"),
        None,
        "an address with no `email_verified` companion was never asserted verified"
    );
    assert_eq!(
        validated.unverified_hint("email"),
        Some(EMAIL),
        "it is reachable only as a hint"
    );
}

/// `tenant-unverified` holds when the issuer omits `email_verified` rather than sending
/// it false.
#[test]
fn tenant_unverified_holds_when_the_issuer_omits_email_verified() {
    let rsa = keys(Algorithm::RS256, "one-2026-09");
    let source = InMemoryJwks::new();
    source.publish(&Issuer::new(ISSUER_ONE), key_set(&[&rsa]));
    let clock = FixedClock::at(NOW);
    let verifier = verifier(&source, &clock, &[(connection(1), RS256)]);
    let log = vec![
        created(
            connection(1),
            organization(10),
            ISSUER_ONE,
            on_claim(organization(10), "email", EMAIL),
        ),
        linked(connection(1), organization(10), SUBJECT, principal(0x21)),
    ];
    let projection = Projection::fold(&log).expect("one connection, one link");
    let proof = mint(
        &rsa,
        &with(claims(ISSUER_ONE, SUBJECT), "email", EMAIL.into()),
    );

    let denied = authenticate(&projection, connection(1), &verifier, proof)
        .expect_err("the email domain arrived without a verified binding: deny, no fallback");

    assert_eq!(denied.reason, DenialReason::TenantMismatch);
    assert_eq!(
        denied.clause,
        DenialClause::UnverifiedFallback,
        "the value that would have resolved the tenant was never asserted verified"
    );
}

// ============================================== 2. key-ID abuse and refresh storms
//
// `docs/sources/original-design.md:2529-2535` requires the JWKS fetch to be hardened
// against "key-ID abuse" and "excessive refresh storms". `verifier_real.rs:628-630`
// claims it is: "a set read a moment ago is not read again for the same `kid`, which is
// what stops an unknown `kid` from becoming a fetch per proof."

/// An unknown `kid`, presented over and over, does not become one source read per proof.
#[test]
fn an_unknown_kid_is_not_one_source_read_per_presentation() {
    let published = keys(Algorithm::ES256, "2026-09");
    let attacker = keys(Algorithm::ES256, "attacker-chosen");
    let source = InMemoryJwks::new();
    source.publish(&Issuer::new(ISSUER_ONE), key_set(&[&published]));
    let clock = FixedClock::at(NOW);
    let verifier = verifier(&source, &clock, &[(connection(1), ES256)]);

    verifier
        .verify(
            &a_connection(ISSUER_ONE),
            &mint(&published, &claims(ISSUER_ONE, SUBJECT)),
        )
        .expect("the published key verifies, and the set is now cached");
    let after_warmup = source.fetches();

    // Nothing here is signed by a key the issuer published, and nothing here needs to be:
    // the key is resolved before the signature is checked, so an unauthenticated caller
    // reaches the source.
    for _ in 0..20 {
        verifier
            .verify(
                &a_connection(ISSUER_ONE),
                &mint(&attacker, &claims(ISSUER_ONE, SUBJECT)),
            )
            .expect_err("no published key carries this kid");
    }

    assert!(
        source.fetches() <= after_warmup + 1,
        "20 presentations of one unknown kid cost {} source reads, not the single refetch \
         the cache is documented to bound them to (verifier_real.rs:628-630)",
        source.fetches() - after_warmup
    );
}

/// A slow key-set read for one issuer does not stall a verification for another issuer.
#[test]
fn a_slow_key_set_read_does_not_stall_another_issuers_verification() {
    struct SlowJwks {
        inner: InMemoryJwks,
        slow: String,
        entered: Arc<AtomicBool>,
    }

    impl JwksSource for SlowJwks {
        fn jwks(&self, issuer: &Issuer) -> Option<serde_json::Value> {
            if issuer.as_str() == self.slow {
                self.entered.store(true, Ordering::SeqCst);
                std::thread::sleep(Duration::from_millis(1500));
            }
            self.inner.jwks(issuer)
        }
    }

    let slow_key = keys(Algorithm::ES256, "slow-2026-09");
    let fast_key = keys(Algorithm::ES256, "fast-2026-09");
    let inner = InMemoryJwks::new();
    inner.publish(&Issuer::new(ISSUER_ONE), key_set(&[&slow_key]));
    inner.publish(&Issuer::new(ISSUER_TWO), key_set(&[&fast_key]));
    let entered = Arc::new(AtomicBool::new(false));
    let source = SlowJwks {
        inner,
        slow: ISSUER_ONE.to_owned(),
        entered: Arc::clone(&entered),
    };
    let clock = FixedClock::at(NOW);
    let built = RealVerifier::new(allowlist(), source, clock)
        .configure_connection(connection(1), &SigningAlgorithm::new(ES256))
        .and_then(|built| built.configure_connection(connection(2), &SigningAlgorithm::new(ES256)))
        .expect("an admitted algorithm for both connections");

    let slow_proof = mint(&slow_key, &claims(ISSUER_ONE, SUBJECT));
    let fast_proof = mint(&fast_key, &claims(ISSUER_TWO, SUBJECT));
    let elapsed = std::thread::scope(|scope| {
        scope.spawn(|| {
            let _ = built.verify(&a_connection_of(connection(1), ISSUER_ONE), &slow_proof);
        });
        let deadline = Instant::now() + Duration::from_secs(5);
        while !entered.load(Ordering::SeqCst) && Instant::now() < deadline {
            std::thread::sleep(Duration::from_millis(5));
        }
        assert!(
            entered.load(Ordering::SeqCst),
            "the slow read never started"
        );
        std::thread::sleep(Duration::from_millis(50));
        let started = Instant::now();
        let _ = built.verify(&a_connection_of(connection(2), ISSUER_TWO), &fast_proof);
        started.elapsed()
    });

    assert!(
        elapsed < Duration::from_millis(500),
        "a verification against {ISSUER_TWO} took {elapsed:?} because a read for \
         {ISSUER_ONE} held the key cache across the port call (verifier_real.rs:631-661)"
    );
}

// ================================================= 3. the transport, on loopback
//
// `docs/sources/original-design.md:2529-2535`: the customer JWKS fetch must be hardened
// against SSRF, DNS rebinding, unbounded redirects, unexpected schemes, huge documents,
// cache poisoning, key-ID abuse and excessive refresh storms. `verifier_real.rs:48-53`
// claims the redirect and the URI halves of that list.

/// The shipped source answers an `https` issuer without panicking, that being every real
/// issuer.
#[test]
fn an_https_issuer_does_not_panic_the_shipped_source() {
    let listener = TcpListener::bind("127.0.0.1:0").expect("a loopback port the test owns");
    let address = listener.local_addr().expect("the bound address");
    let (connected, arrived) = mpsc::channel();
    std::thread::spawn(move || {
        while listener.accept().is_ok() {
            let _ = connected.send(());
        }
    });
    let source = UreqJwks::new();

    let outcome = std::panic::catch_unwind(AssertUnwindSafe(|| {
        source.jwks(&Issuer::new(format!("https://{address}")))
    }));

    let _ = arrived.recv_timeout(Duration::from_millis(500));
    let panicked = outcome.err().map(|payload| {
        payload
            .downcast_ref::<String>()
            .cloned()
            .or_else(|| {
                payload
                    .downcast_ref::<&str>()
                    .map(|text| (*text).to_owned())
            })
            .unwrap_or_else(|| "a panic with an unreadable payload".to_owned())
    });
    assert_eq!(
        panicked, None,
        "the shipped JWKS source panicked on an https issuer instead of answering"
    );
}

/// A `jwks_uri` on a host the issuer's own prefix does not cover is not fetched.
#[test]
fn an_https_jwks_uri_on_another_host_is_not_fetched() {
    let elsewhere = TcpListener::bind("127.0.0.1:0").expect("a loopback port the test owns");
    let elsewhere_address = elsewhere.local_addr().expect("the bound address");
    let (connected, arrived) = mpsc::channel();
    std::thread::spawn(move || {
        while elsewhere.accept().is_ok() {
            let _ = connected.send(());
        }
    });
    let listener = TcpListener::bind("127.0.0.1:0").expect("a loopback port the test owns");
    let issuer = format!(
        "http://{}",
        listener.local_addr().expect("the bound address")
    );
    let discovery = serde_json::json!({
        "issuer": issuer,
        "jwks_uri": format!("https://{elsewhere_address}/jwks"),
    });
    let served = serve(listener, discovery, serde_json::json!({ "keys": [] }), 1);
    let source = UreqJwks::over(ureq::Agent::new_with_config(
        ureq::config::Config::builder()
            .max_redirects(0)
            .proxy(None)
            .build(),
    ));

    let _ = std::panic::catch_unwind(AssertUnwindSafe(|| {
        source.jwks(&Issuer::new(issuer.as_str()))
    }));

    let reached = arrived.recv_timeout(Duration::from_secs(2)).is_ok();
    assert_eq!(
        served.join().expect("the listener thread"),
        vec!["/.well-known/openid-configuration".to_owned()],
        "the document was read"
    );
    assert!(
        !reached,
        "the source opened a connection to {elsewhere_address}, a host the issuer {issuer} \
         does not cover: an absolute https URI is admitted whatever it names \
         (verifier_real.rs:263-271)"
    );
}

/// A `jwks_uri` whose userinfo spells the issuer is not fetched from the host after the
/// `@`.
#[test]
fn a_jwks_uri_whose_userinfo_spells_the_issuer_is_not_fetched() {
    let elsewhere = TcpListener::bind("127.0.0.1:0").expect("a loopback port the test owns");
    let elsewhere_address = elsewhere.local_addr().expect("the bound address");
    let (connected, arrived) = mpsc::channel();
    std::thread::spawn(move || {
        while let Ok((mut stream, _)) = elsewhere.accept() {
            let _ = connected.send(());
            let body = serde_json::json!({ "keys": [] }).to_string();
            let _ = stream.write_all(
                format!(
                    "HTTP/1.1 200 OK\r\ncontent-type: application/json\r\ncontent-length: {}\r\nconnection: close\r\n\r\n{body}",
                    body.len()
                )
                .as_bytes(),
            );
        }
    });
    let listener = TcpListener::bind("127.0.0.1:0").expect("a loopback port the test owns");
    let authority = listener.local_addr().expect("the bound address");
    let issuer = format!("http://{authority}");
    // A string prefix is not an origin: `http://<issuer authority>@<other host>/jwks`
    // starts with the issuer and names another host.
    let discovery = serde_json::json!({
        "issuer": issuer,
        "jwks_uri": format!("http://{authority}@{elsewhere_address}/jwks"),
    });
    let served = serve(listener, discovery, serde_json::json!({ "keys": [] }), 1);
    let source = UreqJwks::over(ureq::Agent::new_with_config(
        ureq::config::Config::builder()
            .max_redirects(0)
            .proxy(None)
            .build(),
    ));

    let _ = std::panic::catch_unwind(AssertUnwindSafe(|| {
        source.jwks(&Issuer::new(issuer.as_str()))
    }));

    let reached = arrived.recv_timeout(Duration::from_secs(2)).is_ok();
    assert_eq!(
        served.join().expect("the listener thread"),
        vec!["/.well-known/openid-configuration".to_owned()],
        "the document was read"
    );
    assert!(
        !reached,
        "the source fetched from {elsewhere_address}: the guard compares a string prefix, \
         and userinfo before the `@` satisfies it (verifier_real.rs:267)"
    );
}

/// The shipped source, not one a case configured, follows no redirect away from the
/// `jwks_uri`.
#[test]
fn the_shipped_source_follows_no_redirect() {
    let listener = TcpListener::bind("127.0.0.1:0").expect("a loopback port the test owns");
    let address = listener.local_addr().expect("the bound address");
    let issuer = format!("http://{address}");
    let discovery = serde_json::json!({
        "issuer": issuer,
        "jwks_uri": format!("{issuer}/jwks"),
    });
    let moved = format!("{issuer}/moved-key-set");
    let served = std::thread::spawn(move || {
        let mut asked = Vec::new();
        for _ in 0..2 {
            let Ok((mut stream, _)) = listener.accept() else {
                break;
            };
            let path = request_path(&stream);
            let response = if path.contains("openid-configuration") {
                let body = discovery.to_string();
                format!(
                    "HTTP/1.1 200 OK\r\ncontent-type: application/json\r\ncontent-length: {}\r\nconnection: close\r\n\r\n{body}",
                    body.len()
                )
            } else {
                format!(
                    "HTTP/1.1 302 Found\r\nlocation: {moved}\r\ncontent-length: 0\r\nconnection: close\r\n\r\n"
                )
            };
            let _ = stream.write_all(response.as_bytes());
            let _ = stream.flush();
            asked.push(path);
        }
        asked
    });
    let source = UreqJwks::new();

    assert!(
        source.jwks(&Issuer::new(issuer.as_str())).is_none(),
        "a redirect is not a key set"
    );
    assert_eq!(
        served.join().expect("the listener thread"),
        vec![
            "/.well-known/openid-configuration".to_owned(),
            "/jwks".to_owned()
        ],
        "the redirect target was never asked for"
    );
}

/// A key set the issuer serves as something other than a JWKS refuses the proof.
#[test]
fn a_key_set_body_that_is_not_a_jwks_is_refused() {
    for body in [
        String::new(),
        "not json at all".to_owned(),
        "{}".to_owned(),
        serde_json::json!({ "keys": "one" }).to_string(),
    ] {
        let listener = TcpListener::bind("127.0.0.1:0").expect("a loopback port the test owns");
        let address = listener.local_addr().expect("the bound address");
        let issuer = format!("http://{address}");
        let discovery = serde_json::json!({
            "issuer": issuer,
            "jwks_uri": format!("{issuer}/jwks"),
        });
        let served = std::thread::spawn(move || {
            let mut asked = Vec::new();
            for _ in 0..2 {
                let Ok((mut stream, _)) = listener.accept() else {
                    break;
                };
                let path = request_path(&stream);
                let payload = if path.contains("openid-configuration") {
                    discovery.to_string()
                } else {
                    body.clone()
                };
                let _ = stream.write_all(
                    format!(
                        "HTTP/1.1 200 OK\r\ncontent-type: application/json\r\ncontent-length: {}\r\nconnection: close\r\n\r\n{payload}",
                        payload.len()
                    )
                    .as_bytes(),
                );
                let _ = stream.flush();
                asked.push(path);
            }
            asked
        });
        let source = UreqJwks::over(ureq::Agent::new_with_config(
            ureq::config::Config::builder()
                .max_redirects(0)
                .proxy(None)
                .build(),
        ));
        let clock = FixedClock::at(NOW);
        let built = RealVerifier::new(allowlist(), source, clock)
            .configure_connection(connection(1), &SigningAlgorithm::new(RS256))
            .expect("an admitted algorithm");
        let rsa = keys(Algorithm::RS256, "one-2026-09");

        let outcome = built.verify(
            &a_connection(issuer.as_str()),
            &mint(&rsa, &claims(issuer.as_str(), SUBJECT)),
        );

        assert!(
            outcome.is_err(),
            "a body that is not a key set verified a proof"
        );
        let _ = served.join();
    }
}

/// A listener that answers exactly `requests` requests and returns the paths it was asked
/// for.
fn serve(
    listener: TcpListener,
    discovery: serde_json::Value,
    jwks: serde_json::Value,
    requests: usize,
) -> JoinHandle<Vec<String>> {
    std::thread::spawn(move || {
        let mut asked = Vec::new();
        for _ in 0..requests {
            let Ok((mut stream, _)) = listener.accept() else {
                break;
            };
            let path = request_path(&stream);
            let body = if path.contains("openid-configuration") {
                discovery.to_string()
            } else {
                jwks.to_string()
            };
            let response = format!(
                "HTTP/1.1 200 OK\r\ncontent-type: application/json\r\ncontent-length: {}\r\nconnection: close\r\n\r\n{body}",
                body.len()
            );
            let _ = stream.write_all(response.as_bytes());
            let _ = stream.flush();
            asked.push(path);
        }
        asked
    })
}

/// The path of the request on this connection, with its headers read off the wire.
fn request_path(stream: &std::net::TcpStream) -> String {
    let mut reader = BufReader::new(stream.try_clone().expect("a reader over the connection"));
    let mut line = String::new();
    let _ = reader.read_line(&mut line);
    let path = line
        .split_whitespace()
        .nth(1)
        .unwrap_or_default()
        .to_owned();
    loop {
        let mut header = String::new();
        match reader.read_line(&mut header) {
            Ok(0) | Err(_) => break,
            Ok(_) if header.trim().is_empty() => break,
            Ok(_) => (),
        }
    }
    path
}

// =============================================== 4. the header, and what it selects
//
// `docs/sources/original-design.md:2527`: never select algorithms solely from untrusted
// token headers.

/// A shared-secret signature under a header naming an admitted algorithm is refused.
#[test]
fn an_hmac_signature_named_as_an_admitted_algorithm_is_refused() {
    let rsa = keys(Algorithm::RS256, "one-2026-09");
    let source = InMemoryJwks::new();
    source.publish(&Issuer::new(ISSUER_ONE), key_set(&[&rsa]));
    let clock = FixedClock::at(NOW);
    let verifier = verifier(&source, &clock, &[(connection(1), RS256)]);
    // The classic confusion: the verification key's own published material as the shared
    // secret, under a header that names the algorithm the connection expects.
    let material = serde_json::to_vec(&rsa.published).expect("the published key as bytes");

    for named in ["RS256", "ES256", "HS256", "none"] {
        let header = serde_json::json!({ "alg": named, "typ": "JWT", "kid": rsa.kid });
        let denied = verifier
            .verify(
                &a_connection(ISSUER_ONE),
                &hmac_signed(&material, &header, &claims(ISSUER_ONE, SUBJECT)),
            )
            .expect_err("a shared-secret signature verifies nothing here");
        assert_eq!(denied.reason, DenialReason::InvalidCredential, "{named}");
    }
}

/// A header algorithm spelled in another case is not the configured algorithm.
#[test]
fn a_header_algorithm_in_another_case_is_refused() {
    let rsa = keys(Algorithm::RS256, "one-2026-09");
    let source = InMemoryJwks::new();
    source.publish(&Issuer::new(ISSUER_ONE), key_set(&[&rsa]));
    let clock = FixedClock::at(NOW);
    let verifier = verifier(&source, &clock, &[(connection(1), RS256)]);
    let header = serde_json::json!({ "alg": "rs256", "typ": "JWT", "kid": rsa.kid });

    let denied = verifier
        .verify(
            &a_connection(ISSUER_ONE),
            &minted_under(&rsa, &header, &claims(ISSUER_ONE, SUBJECT)),
        )
        .expect_err("`rs256` is not `RS256`");

    assert_eq!(denied.clause, DenialClause::AlgorithmPolicy);
    assert_eq!(
        verifier.refusals(),
        vec![RefusalReason::HeaderAlgorithmNotConfigured]
    );
}

/// A header that names no algorithm at all is refused.
#[test]
fn a_header_that_names_no_algorithm_is_refused() {
    let rsa = keys(Algorithm::RS256, "one-2026-09");
    let source = InMemoryJwks::new();
    source.publish(&Issuer::new(ISSUER_ONE), key_set(&[&rsa]));
    let clock = FixedClock::at(NOW);
    let verifier = verifier(&source, &clock, &[(connection(1), RS256)]);
    let header = serde_json::json!({ "typ": "JWT", "kid": rsa.kid });

    let denied = verifier
        .verify(
            &a_connection(ISSUER_ONE),
            &minted_under(&rsa, &header, &claims(ISSUER_ONE, SUBJECT)),
        )
        .expect_err("a header with no `alg` selects nothing");

    assert_eq!(denied.reason, DenialReason::InvalidCredential);
    assert_eq!(verifier.refusals(), vec![RefusalReason::MalformedToken]);
}

/// A header naming a critical extension the verifier does not understand is refused.
#[test]
fn a_header_naming_a_critical_extension_is_refused() {
    let rsa = keys(Algorithm::RS256, "one-2026-09");
    let source = InMemoryJwks::new();
    source.publish(&Issuer::new(ISSUER_ONE), key_set(&[&rsa]));
    let clock = FixedClock::at(NOW);
    let verifier = verifier(&source, &clock, &[(connection(1), RS256)]);
    // RFC 7515 4.1.11: a recipient MUST reject a JWS whose `crit` names a header
    // parameter it does not understand. Nothing here reads `crit`, so nothing here can
    // understand what it names.
    let header = serde_json::json!({
        "alg": "RS256",
        "typ": "JWT",
        "kid": rsa.kid,
        "crit": ["urn:example:unread"],
        "urn:example:unread": "this changes what the token means",
    });

    let outcome = verifier.verify(
        &a_connection(ISSUER_ONE),
        &minted_under(&rsa, &header, &claims(ISSUER_ONE, SUBJECT)),
    );

    assert!(
        outcome.is_err(),
        "a critical header parameter nothing understands was admitted (RFC 7515 4.1.11)"
    );
}

/// Key and certificate URLs in the header are ignored, and never fetched.
#[test]
fn key_and_certificate_urls_in_the_header_are_never_fetched() {
    let elsewhere = TcpListener::bind("127.0.0.1:0").expect("a loopback port the test owns");
    let elsewhere_address = elsewhere.local_addr().expect("the bound address");
    let (connected, arrived) = mpsc::channel();
    std::thread::spawn(move || {
        while elsewhere.accept().is_ok() {
            let _ = connected.send(());
        }
    });
    let published = keys(Algorithm::RS256, "one-2026-09");
    let attacker = keys(Algorithm::ES256, "one-2026-09");
    let source = InMemoryJwks::new();
    source.publish(&Issuer::new(ISSUER_ONE), key_set(&[&published]));
    let clock = FixedClock::at(NOW);
    let verifier = verifier(&source, &clock, &[(connection(1), RS256)]);
    let attacker_jwk = serde_json::to_value(&attacker.published).expect("a serializable JWK");
    let header = serde_json::json!({
        "alg": "RS256",
        "typ": "JWT",
        "kid": published.kid,
        "jku": format!("http://{elsewhere_address}/keys"),
        "x5u": format!("http://{elsewhere_address}/chain"),
        "x5c": ["Zm9yZ2Vk"],
        "jwk": attacker_jwk,
    });

    let denied = verifier
        .verify(
            &a_connection(ISSUER_ONE),
            &signed_under(
                &attacker,
                Algorithm::ES256,
                &header,
                &claims(ISSUER_ONE, SUBJECT),
            ),
        )
        .expect_err("key material the header carries verifies nothing");

    assert_eq!(denied.reason, DenialReason::InvalidCredential);
    assert!(
        arrived.recv_timeout(Duration::from_millis(750)).is_err(),
        "the verifier fetched a URL the token header named"
    );
}

// ================================================== 5. key selection and isolation

/// A `kid` published only by another issuer is never used for this issuer's proof.
#[test]
fn a_kid_published_only_by_another_issuer_is_never_used() {
    let elsewhere = keys(Algorithm::ES256, "shared-kid");
    let here = keys(Algorithm::ES256, "here-2026-09");
    let source = InMemoryJwks::new();
    source.publish(&Issuer::new(ISSUER_ONE), key_set(&[&here]));
    source.publish(&Issuer::new(ISSUER_TWO), key_set(&[&elsewhere]));
    let clock = FixedClock::at(NOW);
    let verifier = verifier(&source, &clock, &[(connection(1), ES256)]);

    let denied = verifier
        .verify(
            &a_connection(ISSUER_ONE),
            &mint(&elsewhere, &claims(ISSUER_ONE, SUBJECT)),
        )
        .expect_err("another issuer's key is not this issuer's key");

    assert_eq!(denied.reason, DenialReason::InvalidCredential);
    assert_eq!(verifier.refusals(), vec![RefusalReason::KeyIdUnknown]);
}

/// A published key that names a shared-secret algorithm verifies nothing.
#[test]
fn a_published_key_naming_a_shared_secret_algorithm_is_refused() {
    let rsa = keys(Algorithm::RS256, "one-2026-09");
    let source = InMemoryJwks::new();
    source.publish(
        &Issuer::new(ISSUER_ONE),
        published_with(&rsa, "alg", "HS256".into()),
    );
    let clock = FixedClock::at(NOW);
    let verifier = verifier(&source, &clock, &[(connection(1), RS256)]);

    let denied = verifier
        .verify(
            &a_connection(ISSUER_ONE),
            &mint(&rsa, &claims(ISSUER_ONE, SUBJECT)),
        )
        .expect_err("a key published for HS256 is not a key for RS256");

    assert_eq!(denied.reason, DenialReason::InvalidCredential);
    assert_eq!(
        verifier.refusals(),
        vec![RefusalReason::KeyAlgorithmMismatch]
    );
}

/// A published key whose type disagrees with the configured algorithm verifies nothing.
#[test]
fn a_published_key_whose_type_disagrees_with_the_algorithm_is_refused() {
    let elliptic = keys(Algorithm::ES256, "one-2026-09");
    let source = InMemoryJwks::new();
    // The `alg` is stripped, so nothing but the key type itself disagrees.
    source.publish(
        &Issuer::new(ISSUER_ONE),
        published_without(&elliptic, "alg"),
    );
    let clock = FixedClock::at(NOW);
    let verifier = verifier(&source, &clock, &[(connection(1), RS256)]);
    let rsa = keys(Algorithm::RS256, "one-2026-09");

    let denied = verifier
        .verify(
            &a_connection(ISSUER_ONE),
            &mint(&rsa, &claims(ISSUER_ONE, SUBJECT)),
        )
        .expect_err("an elliptic-curve key does not verify an RSA signature");

    assert_eq!(denied.reason, DenialReason::InvalidCredential);
}

/// Two published keys under one `kid` resolve the same way every time.
#[test]
fn two_published_keys_under_one_kid_resolve_the_same_way_every_time() {
    let first = keys(Algorithm::ES256, "duplicate");
    let second = keys(Algorithm::ES256, "duplicate");
    let source = InMemoryJwks::new();
    source.publish(&Issuer::new(ISSUER_ONE), key_set(&[&first, &second]));
    let clock = FixedClock::at(NOW);
    let verifier = verifier(&source, &clock, &[(connection(1), ES256)]);

    let by_first: Vec<bool> = (0..3)
        .map(|_| {
            verifier
                .verify(
                    &a_connection(ISSUER_ONE),
                    &mint(&first, &claims(ISSUER_ONE, SUBJECT)),
                )
                .is_ok()
        })
        .collect();
    let by_second: Vec<bool> = (0..3)
        .map(|_| {
            verifier
                .verify(
                    &a_connection(ISSUER_ONE),
                    &mint(&second, &claims(ISSUER_ONE, SUBJECT)),
                )
                .is_ok()
        })
        .collect();

    assert_eq!(by_first, vec![by_first[0]; 3], "one answer for one key");
    assert_eq!(by_second, vec![by_second[0]; 3], "one answer for one key");
    assert!(
        !(by_first[0] && by_second[0]),
        "two distinct keys under one kid cannot both be the published key"
    );
}

// ============================================================ 6. claim boundaries

/// An expiry exactly at the verification instant has passed, and a not-before exactly at
/// it has arrived.
#[test]
fn the_instant_of_expiry_is_out_and_the_instant_of_validity_is_in() {
    let rsa = keys(Algorithm::RS256, "one-2026-09");
    let source = InMemoryJwks::new();
    source.publish(&Issuer::new(ISSUER_ONE), key_set(&[&rsa]));
    let clock = FixedClock::at(NOW);
    let verifier = verifier(&source, &clock, &[(connection(1), RS256)]);

    let at_expiry = with(claims(ISSUER_ONE, SUBJECT), "exp", NOW.into());
    let denied = verifier
        .verify(&a_connection(ISSUER_ONE), &mint(&rsa, &at_expiry))
        .expect_err("`exp` is not a moment the token is still good for");
    assert_eq!(denied.reason, DenialReason::InvalidCredential);
    assert_eq!(verifier.refusals(), vec![RefusalReason::Expired]);

    let at_validity = with(claims(ISSUER_ONE, SUBJECT), "nbf", NOW.into());
    verifier
        .verify(&a_connection(ISSUER_ONE), &mint(&rsa, &at_validity))
        .expect("`nbf` has arrived at the instant it names");
}

/// An expiry that is not an unsigned integer is no expiry at all.
#[test]
fn an_expiry_that_is_not_an_unsigned_integer_is_refused() {
    let rsa = keys(Algorithm::RS256, "one-2026-09");
    let source = InMemoryJwks::new();
    source.publish(&Issuer::new(ISSUER_ONE), key_set(&[&rsa]));
    let clock = FixedClock::at(NOW);
    let verifier = verifier(&source, &clock, &[(connection(1), RS256)]);

    for expiry in [
        serde_json::json!(format!("{}", NOW + 300)),
        serde_json::json!(f64::from(2_000_000_000_u32)),
        serde_json::json!(-1),
        serde_json::json!(null),
        serde_json::json!({ "at": NOW + 300 }),
    ] {
        let denied = verifier
            .verify(
                &a_connection(ISSUER_ONE),
                &mint(
                    &rsa,
                    &with(claims(ISSUER_ONE, SUBJECT), "exp", expiry.clone()),
                ),
            )
            .expect_err("an expiry that cannot be read is not an expiry");
        assert_eq!(denied.reason, DenialReason::InvalidCredential, "{expiry}");
    }
}

/// An audience list naming a party the connection does not trust is refused.
#[test]
fn an_audience_list_naming_an_untrusted_party_is_refused() {
    let rsa = keys(Algorithm::RS256, "one-2026-09");
    let source = InMemoryJwks::new();
    source.publish(&Issuer::new(ISSUER_ONE), key_set(&[&rsa]));
    let clock = FixedClock::at(NOW);
    let verifier = verifier(&source, &clock, &[(connection(1), RS256)]);
    // OIDC Core 3.1.3.7 step 3: the token MUST be rejected if it "contains additional
    // audiences not trusted by the Client"; step 4 wants an `azp` whenever there are
    // several. This token carries neither trust nor an `azp`.
    let several = with(
        claims(ISSUER_ONE, SUBJECT),
        "aud",
        serde_json::json!([CLIENT, "another-relying-party"]),
    );

    let outcome = verifier.verify(&a_connection(ISSUER_ONE), &mint(&rsa, &several));

    assert!(
        outcome.is_err(),
        "a token also addressed to another relying party was admitted with no `azp` \
         naming this one"
    );
}

/// An empty audience list names nobody, this connection's client included.
#[test]
fn an_empty_audience_list_is_refused() {
    let rsa = keys(Algorithm::RS256, "one-2026-09");
    let source = InMemoryJwks::new();
    source.publish(&Issuer::new(ISSUER_ONE), key_set(&[&rsa]));
    let clock = FixedClock::at(NOW);
    let verifier = verifier(&source, &clock, &[(connection(1), RS256)]);

    for audience in [
        serde_json::json!([]),
        serde_json::json!(null),
        serde_json::json!([[CLIENT]]),
        serde_json::json!({ "aud": CLIENT }),
    ] {
        let denied = verifier
            .verify(
                &a_connection(ISSUER_ONE),
                &mint(
                    &rsa,
                    &with(claims(ISSUER_ONE, SUBJECT), "aud", audience.clone()),
                ),
            )
            .expect_err("no audience value is the configured client");
        assert_eq!(denied.reason, DenialReason::AudienceMismatch, "{audience}");
    }
}

/// An issuer that differs from the connection's by case or a trailing slash is another
/// issuer.
#[test]
fn an_issuer_differing_by_case_or_a_trailing_slash_is_refused() {
    let rsa = keys(Algorithm::RS256, "one-2026-09");
    let source = InMemoryJwks::new();
    source.publish(&Issuer::new(ISSUER_ONE), key_set(&[&rsa]));
    let clock = FixedClock::at(NOW);
    let verifier = verifier(&source, &clock, &[(connection(1), RS256)]);

    for named in [
        "https://idp.example/one/",
        "https://IDP.example/one",
        "https://idp.example/ONE",
        "https://idp.example/one/../one",
    ] {
        let denied = verifier
            .verify(
                &a_connection(ISSUER_ONE),
                &mint(&rsa, &claims(named, SUBJECT)),
            )
            .expect_err("the issuer is compared to the connection's, exactly");
        assert_eq!(denied.clause, DenialClause::IssuerMismatch, "{named}");
    }
}

/// A subject that is empty, blank or not a string never becomes a key component.
#[test]
fn a_subject_that_is_empty_blank_or_not_a_string_never_becomes_a_key() {
    let rsa = keys(Algorithm::RS256, "one-2026-09");
    let source = InMemoryJwks::new();
    source.publish(&Issuer::new(ISSUER_ONE), key_set(&[&rsa]));
    let clock = FixedClock::at(NOW);
    let verifier = verifier(&source, &clock, &[(connection(1), RS256)]);
    let log = vec![
        created(
            connection(1),
            organization(10),
            ISSUER_ONE,
            unconditional(organization(10)),
        ),
        linked(connection(1), organization(10), SUBJECT, principal(0x21)),
    ];
    let projection = Projection::fold(&log).expect("one connection, one link");

    for subject in [
        serde_json::json!(""),
        serde_json::json!("   "),
        serde_json::json!("\t\n"),
        serde_json::json!(" subject-one "),
        serde_json::json!(42),
        serde_json::json!(null),
    ] {
        let proof = mint(
            &rsa,
            &with(claims(ISSUER_ONE, SUBJECT), "sub", subject.clone()),
        );
        let denied = authenticate(&projection, connection(1), &verifier, proof)
            .expect_err("a subject that is not the issuer's subject resolves nothing");
        assert_eq!(
            denied.reason,
            DenialReason::InvalidCredential,
            "{subject} resolved to a key component"
        );
    }
}

// ================================================================ 7. fail closed

/// No input this file can build makes the verifier panic or return an empty proof.
#[test]
fn nothing_malformed_panics_or_verifies() {
    let rsa = keys(Algorithm::RS256, "one-2026-09");
    let source = InMemoryJwks::new();
    source.publish(&Issuer::new(ISSUER_ONE), key_set(&[&rsa]));
    let clock = FixedClock::at(NOW);
    let verifier = verifier(&source, &clock, &[(connection(1), RS256)]);
    let header = serde_json::json!({ "alg": "RS256", "typ": "JWT", "kid": rsa.kid });

    let mut malformed: Vec<(String, CredentialProof)> = vec![
        ("empty".to_owned(), CredentialProof::from_bytes(Vec::new())),
        (
            "two dots".to_owned(),
            CredentialProof::from_bytes(b"..".to_vec()),
        ),
        (
            "four segments".to_owned(),
            CredentialProof::from_bytes(b"a.b.c.d".to_vec()),
        ),
        (
            "not utf-8".to_owned(),
            CredentialProof::from_bytes(vec![0xff, 0xfe, 0x2e, 0x00, 0x2e]),
        ),
        (
            "header not base64url".to_owned(),
            CredentialProof::from_bytes(b"!!!!.e30.c2ln".to_vec()),
        ),
        (
            "header padded".to_owned(),
            CredentialProof::from_bytes(format!("{}==.e30.c2ln", base64url(b"{}")).into_bytes()),
        ),
        (
            "header is a list".to_owned(),
            CredentialProof::from_bytes(
                format!("{}.e30.c2ln", base64url(b"[\"RS256\"]")).into_bytes(),
            ),
        ),
        (
            "alg is a number".to_owned(),
            CredentialProof::from_bytes(
                format!("{}.e30.c2ln", base64url(br#"{"alg":256}"#)).into_bytes(),
            ),
        ),
        (
            "empty payload".to_owned(),
            CredentialProof::from_bytes(
                format!("{}..c2ln", base64url(header.to_string().as_bytes())).into_bytes(),
            ),
        ),
        (
            "payload is a list".to_owned(),
            minted_under(&rsa, &header, &serde_json::json!([1, 2, 3])),
        ),
        (
            "payload is a string".to_owned(),
            minted_under(&rsa, &header, &serde_json::json!("claims")),
        ),
        (
            "claims are deeply nested".to_owned(),
            minted_under(&rsa, &header, &nested(400)),
        ),
        (
            "a very long kid".to_owned(),
            minted_under(
                &rsa,
                &serde_json::json!({ "alg": "RS256", "kid": "k".repeat(200_000) }),
                &claims(ISSUER_ONE, SUBJECT),
            ),
        ),
        (
            "a very long subject".to_owned(),
            mint(
                &rsa,
                &with(
                    claims(ISSUER_ONE, SUBJECT),
                    "sub",
                    "s".repeat(1_000_000).into(),
                ),
            ),
        ),
        (
            "an expiry at the end of time".to_owned(),
            mint(
                &rsa,
                &with(claims(ISSUER_ONE, SUBJECT), "exp", u64::MAX.into()),
            ),
        ),
        (
            "a not-before at the end of time".to_owned(),
            mint(
                &rsa,
                &with(claims(ISSUER_ONE, SUBJECT), "nbf", u64::MAX.into()),
            ),
        ),
    ];
    malformed.push((
        "a signature that is not base64url".to_owned(),
        CredentialProof::from_bytes(
            format!(
                "{}.{}.!!!",
                base64url(header.to_string().as_bytes()),
                base64url(claims(ISSUER_ONE, SUBJECT).to_string().as_bytes())
            )
            .into_bytes(),
        ),
    ));

    for (name, proof) in malformed {
        let outcome = std::panic::catch_unwind(AssertUnwindSafe(|| {
            verifier.verify(&a_connection(ISSUER_ONE), &proof)
        }));
        match outcome {
            Err(_) => panic!("`{name}` panicked the verifier"),
            // The value is summarized rather than printed: one of these inputs is a
            // megabyte long, and a megabyte of assertion output buries every other
            // result in the run.
            Ok(Ok(verified)) => panic!(
                "`{name}` verified: a subject of {} bytes beginning {:?}",
                verified.subject().as_str().len(),
                verified
                    .subject()
                    .as_str()
                    .chars()
                    .take(24)
                    .collect::<String>()
            ),
            Ok(Err(denied)) => assert_ne!(
                denied.reason,
                DenialReason::Denied,
                "`{name}` denied without naming an invalid credential"
            ),
        }
    }
}

fn nested(depth: usize) -> serde_json::Value {
    let mut value = serde_json::json!(1);
    for _ in 0..depth {
        value = serde_json::Value::Array(vec![value]);
    }
    serde_json::json!({ "iss": ISSUER_ONE, "sub": SUBJECT, "aud": CLIENT, "exp": NOW + 300, "deep": value })
}

/// An access token of the type RFC 9068 declares is refused, whatever else it carries.
#[test]
fn an_rfc_9068_access_token_type_is_refused() {
    let rsa = keys(Algorithm::RS256, "one-2026-09");
    let source = InMemoryJwks::new();
    source.publish(&Issuer::new(ISSUER_ONE), key_set(&[&rsa]));
    let clock = FixedClock::at(NOW);
    let verifier = verifier(&source, &clock, &[(connection(1), RS256)]);
    let header = serde_json::json!({ "alg": "RS256", "typ": "at+jwt", "kid": rsa.kid });

    let denied = verifier
        .verify(
            &a_connection(ISSUER_ONE),
            &minted_under(&rsa, &header, &claims(ISSUER_ONE, SUBJECT)),
        )
        .expect_err("the verifier admits one token type");

    assert_eq!(
        verifier.refusals(),
        vec![RefusalReason::UnexpectedTokenType],
        "recorded so that the deployment can see why every login failed"
    );
    assert_eq!(denied.clause, DenialClause::ProofInvalid);
}
