//! The denial clauses of `mandate.federation` that `contracts/obligations/federation.json`
//! carried unbound, each driven to exactly the clause it names.
//!
//! `story:obligation-registry` split every implemented command's declared `condition.cause`
//! into its clauses and bound the ones an existing case already decided. Twenty were left
//! `blocked_on: story:obligations-federation`, which is this file. Sixteen are decided here:
//! thirteen refuse through the handler the crate ships, with no stand-in deciding anything,
//! and the three of `mandate.federation.RegisterOAuthClient` are decided by the
//! `ClientRegistrationAdmission` implementation they are passed, which is why the document
//! publishes those three on the `double` path (*Where a double decides*, below). Every case
//! asserts both halves of the refusal: the contract's `mandate.core.DenialReason` and the
//! crate-local [`DenialClause`] that says *which* declared condition fired. Asserting the
//! reason alone would let a clause be satisfied by any refusal of the command.
//!
//! # Why the verifier here is the real one
//!
//! `story:signing-and-verification` shipped [`RealVerifier`], so the proof-driven cases mint
//! a real token with a key generated in this process and verify it through the same code a
//! deployment runs. [`mandate_federation::verifier::ConstructedVerifier`] admits or refuses
//! by construction: a proof clause it "decided" would be evidence about the double and not
//! about the shipped path, which is exactly what `contracts/obligations/README.md` counts in
//! its own column. [`InMemoryJwks`] publishes the key set and [`FixedClock`] dates the
//! request; neither decides a refusal — they supply what the verifier reads, and a key set
//! and a clock are the deployment's input in production too.
//!
//! Every key is generated by `aws_lc_rs` when the case runs, under ES256: no private key is
//! read from the repository and nothing here opens a socket.
//!
//! # Where a double decides
//!
//! The three `mandate.federation.RegisterOAuthClient` cases are the exception, and
//! `contracts/obligations/federation.json` publishes them as one: each row is
//! `path: "double"`, `double: "mandate_federation::register_client::ConfiguredAdmission"`,
//! and each clause carries `blocked_on: "decision-blocker:guards"`.
//!
//! `register_client.rs:93` declares a port, not a decision. The handler compares nothing: it
//! asks `ClientRegistrationAdmission` the three questions the declared denial names and turns
//! a `false` into the refusal, so what refuses is the implementation it was handed. The only
//! implementation in this workspace is [`ConfiguredAdmission`], which `register_client.rs:181`
//! calls "a fixture, never a shipped implementation" and which
//! `crates/mandate-conformance/src/external.rs:248` registers as this port's standing double,
//! beside `mandate_graph::double::GraphDouble` and `mandate_policy::double::PolicyDouble`
//! whose clauses are published the same way. By `contracts/obligations/README.md` that is a
//! `double` row: it is counted in `double_only`, it never covers, and it carries a
//! `blocked_on` naming what owns the port's shipped implementation rather than this file —
//! the shipped client-administration adapter is what `decision-blocker:guards` owns.
//!
//! The three cases stay, because a double row is evidence of exactly what it says: the
//! handler reaches the port for each of the three conditions and reports the
//! [`DenialClause`] the port's answer selects, which is what binds the clause to a condition
//! rather than to "the command refused".
//!
//! # What is not here
//!
//! Nine clauses of this crate's commands stay deferred, and none of them for want of a case.
//! Four name an administration authority the handler deciding them takes no admission port
//! for at all, which is `story:federation-admission-port`; `register_client.rs:93` is where
//! that port exists, and it decides nothing itself — the answer is the implementation's, and
//! today the only one is the fixture [`ConfiguredAdmission`] (above). The durable-commit and
//! invalidation clauses name the adapter's transaction. Two more — "STS code
//! issuance/narrowing is refused" and "disablement cannot stop the issuance of new
//! authorization codes to it" — are decided by `mandate-sts` code no case in this crate
//! reaches, which is `story:cross-crate-clauses`. `contracts/obligations/federation.json`
//! records which story or blocker owns each of those paths.

use aws_lc_rs::rand::SystemRandom;
use aws_lc_rs::signature::{ECDSA_P256_SHA256_FIXED_SIGNING, EcdsaKeyPair};
use jsonwebtoken::jwk::Jwk;
use jsonwebtoken::{Algorithm, EncodingKey, Header, encode};

use mandate_federation::authenticate::{ProvisionExternalPrincipal, provision_external_principal};
use mandate_federation::disable::{
    DisableFederationConnection, DisableOAuthClient, UnlinkExternalPrincipal,
    disable_federation_connection, disable_oauth_client, unlink_external_principal,
};
use mandate_federation::link::{LinkExternalPrincipal, link_external_principal};
use mandate_federation::record::{
    ConnectionRegistered, FederationEvent, Projection, RegisterFederationConnection,
    register_federation_connection,
};
use mandate_federation::register_client::{
    ConfiguredAdmission, RegisterOAuthClient, register_o_auth_client,
};
use mandate_federation::verifier_real::{
    AllowedAlgorithms, FixedClock, InMemoryJwks, RealVerifier,
};
use mandate_federation::{
    DenialClause, Denied, PrincipalState, RecordedPrincipals, RequestContext, SequentialAllocator,
};
use mandate_model::TenantResolutionRule;
use mandate_types::value::Uuid;
use mandate_types::{
    Audience, ClientId, CorrelationId, CredentialId, CredentialProof, DenialReason,
    ExternalLinkMethod, ExternalPrincipalId, ExternalSubject, FederationConnectionId, Issuer,
    OAuthClientId, OrganizationId, PkceMethod, PrincipalId, RedirectUri, SigningAlgorithm,
    Timestamp, VerifiedContext,
};

const ISSUER_ONE: &str = "https://idp.example/one";
const ISSUER_TWO: &str = "https://idp.example/two";
const CLIENT: &str = "configured-client";
const SUBJECT: &str = "subject-one";
const ES256: &str = "ES256";
const REGISTERED: &str = "https://app.example/callback";

/// The instant every case is dated from, as seconds since the Unix epoch.
const NOW: u64 = 1_758_240_000;

// ------------------------------------------------------------------ identities

fn uuid(tag: u8) -> Uuid {
    Uuid::from_bytes([tag; 16])
}

fn organization(tag: u8) -> OrganizationId {
    OrganizationId::new(uuid(tag))
}

fn connection(tag: u8) -> FederationConnectionId {
    FederationConnectionId::new(uuid(tag))
}

fn principal(tag: u8) -> PrincipalId {
    PrincipalId::new(uuid(tag))
}

fn external_principal(tag: u8) -> ExternalPrincipalId {
    ExternalPrincipalId::new(uuid(tag))
}

/// The caller the client-registration admission holds authority for.
fn administrator() -> PrincipalId {
    principal(0x51)
}

fn redirect(text: &str) -> RedirectUri {
    RedirectUri::new(text)
}

fn context(organization_id: OrganizationId) -> VerifiedContext {
    VerifiedContext {
        subject: administrator(),
        actor: None,
        organization: organization_id,
        audience: Audience::new("mandate"),
        credential: CredentialId::new(uuid(0xcd)),
        delegation: None,
        execution: None,
        correlation: CorrelationId::new("obligations-federation"),
    }
}

fn at() -> Timestamp {
    Timestamp::new("2026-09-18T00:00:00Z")
}

fn request() -> RequestContext {
    RequestContext {
        audience: Audience::new("mandate"),
        correlation: CorrelationId::new("obligations-federation"),
        credential: CredentialId::new(uuid(0xcd)),
        at: at(),
    }
}

// ---------------------------------------------------------------- the records

fn unconditional(organization_id: OrganizationId) -> TenantResolutionRule {
    TenantResolutionRule {
        configured_organization: organization_id,
        verified_claim_name: None,
        verified_claim_value: None,
    }
}

fn on_claim(organization_id: OrganizationId, name: &str, value: &str) -> TenantResolutionRule {
    TenantResolutionRule {
        configured_organization: organization_id,
        verified_claim_name: Some(name.to_owned()),
        verified_claim_value: Some(value.to_owned()),
    }
}

/// A registration of `ISSUER_ONE` for `organization_id`, keyed on one claim, as
/// `mandate.federation.RegisterFederationConnection` declares it.
fn registration(
    organization_id: OrganizationId,
    name: &str,
    value: &str,
) -> RegisterFederationConnection {
    RegisterFederationConnection {
        context: context(organization_id),
        issuer: Issuer::new(ISSUER_ONE),
        client_id: ClientId::new(CLIENT),
        tenant_resolution: on_claim(organization_id, name, value),
        jit_provisioning: true,
    }
}

/// Register one connection through the shipped writer, refusing to proceed on a denial:
/// an arrangement this command does not accept is not a state a deployment can reach.
fn register(
    organization_id: OrganizationId,
    name: &str,
    value: &str,
    held: &Projection,
    allocator: &mut SequentialAllocator,
) -> ConnectionRegistered {
    register_federation_connection(&registration(organization_id, name, value), held, allocator)
        .expect("the shipped writer admits this registration")
}

fn created(
    connection_id: FederationConnectionId,
    organization_id: OrganizationId,
    issuer: &str,
    tenant_resolution: TenantResolutionRule,
    jit_provisioning: bool,
) -> FederationEvent {
    FederationEvent::FederationConnectionCreated {
        context: context(organization_id),
        connection_id,
        issuer: Issuer::new(issuer),
        client_id: ClientId::new(CLIENT),
        tenant_resolution,
        jit_provisioning,
    }
}

fn linked(
    connection_id: FederationConnectionId,
    organization_id: OrganizationId,
    subject: &str,
    principal_id: PrincipalId,
) -> FederationEvent {
    FederationEvent::ExternalPrincipalLinked {
        context: context(organization_id),
        connection_id,
        principal_id,
        external_principal_id: external_principal(0x71),
        subject: ExternalSubject::new(subject),
        link_method: ExternalLinkMethod::Administrator,
        linked_at: at(),
    }
}

fn disabled(
    connection_id: FederationConnectionId,
    organization_id: OrganizationId,
) -> FederationEvent {
    FederationEvent::FederationConnectionDisabled {
        context: context(organization_id),
        id: connection_id,
    }
}

/// One enabled connection of organization 10 on `ISSUER_ONE`, admitting provisioning.
fn one_connection() -> Projection {
    Projection::fold(&[created(
        connection(1),
        organization(10),
        ISSUER_ONE,
        unconditional(organization(10)),
        true,
    )])
    .expect("one connection")
}

// ---------------------------------------------------------------- key material

/// A generated key pair, the public JWK that publishes it, and the `kid` it is published
/// under. Nothing is read from the repository: the key is generated when the case runs.
struct Keys {
    signing: EncodingKey,
    published: Jwk,
    kid: String,
}

/// A fresh P-256 key pair published under `kid`.
fn keys(kid: &str) -> Keys {
    let pkcs8 =
        EcdsaKeyPair::generate_pkcs8(&ECDSA_P256_SHA256_FIXED_SIGNING, &SystemRandom::new())
            .expect("a generated elliptic-curve key");
    let signing = EncodingKey::from_ec_der(pkcs8.as_ref());
    let mut published = Jwk::from_encoding_key(&signing, Algorithm::ES256).expect("a public JWK");
    published.common.key_id = Some(kid.to_owned());
    Keys {
        signing,
        published,
        kid: kid.to_owned(),
    }
}

fn key_set(published: &[&Keys]) -> serde_json::Value {
    serde_json::json!({
        "keys": published
            .iter()
            .map(|keys| serde_json::to_value(&keys.published).expect("a serializable JWK"))
            .collect::<Vec<_>>(),
    })
}

fn claims(issuer: &str, subject: &str) -> serde_json::Value {
    serde_json::json!({
        "iss": issuer,
        "sub": subject,
        "aud": CLIENT,
        "iat": NOW,
        "exp": NOW + 300,
    })
}

fn with(mut claims: serde_json::Value, name: &str, value: serde_json::Value) -> serde_json::Value {
    claims
        .as_object_mut()
        .expect("a claims object")
        .insert(name.to_owned(), value);
    claims
}

fn mint(keys: &Keys, claims: &serde_json::Value) -> CredentialProof {
    let mut header = Header::new(Algorithm::ES256);
    header.kid = Some(keys.kid.clone());
    let token = encode(&header, claims, &keys.signing).expect("a signed token");
    CredentialProof::from_bytes(token.into_bytes())
}

/// The real verifier over a published key set, a fixed clock and the connections whose
/// algorithm the deployment configured.
fn verifier(
    source: &InMemoryJwks,
    clock: &FixedClock,
    configured: &[FederationConnectionId],
) -> RealVerifier<InMemoryJwks, FixedClock> {
    let allowed = AllowedAlgorithms::configured(&[SigningAlgorithm::new(ES256)])
        .expect("a non-empty allowlist is admitted");
    let mut built = RealVerifier::new(allowed, source.clone(), clock.clone());
    for connection_id in configured {
        built = built
            .configure_connection(*connection_id, &SigningAlgorithm::new(ES256))
            .expect("an admitted algorithm for this connection");
    }
    built
}

/// One published issuer, its verifier, and the key that signs for it.
fn published() -> (Keys, RealVerifier<InMemoryJwks, FixedClock>) {
    let signing = keys("2026-09");
    let source = InMemoryJwks::new();
    source.publish(&Issuer::new(ISSUER_ONE), key_set(&[&signing]));
    let verifier = verifier(&source, &FixedClock::at(NOW), &[connection(1)]);
    (signing, verifier)
}

/// `ProvisionExternalPrincipal` against the real handler.
fn provision(
    projection: &Projection,
    connection_id: FederationConnectionId,
    verifier: &RealVerifier<InMemoryJwks, FixedClock>,
    proof: CredentialProof,
) -> Denied {
    let mut allocator = SequentialAllocator::new();
    provision_external_principal(
        &ProvisionExternalPrincipal {
            connection_id,
            proof,
        },
        &request(),
        verifier,
        projection,
        projection,
        &mut allocator,
    )
    .expect_err("this case is a refusal")
}

// ==================================================================================
// mandate.federation.DisableFederationConnection
// ==================================================================================

/// "connection is outside the verified organization": the binding is the record's own, and
/// a caller verified in another organization does not acquire it by naming the connection.
#[test]
fn a_connection_outside_the_verified_organization_is_refused_at_disable() {
    let held = one_connection();

    let denied = disable_federation_connection(
        &DisableFederationConnection {
            context: context(organization(11)),
            id: connection(1),
        },
        &held,
    )
    .expect_err("the connection belongs to organization 10");

    assert_eq!(denied.reason, DenialReason::TenantMismatch);
    assert_eq!(denied.clause, DenialClause::OrganizationMismatch);
}

// ==================================================================================
// mandate.federation.DisableOAuthClient
// ==================================================================================

/// A client registered by the real handler, and the fold that holds it.
fn a_registered_client(organization_id: OrganizationId) -> (Projection, OAuthClientId) {
    let admission = ConfiguredAdmission::new()
        .with_administrator(administrator())
        .with_organization(organization_id)
        .with_redirect_uri(organization_id, redirect(REGISTERED));
    let mut allocator = SequentialAllocator::new();
    let registered = register_o_auth_client(
        &RegisterOAuthClient {
            context: context(organization_id),
            public: true,
            redirect_uris: vec![redirect(REGISTERED)],
            pkce_method: PkceMethod::S256,
        },
        &admission,
        &mut allocator,
    )
    .expect("the admission holds the caller, the organization and the redirect");

    (
        Projection::fold(&[registered.event]).expect("one registration"),
        registered.id,
    )
}

/// "the client is outside the verified organization".
#[test]
fn a_client_outside_the_verified_organization_is_refused_at_disable() {
    let (held, client_id) = a_registered_client(organization(10));

    let denied = disable_oauth_client(
        &DisableOAuthClient {
            context: context(organization(11)),
            id: client_id,
        },
        &held,
    )
    .expect_err("the client belongs to organization 10");

    assert_eq!(denied.reason, DenialReason::TenantMismatch);
    assert_eq!(denied.clause, DenialClause::OrganizationMismatch);
}

// ==================================================================================
// mandate.federation.UnlinkExternalPrincipal
// ==================================================================================

/// "link is outside the verified organization".
#[test]
fn a_link_outside_the_verified_organization_is_refused_at_unlink() {
    let held = one_connection();
    let links = RecordedPrincipals::over(held.clone()).with_principal(
        principal(0x21),
        organization(10),
        PrincipalState::Active,
    );
    let mut allocator = SequentialAllocator::new();
    let link = link_external_principal(
        &LinkExternalPrincipal {
            context: context(organization(10)),
            connection_id: connection(1),
            external_subject: ExternalSubject::new(SUBJECT),
            principal_id: principal(0x21),
            method: ExternalLinkMethod::Administrator,
        },
        &request(),
        &held,
        &links,
        &mut allocator,
    )
    .expect("the link is recorded first");
    let held = Projection::fold(&[
        created(
            connection(1),
            organization(10),
            ISSUER_ONE,
            unconditional(organization(10)),
            true,
        ),
        link.event,
    ])
    .expect("a connection and a link");

    let denied = unlink_external_principal(
        &UnlinkExternalPrincipal {
            context: context(organization(11)),
            id: link.external_principal_id,
        },
        &held,
    )
    .expect_err("the link belongs to organization 10");

    assert_eq!(denied.reason, DenialReason::TenantMismatch);
    assert_eq!(denied.clause, DenialClause::OrganizationMismatch);
}

// ==================================================================================
// mandate.federation.RegisterOAuthClient
//
// The three refusals below are `ClientRegistrationAdmission`'s answers and not this
// crate's: `contracts/obligations/federation.json` publishes them on the `double` path,
// blocked on `decision-blocker:guards`. See *Where a double decides*, above.
// ==================================================================================

/// The registration this organization's admission would accept from its administrator.
fn a_registration(organization_id: OrganizationId) -> RegisterOAuthClient {
    RegisterOAuthClient {
        context: context(organization_id),
        public: true,
        redirect_uris: vec![redirect(REGISTERED)],
        pkce_method: PkceMethod::S256,
    }
}

/// "Caller lacks client-administration authority": the admission holds the organization and
/// the redirect, and does not hold this caller.
#[test]
fn a_caller_the_admission_does_not_hold_as_a_client_administrator_is_refused() {
    let admission = ConfiguredAdmission::new()
        .with_organization(organization(10))
        .with_redirect_uri(organization(10), redirect(REGISTERED));
    let mut allocator = SequentialAllocator::new();

    let denied = register_o_auth_client(
        &a_registration(organization(10)),
        &admission,
        &mut allocator,
    )
    .expect_err("no caller holds client-administration authority here");

    assert_eq!(denied.reason, DenialReason::Denied);
    assert_eq!(denied.clause, DenialClause::ClientAdministrationAuthority);
}

/// "organization binding is invalid": the organization is the verified context's own, and
/// this deployment admits no client registration into it.
#[test]
fn an_organization_no_client_may_be_registered_into_is_refused() {
    let admission = ConfiguredAdmission::new()
        .with_administrator(administrator())
        .with_redirect_uri(organization(10), redirect(REGISTERED));
    let mut allocator = SequentialAllocator::new();

    let denied = register_o_auth_client(
        &a_registration(organization(10)),
        &admission,
        &mut allocator,
    )
    .expect_err("no organization is admitted here");

    assert_eq!(denied.reason, DenialReason::TenantMismatch);
    assert_eq!(denied.clause, DenialClause::OrganizationMismatch);
}

/// "a redirect URI is unadmitted", each of them: a set that is admitted except for one
/// entry is refused rather than registered without it.
#[test]
fn a_redirect_uri_the_deployment_does_not_admit_is_refused() {
    let admission = ConfiguredAdmission::new()
        .with_administrator(administrator())
        .with_organization(organization(10))
        .with_redirect_uri(organization(10), redirect(REGISTERED));
    let mut allocator = SequentialAllocator::new();
    let input = RegisterOAuthClient {
        redirect_uris: vec![redirect(REGISTERED), redirect("https://app.example/other")],
        ..a_registration(organization(10))
    };

    let denied = register_o_auth_client(&input, &admission, &mut allocator)
        .expect_err("the second redirect is not admitted");

    assert_eq!(denied.reason, DenialReason::Denied);
    assert_eq!(denied.clause, DenialClause::RedirectUriUnadmitted);
}

// ==================================================================================
// mandate.federation.ProvisionExternalPrincipal
// ==================================================================================

/// "Connection is disabled/untrusted": the disabled half. A disabled connection selects no
/// trust relationship, so no first login is provisioned through it.
#[test]
fn a_disabled_connection_is_refused_at_provisioning() {
    let (signing, verifier) = published();
    let held = Projection::fold(&[
        created(
            connection(1),
            organization(10),
            ISSUER_ONE,
            unconditional(organization(10)),
            true,
        ),
        disabled(connection(1), organization(10)),
    ])
    .expect("a connection and its disable");

    let denied = provision(
        &held,
        connection(1),
        &verifier,
        mint(&signing, &claims(ISSUER_ONE, SUBJECT)),
    );

    assert_eq!(denied.reason, DenialReason::Denied);
    assert_eq!(denied.clause, DenialClause::ConnectionDisabled);
}

/// "Connection is disabled/untrusted": the untrusted half. A connection no event created is
/// no configured trust relationship.
#[test]
fn an_unresolved_connection_is_refused_at_provisioning() {
    let (signing, verifier) = published();

    let denied = provision(
        &one_connection(),
        connection(2),
        &verifier,
        mint(&signing, &claims(ISSUER_ONE, SUBJECT)),
    );

    assert_eq!(denied.reason, DenialReason::Denied);
    assert_eq!(denied.clause, DenialClause::ConnectionUnknown);
}

/// "proof signature/issuer/audience/expiry is invalid": the signature half, refused by the
/// real verifier against the key set the issuer actually published.
#[test]
fn a_proof_signed_by_a_key_the_issuer_never_published_is_refused_at_provisioning() {
    let (_, verifier) = published();
    let attacker = keys("2026-09");

    let denied = provision(
        &one_connection(),
        connection(1),
        &verifier,
        mint(&attacker, &claims(ISSUER_ONE, SUBJECT)),
    );

    assert_eq!(denied.reason, DenialReason::InvalidCredential);
    assert_eq!(denied.clause, DenialClause::ProofInvalid);
}

/// "proof signature/issuer/audience/expiry is invalid": the expiry half.
#[test]
fn a_proof_whose_expiry_has_passed_is_refused_at_provisioning() {
    let signing = keys("2026-09");
    let source = InMemoryJwks::new();
    source.publish(&Issuer::new(ISSUER_ONE), key_set(&[&signing]));
    // The token is minted inside its window and presented after it: the clock the request
    // is served under is past the `exp` the issuer signed.
    let verifier = verifier(&source, &FixedClock::at(NOW + 600), &[connection(1)]);

    let denied = provision(
        &one_connection(),
        connection(1),
        &verifier,
        mint(&signing, &claims(ISSUER_ONE, SUBJECT)),
    );

    assert_eq!(denied.reason, DenialReason::InvalidCredential);
    assert_eq!(denied.clause, DenialClause::ProofInvalid);
}

/// "proof signature/issuer/audience/expiry is invalid": the issuer half. The issuer is the
/// connection's configured one and never the token's own claim.
#[test]
fn a_proof_whose_issuer_is_not_the_connections_is_refused_at_provisioning() {
    let (signing, verifier) = published();

    let denied = provision(
        &one_connection(),
        connection(1),
        &verifier,
        mint(&signing, &claims(ISSUER_TWO, SUBJECT)),
    );

    assert_eq!(denied.reason, DenialReason::InvalidCredential);
    assert_eq!(denied.clause, DenialClause::IssuerMismatch);
}

/// "proof signature/issuer/audience/expiry is invalid": the audience half. A token minted
/// for another client is not this connection's proof.
#[test]
fn a_proof_whose_audience_is_not_the_configured_client_is_refused_at_provisioning() {
    let (signing, verifier) = published();

    let denied = provision(
        &one_connection(),
        connection(1),
        &verifier,
        mint(
            &signing,
            &with(claims(ISSUER_ONE, SUBJECT), "aud", "another-client".into()),
        ),
    );

    assert_eq!(denied.reason, DenialReason::AudienceMismatch);
    assert_eq!(denied.clause, DenialClause::AudienceBinding);
}

/// "tenant resolution has zero or multiple matches": zero. No organization is guessed for a
/// validated proof the configured rule does not match.
#[test]
fn a_proof_matching_no_configured_tenant_is_refused_at_provisioning() {
    let (signing, verifier) = published();
    let held = Projection::fold(&[created(
        connection(1),
        organization(10),
        ISSUER_ONE,
        on_claim(organization(10), "org", "acme"),
        true,
    )])
    .expect("one connection");

    let denied = provision(
        &held,
        connection(1),
        &verifier,
        mint(
            &signing,
            &with(claims(ISSUER_ONE, SUBJECT), "org", "another".into()),
        ),
    );

    assert_eq!(denied.reason, DenialReason::TenantMismatch);
    assert_eq!(denied.clause, DenialClause::TenantZero);
}

/// "tenant resolution has zero or multiple matches": multiple. Two configured tenants stand
/// behind one issuer and the proof matches both, so the first login resolves neither.
///
/// The writer refuses a second organization's rule a proof could satisfy alongside a held
/// one, so no single registration against a current fold reaches this pair. Two routes
/// still do, and the fold does not re-decide the guard on either. A replayed history: an
/// event log written before the guard refused different-claim rules folds through
/// `Projection::apply` as it was accepted (`Deployment::record_federation` in
/// `services/control-plane` is that raw fold; its
/// `serve.rs::two_connections_on_one_issuer_from_a_log_are_still_refused_as_ambiguous` holds
/// the pair that way). And the race the guard's own comment names: the guard is
/// read-then-write, so two registrations that each read the issuer before the other's event
/// is folded are both admitted. This case takes the second route, so both connections come
/// out of `register_federation_connection` rather than being folded by hand. Each
/// organization keys on the claim it uses — `{org: acme}` and `{dept: eng}` — and one proof
/// carrying both claims matches both rules.
#[test]
fn a_proof_matching_two_configured_tenants_is_refused_at_provisioning() {
    let mut allocator = SequentialAllocator::new();
    let unheld = Projection::default();
    let incumbent = register(organization(10), "org", "acme", &unheld, &mut allocator);
    let second = register(organization(11), "dept", "eng", &unheld, &mut allocator);
    let held =
        Projection::fold(&[incumbent.event, second.event]).expect("two connections on one issuer");
    let signing = keys("2026-09");
    let source = InMemoryJwks::new();
    source.publish(&Issuer::new(ISSUER_ONE), key_set(&[&signing]));
    let verifier = verifier(
        &source,
        &FixedClock::at(NOW),
        &[incumbent.connection_id, second.connection_id],
    );

    let denied = provision(
        &held,
        incumbent.connection_id,
        &verifier,
        mint(
            &signing,
            &with(
                with(claims(ISSUER_ONE, SUBJECT), "org", "acme".into()),
                "dept",
                "eng".into(),
            ),
        ),
    );

    assert_eq!(denied.reason, DenialReason::TenantMismatch);
    assert_eq!(denied.clause, DenialClause::TenantAmbiguous);
}

/// "the composite (organization, configured issuer, subject) key already exists": the first
/// login already happened, and provisioning creates nothing on top of it.
#[test]
fn a_subject_already_holding_the_composite_key_is_refused_at_provisioning() {
    let (signing, verifier) = published();
    let held = Projection::fold(&[
        created(
            connection(1),
            organization(10),
            ISSUER_ONE,
            unconditional(organization(10)),
            true,
        ),
        linked(connection(1), organization(10), SUBJECT, principal(0x21)),
    ])
    .expect("a connection and a link");

    let denied = provision(
        &held,
        connection(1),
        &verifier,
        mint(&signing, &claims(ISSUER_ONE, SUBJECT)),
    );

    assert_eq!(denied.reason, DenialReason::Denied);
    assert_eq!(denied.clause, DenialClause::ExternalKeyExists);
}

/// "any email-domain/unverified-input fallback would be required": the issuer signed the
/// address and did not assert it had verified it, so the rule that would have matched on it
/// refuses the request rather than resolving one.
#[test]
fn an_unverified_claim_a_tenant_rule_would_have_matched_is_refused_at_provisioning() {
    let (signing, verifier) = published();
    let held = Projection::fold(&[created(
        connection(1),
        organization(10),
        ISSUER_ONE,
        on_claim(organization(10), "email", "person@acme.example"),
        true,
    )])
    .expect("one connection");

    let denied = provision(
        &held,
        connection(1),
        &verifier,
        mint(
            &signing,
            &with(
                claims(ISSUER_ONE, SUBJECT),
                "email",
                "person@acme.example".into(),
            ),
        ),
    );

    assert_eq!(denied.reason, DenialReason::TenantMismatch);
    assert_eq!(
        denied.clause,
        DenialClause::UnverifiedFallback,
        "an address without `email_verified` is not a validated claim"
    );
}
