//! Validation of emitted events against the closed contract.
//!
//! Three checks, each reading one generated projection and nothing else:
//!
//! - [`check_event_conforms`] reads `generated/schema/events/<name>.schema.json` and
//!   validates a payload against it with a Draft 2020-12 validator, format assertions
//!   on. The schemas are self-contained — local `$defs`, `additionalProperties: false`,
//!   a `required` list — so nothing is retrieved over the network or off disk beyond
//!   the one file.
//! - [`check_single_emission`] reads `generated/ir/system.json`: an accepted outcome
//!   emits exactly the one event it declares, an error outcome emits nothing.
//! - [`check_payload_sources`] reads the same file: every field of the emitted payload
//!   is compared against the source the contract declares for it.
//!
//! Every check returns the whole list of what failed, not the first failure, so one run
//! says everything it can about the payload in front of it, and names the whole of what
//! the caller supplied before it says what is undeclared. The `assert_` forms panic with
//! that same message. Every message carries a repository-relative path; no absolute path
//! appears in any of them.
//!
//! [`declaring_outcome_in`] is the one seam: it reads an IR value the caller hands it,
//! so a case can decide the harness against an IR the generated file does not contain.
//!
//! Both files are generated by `ess generate` and are the contract, not a copy of it: a
//! failure here means the runtime and the specification disagree, and the specification
//! is the one that is right.

use std::collections::BTreeSet;
use std::sync::OnceLock;

use jsonschema::Draft;
use serde_json::Value;

/// The generated event payload schemas, one file per event.
const EVENT_SCHEMAS: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../generated/schema/events");

/// The generated system IR: commands, outcomes, emissions and payload sources.
const SYSTEM_IR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../generated/ir/system.json"
);

/// How the IR is named in a message, so a failure points at a repository path.
const IR_NAME: &str = "generated/ir/system.json";

/// Validate an emitted event payload against its generated schema.
///
/// Reads `generated/schema/events/<ess_name>.schema.json` and validates `payload`
/// against it as Draft 2020-12 with format assertions enabled, so `pattern`, `format`,
/// `enum`, `const`, `type` and `required` are all decided, and `additionalProperties:
/// false` closes the shape.
///
/// # Errors
///
/// Returns the event name followed by every validation failure — each one an instance
/// location and the validator's own message — when the payload does not conform, or
/// when the schema file cannot be read, parsed or compiled. An `ess_name` the contract
/// does not declare is refused as undeclared before any path is built from it, so a
/// name is never reported as a missing file and never reaches the filesystem. A failure
/// means the payload is not the one the contract declares: an obsolete field, a missing
/// required field, a `null` where the contract spells absence by leaving the field out,
/// or a value outside the declared lexical form.
pub fn check_event_conforms(ess_name: &str, payload: &Value) -> Result<(), String> {
    declared_event(ess_name)?;
    let schema_name = format!("generated/schema/events/{ess_name}.schema.json");
    let text = std::fs::read_to_string(format!("{EVENT_SCHEMAS}/{ess_name}.schema.json"))
        .map_err(|error| format!("{ess_name}: {schema_name}: {error}"))?;
    let schema: Value = serde_json::from_str(&text)
        .map_err(|error| format!("{ess_name}: {schema_name}: {error}"))?;
    let validator = jsonschema::options()
        .with_draft(Draft::Draft202012)
        .should_validate_formats(true)
        .build(&schema)
        .map_err(|error| format!("{ess_name}: {schema_name}: {error}"))?;
    let failures: Vec<String> = validator
        .iter_errors(payload)
        .map(|failure| {
            let location = failure.instance_path().to_string();
            let location = if location.is_empty() {
                "/".to_owned()
            } else {
                location
            };
            format!("{location}: {failure}")
        })
        .collect();
    if failures.is_empty() {
        Ok(())
    } else {
        Err(format!("{ess_name}: {}", failures.join("; ")))
    }
}

/// Panicking form of [`check_event_conforms`].
///
/// # Panics
///
/// Panics with the message [`check_event_conforms`] returns.
pub fn assert_event_conforms(ess_name: &str, payload: &Value) {
    if let Err(message) = check_event_conforms(ess_name, payload) {
        panic!("{message}");
    }
}

/// Check what an outcome emitted against what the contract declares it emits.
///
/// Reads `generated/ir/system.json`. An accepted outcome declares exactly one event and
/// must have emitted exactly that one; an error outcome declares none and must have
/// emitted none. `emitted` carries the event names and their payloads in emission
/// order; only the names and the count are decided here, the payloads are for
/// [`check_event_conforms`].
///
/// # Errors
///
/// Returns a message naming the command and the outcome when the command or the outcome
/// is not declared, when an accepted outcome emitted the wrong event or the wrong number
/// of them, or when an error outcome emitted anything at all. A failure means the
/// implementation emits a different set of events than the contract says it does.
pub fn check_single_emission(
    command: &str,
    outcome: &str,
    emitted: &[(&str, &Value)],
) -> Result<(), String> {
    let node = outcome_node(command, outcome)
        .map_err(|reason| format!("{command}/{outcome}: {reason}"))?;
    let declared = names(node.get("emits"));
    let actual: Vec<&str> = emitted.iter().map(|(name, _)| *name).collect();
    if node.get("error").is_some() {
        if !declared.is_empty() {
            return Err(format!(
                "{command}/{outcome}: {IR_NAME} declares an error outcome that emits {}",
                listed(&declared)
            ));
        }
        if actual.is_empty() {
            return Ok(());
        }
        return Err(format!(
            "{command}/{outcome}: a denied outcome emits nothing, but {} emitted: {}",
            counted(actual.len()),
            listed(&actual)
        ));
    }
    let [single] = declared.as_slice() else {
        return Err(format!(
            "{command}/{outcome}: an accepted outcome emits exactly one event, but {IR_NAME} declares {}: {}",
            declared.len(),
            listed(&declared)
        ));
    };
    match actual.as_slice() {
        [one] if one == single => Ok(()),
        [one] => Err(format!(
            "{command}/{outcome}: the contract declares `{single}`, but `{one}` was emitted"
        )),
        other => Err(format!(
            "{command}/{outcome}: the contract declares exactly one emission, `{single}`, but {} emitted: {}",
            counted(other.len()),
            listed(other)
        )),
    }
}

/// Panicking form of [`check_single_emission`].
///
/// # Panics
///
/// Panics with the message [`check_single_emission`] returns.
pub fn assert_single_emission(command: &str, outcome: &str, emitted: &[(&str, &Value)]) {
    if let Err(message) = check_single_emission(command, outcome, emitted) {
        panic!("{message}");
    }
}

/// Check an emitted payload against the sources the contract declares for it.
///
/// Reads the payload mapping keyed on the triple (command, outcome, event) in
/// `generated/ir/system.json` — the outcome is resolved from `command` and `event_name`
/// and an event two outcomes both declare is refused rather than decided by whichever
/// outcome the IR happens to list first — and decides every mapped field by its
/// declared source: `input_field` is compared by value against the named field of
/// `input`, `response_field` against the named field of `response`, `literal` against
/// the value the contract names, and `generated` is checked for presence only, its
/// value being produced at runtime.
///
/// Absence is decided at the level the mapping compares — the mapped field itself —
/// and nowhere deeper: a `null` standing for a whole mapped field is read as an absent
/// value on either side, while a `null` nested inside a mapped object is part of the
/// value this check compares and is left to [`check_event_conforms`], which refuses it
/// because the contract declares no nullable type.
///
/// Whether an absent source is a failure is the contract's decision, read off the
/// field's `target_type`: a target the IR declares `optional` may be absent when its
/// source is, which is how the contract's four optional-to-optional mappings pass
/// (`parent` on `ResourceRegistered`, `not_before` and `execution_binding` on
/// `DelegationCreated`, `descriptor` on `CredentialIntrospected` — the one optional
/// `response_field`). Every other target must be carried whatever the caller supplied,
/// because the schema declares it required and an absent source cannot excuse it. An
/// absent source with a carried target is a failure either way. The event's key set is
/// closed the same way its schema closes it: a key with no declared source is refused.
///
/// # Errors
///
/// Returns a message naming what the caller supplied — the command, the outcome once it
/// is resolved, and the event — followed by every field that failed: a mapped field
/// absent from the event, a value that disagrees with its source, an event key the
/// contract declares no source for, a response-sourced field with no `response`
/// supplied, or a source kind this harness does not check. A failure means the event
/// carries something the command was not given and the contract did not declare.
pub fn check_payload_sources(
    command: &str,
    input: &Value,
    response: Option<&Value>,
    event_name: &str,
    event: &Value,
) -> Result<(), String> {
    let outcome = declaring_outcome(command, event_name)?;
    let fields = payload_fields(command, &outcome, event_name)
        .map_err(|reason| format!("{command}/{outcome}/{event_name}: {reason}"))?;
    let mut failures: Vec<String> = Vec::new();
    for field in fields {
        let target = field
            .get("target")
            .and_then(Value::as_str)
            .unwrap_or("<unnamed>");
        let source = field.get("value").unwrap_or(&Value::Null);
        let kind = source.get("kind").and_then(Value::as_str).unwrap_or("");
        let optional = field
            .get("target_type")
            .and_then(|declared| declared.get("kind"))
            .and_then(Value::as_str)
            == Some("optional");
        let actual = carried(event, target);
        match kind {
            "input_field" => {
                let named = source
                    .get("field")
                    .and_then(Value::as_str)
                    .unwrap_or("<unnamed>");
                let origin = format!("the input field `{named}`");
                match carried(input, named) {
                    Some(expected) => compare(&mut failures, target, &origin, expected, actual),
                    None => absent(&mut failures, target, &origin, optional, actual),
                }
            }
            "response_field" => {
                let named = source
                    .get("field")
                    .and_then(Value::as_str)
                    .unwrap_or("<unnamed>");
                let origin = format!("the response field `{named}`");
                match response {
                    None => failures.push(format!(
                        "field `{target}`: sourced from {origin}, but no response was supplied"
                    )),
                    Some(response) => match carried(response, named) {
                        Some(expected) => {
                            compare(&mut failures, target, &origin, expected, actual);
                        }
                        None => absent(&mut failures, target, &origin, optional, actual),
                    },
                }
            }
            "literal" => compare(
                &mut failures,
                target,
                "the declared literal",
                source.get("value").unwrap_or(&Value::Null),
                actual,
            ),
            "generated" => {
                if actual.is_none() {
                    failures.push(format!(
                        "field `{target}`: generated at runtime, but the event carries no such field"
                    ));
                }
            }
            other => failures.push(format!(
                "field `{target}`: {IR_NAME} declares the source kind `{other}`, which this harness does not check"
            )),
        }
    }
    undeclared_keys(&mut failures, fields, event);
    if failures.is_empty() {
        Ok(())
    } else {
        Err(format!(
            "{command}/{outcome}/{event_name}: {}",
            failures.join("; ")
        ))
    }
}

/// Panicking form of [`check_payload_sources`].
///
/// # Panics
///
/// Panics with the message [`check_payload_sources`] returns.
pub fn assert_payload_sources(
    command: &str,
    input: &Value,
    response: Option<&Value>,
    event_name: &str,
    event: &Value,
) {
    if let Err(message) = check_payload_sources(command, input, response, event_name, event) {
        panic!("{message}");
    }
}

/// The generated IR, read once and parsed once for the whole process.
fn system_ir() -> Result<&'static Value, String> {
    static IR: OnceLock<Result<Value, String>> = OnceLock::new();
    IR.get_or_init(|| {
        let text =
            std::fs::read_to_string(SYSTEM_IR).map_err(|error| format!("{IR_NAME}: {error}"))?;
        serde_json::from_str(&text).map_err(|error| format!("{IR_NAME}: {error}"))
    })
    .as_ref()
    .map_err(Clone::clone)
}

/// The IR node for a declared command.
///
/// The failure is the reason alone: what the caller supplied is named by the public
/// function, which knows all of it, so that every refusal reads back the whole of what
/// it was asked about and not only the part that was looked up first.
fn command_node(command: &str) -> Result<&'static Value, String> {
    system_ir()?
        .get("commands")
        .and_then(|commands| commands.get(command))
        .ok_or_else(|| format!("{IR_NAME} declares no such command"))
}

/// The IR node for one named outcome of a declared command.
fn outcome_node(command: &str, outcome: &str) -> Result<&'static Value, String> {
    command_node(command)?
        .get("outcomes")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .find(|candidate| candidate.get("name").and_then(Value::as_str) == Some(outcome))
        .ok_or_else(|| format!("{IR_NAME} declares no outcome `{outcome}` for this command"))
}

/// The one outcome of `command` whose payload declares `event`, read out of the IR
/// value supplied rather than out of the generated file.
///
/// This is the seam [`check_payload_sources`] resolves its outcome through, exposed so
/// that a case can hand it an IR the generated one does not contain: a payload mapping
/// is keyed on the triple (command, outcome, event), and an event two outcomes of one
/// command both declare is ambiguous. Today's `generated/ir/system.json` declares every
/// mapping on a distinct event, so the ambiguous case cannot be built from it, and a
/// resolver that silently took the first match would read the same on every mapping the
/// contract has.
///
/// # Errors
///
/// Returns a message naming the command and the event supplied when `ir` declares no
/// such command, no payload for that event on it, or more than one outcome declaring
/// it — the last naming every outcome that does.
pub fn declaring_outcome_in(ir: &Value, command: &str, event: &str) -> Result<String, String> {
    let Some(node) = ir
        .get("commands")
        .and_then(|commands| commands.get(command))
    else {
        return Err(format!(
            "{command}/{event}: {IR_NAME} declares no such command"
        ));
    };
    let declaring: Vec<&str> = node
        .get("outcomes")
        .and_then(Value::as_array)
        .map_or(&[][..], Vec::as_slice)
        .iter()
        .filter(|outcome| {
            outcome
                .get("payload")
                .and_then(Value::as_array)
                .into_iter()
                .flatten()
                .any(|entry| entry.get("event").and_then(Value::as_str) == Some(event))
        })
        .map(|outcome| {
            outcome
                .get("name")
                .and_then(Value::as_str)
                .unwrap_or("<unnamed>")
        })
        .collect();
    match declaring.as_slice() {
        [single] => Ok((*single).to_owned()),
        [] => Err(format!(
            "{command}/{event}: {IR_NAME} declares no payload for event `{event}` on this command"
        )),
        many => Err(format!(
            "{command}/{event}: {IR_NAME} declares a payload for event `{event}` on {} outcomes ({}), so the outcome decides the mapping",
            many.len(),
            many.join(", ")
        )),
    }
}

/// The one outcome of `command` whose payload declares `event_name` in the generated IR.
fn declaring_outcome(command: &str, event_name: &str) -> Result<String, String> {
    declaring_outcome_in(system_ir()?, command, event_name)
}

/// The declared payload field mapping of one event under one outcome of a command.
fn payload_fields(
    command: &str,
    outcome: &str,
    event_name: &str,
) -> Result<&'static Vec<Value>, String> {
    outcome_node(command, outcome)?
        .get("payload")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .find(|entry| entry.get("event").and_then(Value::as_str) == Some(event_name))
        .and_then(|entry| entry.get("fields").and_then(Value::as_array))
        .ok_or_else(|| {
            format!("{IR_NAME} declares no payload for event `{event_name}` on this outcome")
        })
}

/// Whether the contract declares an event under this name.
///
/// The name is looked up in the IR's own event list, which is a map lookup and not a
/// path: a name that is not declared is refused before any path is built from it, so
/// nothing a caller supplies reaches the filesystem.
fn declared_event(ess_name: &str) -> Result<(), String> {
    if system_ir()?
        .get("events")
        .and_then(|events| events.get(ess_name))
        .is_some()
    {
        Ok(())
    } else {
        Err(format!("{ess_name}: {IR_NAME} declares no such event"))
    }
}

/// The string list under a key, or an empty list when the key is absent.
fn names(node: Option<&Value>) -> Vec<&str> {
    node.and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .collect()
}

/// Event names as a message reads them, or `(none)` when there are none.
fn listed(items: &[&str]) -> String {
    if items.is_empty() {
        "(none)".to_owned()
    } else {
        items.join(", ")
    }
}

/// `1 event was` or `n events were`, so a message reads as a sentence.
fn counted(count: usize) -> String {
    if count == 1 {
        "1 event was".to_owned()
    } else {
        format!("{count} events were")
    }
}

/// The value an object carries under a key, reading `null` as absence.
///
/// The contract declares no nullable type: an optional field is a `$ref` to a
/// non-nullable type left out of `required`, so absence is spelled by omission and
/// `null` is a form the contract does not declare. Both sides are read this way, so a
/// `null` is never mistaken for a value that was supplied or generated.
fn carried<'a>(object: &'a Value, key: &str) -> Option<&'a Value> {
    match object.get(key) {
        None | Some(&Value::Null) => None,
        Some(value) => Some(value),
    }
}

/// Compare one mapped field of the event against its declared source.
fn compare(
    failures: &mut Vec<String>,
    target: &str,
    source: &str,
    expected: &Value,
    actual: Option<&Value>,
) {
    match actual {
        None => failures.push(format!(
            "field `{target}`: {source} is {expected}, but the event carries no such field"
        )),
        Some(actual) if actual == expected => {}
        Some(actual) => failures.push(format!(
            "field `{target}`: {source} is {expected}, the event carries {actual}"
        )),
    }
}

/// Decide one mapped field whose declared source carries no value.
///
/// Which way this goes is the contract's decision and not the caller's: an absent
/// source and an absent target agree only where the IR declares the target `optional`,
/// which is the contract's four optional-to-optional mappings and nothing else. For
/// every other target the schema declares the field required, so an absent source
/// cannot excuse an event that omits it — that payload would be refused by
/// [`check_event_conforms`], and a source check that passed it would disagree with the
/// contract. An absent source with a value in the event is a failure either way: the
/// event carries something the command was not given.
fn absent(
    failures: &mut Vec<String>,
    target: &str,
    source: &str,
    optional: bool,
    actual: Option<&Value>,
) {
    match actual {
        Some(actual) => failures.push(format!(
            "field `{target}`: {source} carries no value, but the event carries {actual}"
        )),
        None if !optional => failures.push(format!(
            "field `{target}`: {source} carries no value and the event carries no such field, but {IR_NAME} declares `{target}` required"
        )),
        None => {}
    }
}

/// Refuse every event key the contract declares no source for.
///
/// The declared targets are the whole of what an emitted payload may carry, so this is
/// a key-set comparison and not a per-field one: a key with no mapping is a field the
/// command was never given, whatever its value.
fn undeclared_keys(failures: &mut Vec<String>, fields: &[Value], event: &Value) {
    let Some(object) = event.as_object() else {
        failures.push(format!("the event is not a JSON object, but {event}"));
        return;
    };
    let declared: BTreeSet<&str> = fields
        .iter()
        .filter_map(|field| field.get("target").and_then(Value::as_str))
        .collect();
    let undeclared: Vec<String> = object
        .keys()
        .filter(|key| !declared.contains(key.as_str()))
        .map(|key| format!("`{key}`"))
        .collect();
    if !undeclared.is_empty() {
        failures.push(format!(
            "the event carries {} the contract declares no source for: {}",
            if undeclared.len() == 1 {
                "a key"
            } else {
                "keys"
            },
            undeclared.join(", ")
        ));
    }
}
