//! The emitter's cases, decided against the committed IR and doctored copies of it.
//!
//! Every case reads `generated/ir/system.json` — the same bytes `cargo xtask generate` reads —
//! so what is proved here is proved about the emission the gate byte-compares. The doctored
//! cases copy that model and change one declaration, which is the only way to reach a refusal
//! the contract does not currently provoke.
#[allow(dead_code)] // the binary target uses the whole module; a case here uses part of it.
#[path = "../src/emit.rs"]
mod emit;

use serde_json::Value;
use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    path::{Path, PathBuf},
};

fn repo() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("workspace root")
        .to_owned()
}

/// The committed model: the emitter's only input.
fn model() -> Vec<u8> {
    fs::read(repo().join("generated/ir/system.json")).expect("the committed IR")
}

fn rendered() -> BTreeMap<String, String> {
    emit::render(&model()).expect("the committed IR emits")
}

/// Every declaration a file introduces, by Rust name.
///
/// Only a line that starts a declaration at column zero counts, so the `Declared` visitor
/// nested inside `Presence`'s `Deserialize` impl is not one of them — it is indented and
/// private, and neither is true of an emitted declaration.
fn declarations(body: &str) -> Vec<String> {
    body.lines()
        .filter_map(|line| {
            line.strip_prefix("pub struct ")
                .or_else(|| line.strip_prefix("pub enum "))
        })
        .map(|rest| {
            rest.split(|c: char| !c.is_ascii_alphanumeric() && c != '_')
                .next()
                .unwrap_or_default()
                .to_owned()
        })
        .collect()
}

/// The names the IR declares for one kind, projected through the naming rule.
fn names(model: &Value, kind: &str, suffix: &str) -> BTreeSet<String> {
    model[kind]
        .as_object()
        .expect("an IR index")
        .keys()
        .map(|name| format!("{}{suffix}", emit::declaration_name(name)))
        .collect()
}

#[test]
fn a_declaration_name_is_every_part_of_the_dotted_path_capitalised() {
    for (source, expected) in [
        (
            "mandate.federation.FederationAuthenticated",
            "MandateFederationFederationAuthenticated",
        ),
        (
            "mandate.federation.AuthenticateFederation",
            "MandateFederationAuthenticateFederation",
        ),
        (
            "mandate.federation.FederationConnection",
            "MandateFederationFederationConnection",
        ),
        (
            "mandate.federation.FederationConnection.State",
            "MandateFederationFederationConnectionState",
        ),
        ("mandate.audit.Denied", "MandateAuditDenied"),
    ] {
        assert_eq!(emit::declaration_name(source), expected);
    }
}

#[test]
fn two_emissions_of_one_model_are_byte_identical() {
    let model = model();
    let first = emit::render(&model).expect("first emission");
    let second = emit::render(&model).expect("second emission");
    assert_eq!(first, second);
}

#[test]
fn the_four_files_are_emitted_and_each_starts_with_the_digest_of_the_model_it_read() {
    let files = rendered();
    assert_eq!(
        files.keys().collect::<Vec<_>>(),
        ["commands.rs", "entities.rs", "events.rs", "types.rs"]
            .iter()
            .collect::<Vec<_>>()
    );
    let digest = emit::digest(&model());
    let header = format!(
        "// Generated by cargo xtask generate from ir/system.json (sha256 {digest}) \
         with ess 0.26.0. Do not edit.\n"
    );
    for (name, body) in &files {
        assert!(body.starts_with(&header), "{name} has no header line");
    }
}

#[test]
fn a_changed_model_changes_the_digest_every_file_carries() {
    let mut model: Value = serde_json::from_slice(&model()).expect("the committed IR parses");
    model["summary"] = Value::String("doctored".to_owned());
    let doctored = serde_json::to_vec(&model).expect("serialize");
    let before = emit::digest(&self::model());
    let after = emit::digest(&doctored);
    assert_ne!(before, after);
    for body in emit::render(&doctored).expect("emission").values() {
        assert!(body.contains(&after));
        assert!(!body.contains(&before));
    }
}

/// Every element of the four emitted kinds is declared once, and nothing else is.
///
/// The expectation is the IR's own index, not a number: a set equality states both halves —
/// no element is missing and no declaration is invented — and stays true as the contract grows.
/// The counts are asserted beside it as the figure this wave measured.
#[test]
fn every_element_the_model_declares_is_emitted_exactly_once() {
    let files = rendered();
    let model: Value = serde_json::from_slice(&model()).expect("the committed IR parses");

    let states = model["entities"]
        .as_object()
        .expect("entities")
        .values()
        .map(|entity| emit::declaration_name(entity["state_type"].as_str().expect("a state type")))
        .collect::<BTreeSet<_>>();

    for (file, expected) in [
        (
            "types.rs",
            names(&model, "types", "")
                .difference(&states)
                .cloned()
                .chain(["Presence".to_owned()])
                .collect::<BTreeSet<_>>(),
        ),
        (
            "entities.rs",
            names(&model, "entities", "")
                .union(&states)
                .cloned()
                .collect(),
        ),
        ("events.rs", names(&model, "events", "")),
        (
            "commands.rs",
            names(&model, "commands", "Input")
                .union(&names(&model, "errors", ""))
                .cloned()
                .chain(
                    model["commands"]
                        .as_object()
                        .expect("commands")
                        .iter()
                        .filter(|(_, command)| command.get("response").is_some())
                        .map(|(name, _)| format!("{}Response", emit::declaration_name(name))),
                )
                .collect(),
        ),
    ] {
        let emitted = declarations(&files[file]);
        let once = emitted.iter().cloned().collect::<BTreeSet<_>>();
        assert_eq!(once.len(), emitted.len(), "{file} declares a name twice");
        assert_eq!(
            once, expected,
            "{file} does not declare what the IR carries"
        );
    }

    // The figures this wave measured, so a silently shrinking emission is a failure here too.
    assert_eq!(declarations(&files["events.rs"]).len(), 74);
    assert_eq!(declarations(&files["entities.rs"]).len(), 72); // 36 entities and 36 state enums
    assert_eq!(declarations(&files["commands.rs"]).len(), 98); // 61 inputs, 26 responses, 11 errors
    assert_eq!(declarations(&files["types.rs"]).len(), 75); // 110 types less 36 states, and Presence
}

/// A response is emitted for the command that declares one, and only for it.
///
/// 35 of the 61 commands carry no `response` key at all. An emitter that answered them with an
/// empty record would be inventing a declaration the contract does not make, and every reader
/// of the crate would then take the silence for a shape.
#[test]
fn only_a_command_that_declares_a_response_is_given_one() {
    let files = rendered();
    let model: Value = serde_json::from_slice(&model()).expect("the committed IR parses");
    let commands = model["commands"].as_object().expect("commands");
    let declared = commands
        .values()
        .filter(|command| command.get("response").is_some())
        .count();
    assert_eq!(declared, 26);
    assert_eq!(
        declarations(&files["commands.rs"])
            .iter()
            .filter(|name| name.ends_with("Response"))
            .count(),
        declared
    );
    assert!(files["commands.rs"].contains("pub struct MandateAuditRecordAuditEventResponse {"));
    assert!(!files["commands.rs"].contains("MandateAuditRedactAuditEventResponse"));
}

#[test]
fn an_event_that_reaches_credential_material_is_refused_by_name() {
    for secret in [
        "mandate.core.CredentialSecret",
        "mandate.core.CredentialProof",
    ] {
        let mut model: Value = serde_json::from_slice(&model()).expect("the committed IR parses");
        model["events"]["mandate.identity.SessionRevoked"]["fields"]
            .as_array_mut()
            .expect("event fields")
            .push(serde_json::json!({
                "name": "secret",
                "type_ref": {"kind": "declared", "name": secret},
                "naming": {}
            }));
        let refusal = emit::render(&serde_json::to_vec(&model).expect("serialize"))
            .expect_err("an event carrying credential material is refused")
            .to_string();
        assert!(
            refusal.contains("mandate.identity.SessionRevoked"),
            "{refusal}"
        );
        assert!(refusal.contains(secret), "{refusal}");
        assert!(refusal.contains("secret"), "{refusal}");
    }
}

/// The refusal follows the reference graph, not just the field's own type.
///
/// A declaration reaches credential material through any chain of declared types, and the one
/// that matters is the indirect one: a field typed `VerifiedContext` looks harmless at the
/// event and carries the secret two hops down.
#[test]
fn an_entity_that_reaches_credential_material_indirectly_is_refused_with_the_path() {
    let mut model: Value = serde_json::from_slice(&model()).expect("the committed IR parses");
    model["types"]["mandate.core.VerifiedContext"]["body"]["fields"]
        .as_array_mut()
        .expect("struct fields")
        .push(serde_json::json!({
            "name": "proof",
            "type_ref": {"kind": "declared", "name": "mandate.core.CredentialProof"},
            "naming": {}
        }));
    model["entities"]["mandate.identity.Principal"]["fields"]
        .as_array_mut()
        .expect("entity fields")
        .push(serde_json::json!({
            "name": "opened_with",
            "type_ref": {"kind": "declared", "name": "mandate.core.VerifiedContext"},
            "naming": {}
        }));
    let refusal = emit::render(&serde_json::to_vec(&model).expect("serialize"))
        .expect_err("an entity reaching credential material is refused")
        .to_string();
    assert!(refusal.contains("mandate.identity.Principal"), "{refusal}");
    assert!(
        refusal.contains("mandate.core.VerifiedContext -> mandate.core.CredentialProof"),
        "{refusal}"
    );
}

/// A command input may carry credential material, and seven of them do.
///
/// The refusal is about the record: an event is the durable one and an entity is the projected
/// one, and neither may hold a secret. A command input is the message that carries the
/// credential to be verified, so refusing it would refuse the contract as declared.
#[test]
fn a_command_input_may_carry_credential_material() {
    let files = rendered();
    assert!(files["commands.rs"].contains("MandateCoreCredentialSecret"));
    assert!(files["commands.rs"].contains("MandateCoreCredentialProof"));
    assert!(!files["events.rs"].contains("MandateCoreCredentialSecret"));
    assert!(!files["events.rs"].contains("MandateCoreCredentialProof"));
    assert!(!files["entities.rs"].contains("MandateCoreCredentialSecret"));
    assert!(!files["entities.rs"].contains("MandateCoreCredentialProof"));
}

/// A primitive the mapping does not name is a refusal, not a guess.
///
/// The story's mapping table names six primitives and the model uses seven — `boolean` is in
/// the contract and not in the table. That gap was closed by measuring the model rather than
/// reading the table, and this case closes the class it belongs to: the next primitive ESS
/// admits stops the gate instead of reaching a reader as some plausible Rust type.
#[test]
fn a_primitive_the_mapping_does_not_name_is_refused() {
    assert!(rendered()["entities.rs"].contains("pub jit_provisioning: bool,"));
    let mut model: Value = serde_json::from_slice(&model()).expect("the committed IR parses");
    model["events"]["mandate.identity.SessionRevoked"]["fields"]
        .as_array_mut()
        .expect("event fields")
        .push(serde_json::json!({
            "name": "rate",
            "type_ref": {"kind": "primitive", "name": "decimal"},
            "naming": {}
        }));
    let refusal = emit::render(&serde_json::to_vec(&model).expect("serialize"))
        .expect_err("an unmapped primitive is refused")
        .to_string();
    assert!(refusal.contains("decimal"), "{refusal}");
}

/// A name Rust cannot take is a refusal, not broken source.
///
/// Every field name and enum variant in the model is a plain Rust identifier today. An
/// emitter that assumed it would stay that way would answer a renamed declaration with a file
/// that does not parse, and the failure would be reported against the crate rather than
/// against the declaration that caused it.
#[test]
fn a_name_rust_cannot_take_is_refused() {
    for (name, needle) in [
        ("type", "type"),
        ("session-id", "session-id"),
        // Reserved, not strict: `rustc --edition 2024` answers "expected identifier, found
        // reserved keyword" for each of these exactly as it does for a strict one.
        ("try", "try"),
        ("gen", "gen"),
        ("become", "become"),
        ("priv", "priv"),
        // The four that cannot even be raw identifiers, so escaping is not an answer.
        ("self", "self"),
        ("Self", "Self"),
        ("crate", "crate"),
        ("super", "super"),
    ] {
        let mut model: Value = serde_json::from_slice(&model()).expect("the committed IR parses");
        model["events"]["mandate.identity.SessionRevoked"]["fields"]
            .as_array_mut()
            .expect("event fields")
            .push(serde_json::json!({
                "name": name,
                "type_ref": {"kind": "declared", "name": "mandate.core.SessionId"},
                "naming": {}
            }));
        let refusal = emit::render(&serde_json::to_vec(&model).expect("serialize"))
            .expect_err("a name Rust cannot take is refused")
            .to_string();
        assert!(refusal.contains(needle), "{refusal}");
        assert!(
            refusal.contains("mandate.identity.SessionRevoked"),
            "{refusal}"
        );
    }
}

const EVENT: &str = r#"/// `mandate.identity.SessionRevoked` — event payload.
#[derive(Clone, Debug, PartialEq, ::serde::Deserialize, ::serde::Serialize)]
#[serde(deny_unknown_fields)]
pub struct MandateIdentitySessionRevoked {
    pub context: super::types::MandateCoreVerifiedContext,
    pub id: super::types::MandateCoreSessionId,
}
"#;

const INPUT: &str = r#"/// `mandate.audit.RecordAuditEvent` — command input.
#[derive(Clone, Debug, PartialEq, ::serde::Deserialize, ::serde::Serialize)]
#[serde(deny_unknown_fields)]
pub struct MandateAuditRecordAuditEventInput {
    pub emitter_context: super::types::MandateCoreVerifiedContext,
    pub record: super::types::MandateCoreAuditRecord,
}
"#;

const ENTITY: &str = r#"/// `mandate.identity.Principal` — entity record.
#[derive(Clone, Debug, PartialEq, ::serde::Deserialize, ::serde::Serialize)]
#[serde(deny_unknown_fields)]
pub struct MandateIdentityPrincipal {
    pub id: super::types::MandateCorePrincipalId,
    pub kind: super::types::MandateCorePrincipalKind,
    pub display_name: String,
    pub state: MandateIdentityPrincipalState,
}

/// `mandate.identity.Principal.State` — enum.
#[derive(Clone, Debug, PartialEq, ::serde::Deserialize, ::serde::Serialize)]
pub enum MandateIdentityPrincipalState {
    #[serde(rename = "Active")]
    Active,
    #[serde(rename = "Disabled")]
    Disabled,
}
"#;

const ERROR: &str = r#"/// `mandate.audit.Denied` — refusal payload.
#[derive(Clone, Debug, PartialEq, ::serde::Deserialize, ::serde::Serialize)]
#[serde(deny_unknown_fields)]
pub struct MandateAuditDenied {
    pub reason: super::types::MandateCoreDenialReason,
}
"#;

const OPTIONAL: &str = r#"/// `mandate.core.VerifiedContext` — struct.
#[derive(Clone, Debug, PartialEq, ::serde::Deserialize, ::serde::Serialize)]
#[serde(deny_unknown_fields)]
pub struct MandateCoreVerifiedContext {
    pub subject: MandateCorePrincipalId,
    #[serde(default, skip_serializing_if = "Presence::is_absent")]
    pub actor: Presence<MandateCorePrincipalId>,
    pub organization: MandateCoreOrganizationId,
    pub audience: MandateCoreAudience,
    pub credential: MandateCoreCredentialId,
    #[serde(default, skip_serializing_if = "Presence::is_absent")]
    pub delegation: Presence<MandateCoreDelegationId>,
    #[serde(default, skip_serializing_if = "Presence::is_absent")]
    pub execution: Presence<MandateCoreExecutionId>,
    pub correlation: MandateCoreCorrelationId,
}
"#;

const UNION: &str = r#"/// `mandate.core.SecurityEpochTarget` — union.
#[derive(Clone, Debug, PartialEq, ::serde::Deserialize, ::serde::Serialize)]
#[serde(tag = "kind", content = "value", deny_unknown_fields)]
pub enum MandateCoreSecurityEpochTarget {
    #[serde(rename = "federation")]
    Federation(MandateCoreFederationConnectionId),
    #[serde(rename = "organization")]
    Organization(MandateCoreOrganizationId),
    #[serde(rename = "principal")]
    Principal(MandateCorePrincipalId),
}
"#;

const NEWTYPE: &str = r#"/// `mandate.core.CredentialSecret` — newtype over `bytes`.
#[derive(Clone, Debug, PartialEq, ::serde::Deserialize, ::serde::Serialize)]
#[serde(transparent)]
pub struct MandateCoreCredentialSecret(pub String);
"#;

const LIST: &str = r#"/// `mandate.core.AuthorityScope` — struct.
#[derive(Clone, Debug, PartialEq, ::serde::Deserialize, ::serde::Serialize)]
#[serde(deny_unknown_fields)]
pub struct MandateCoreAuthorityScope {
    pub actions: Vec<MandateCoreAction>,
    pub resources: Vec<MandateCoreResourceRef>,
    #[serde(default, skip_serializing_if = "Presence::is_absent")]
    pub space: Presence<MandateCoreSpaceId>,
}
"#;

const PRIMITIVES: &str = r#"/// `mandate.identity.SecurityEpochRecorded` — event payload.
#[derive(Clone, Debug, PartialEq, ::serde::Deserialize, ::serde::Serialize)]
#[serde(deny_unknown_fields)]
pub struct MandateIdentitySecurityEpochRecorded {
    pub target: super::types::MandateCoreSecurityEpochTarget,
    pub generation: ::serde_json::Number,
}
"#;

/// The emitted text of one declaration per kind, verbatim.
///
/// A golden is what keeps the mapping table in the story honest: a change to any of `optional`,
/// `list`, the primitives, the naming rule, the derive set or the serde attributes shows up
/// here as a diff rather than as a silently different wire shape.
#[test]
fn the_emitted_text_of_each_kind_is_exactly_this() {
    let files = rendered();
    for (file, golden) in [
        ("events.rs", EVENT),
        ("commands.rs", INPUT),
        ("entities.rs", ENTITY),
        ("commands.rs", ERROR),
        ("types.rs", OPTIONAL),
        ("types.rs", UNION),
        ("types.rs", NEWTYPE),
        ("types.rs", LIST),
        ("events.rs", PRIMITIVES),
    ] {
        assert!(
            files[file].contains(golden),
            "{file} does not contain:\n{golden}"
        );
    }
}

/// `Presence` is declared once, in `types.rs`, and the other files reach it through `super`.
#[test]
fn presence_is_declared_once_and_shared() {
    let files = rendered();
    assert_eq!(
        files["types.rs"].matches("pub enum Presence<T> {").count(),
        1
    );
    for file in ["entities.rs", "events.rs", "commands.rs"] {
        assert!(!files[file].contains("pub enum Presence"), "{file}");
        assert!(
            files[file].contains("super::types::Presence<"),
            "{file} never uses the shared carrier"
        );
        assert!(
            files[file].contains(
                r#"#[serde(default, skip_serializing_if = "super::types::Presence::is_absent")]"#
            ),
            "{file} does not skip an absent key"
        );
    }
}

/// The emission lands where the crate's `#[path]` modules read it from.
#[test]
fn emit_writes_the_four_files_under_the_generated_root() {
    let root = repo().join("target/xtask-emit-cases");
    if root.exists() {
        fs::remove_dir_all(&root).expect("clear the fixture");
    }
    fs::create_dir_all(root.join("ir")).expect("fixture tree");
    fs::write(root.join("ir/system.json"), model()).expect("fixture model");
    emit::emit(&root).expect("emission");
    let files = rendered();
    for (name, body) in &files {
        let path = root.join("rust/mandate-contract/src").join(name);
        assert_eq!(&fs::read_to_string(&path).expect("emitted file"), body);
    }
}

/// A declared reference the model does not carry is a refusal, in every position.
///
/// The class is "a name that resolves to nothing", and the emitter answers it the same way
/// wherever it sits: a struct field, a command input, a union variant, the value a newtype
/// wraps. The credential walk is listed here too, because that is the position where a silent
/// `None` would read as "this declaration holds no secret" rather than "this name is not one".
#[test]
fn a_declared_reference_the_model_does_not_carry_is_refused_everywhere() {
    let missing = serde_json::json!({"kind": "declared", "name": "mandate.core.NotDeclared"});
    for (path, position) in [
        (
            vec!["events", "mandate.identity.SessionRevoked", "fields", "0"],
            "context",
        ),
        (
            vec!["commands", "mandate.audit.RecordAuditEvent", "input", "0"],
            "emitter_context",
        ),
        (
            vec!["entities", "mandate.identity.Principal", "fields", "0"],
            "kind",
        ),
        (
            vec!["errors", "mandate.audit.Denied", "fields", "0"],
            "reason",
        ),
    ] {
        let mut model: Value = serde_json::from_slice(&model()).expect("the committed IR parses");
        let mut at = &mut model;
        for step in &path {
            at = match step.parse::<usize>() {
                Ok(index) => &mut at.as_array_mut().expect("an array")[index],
                Err(_) => &mut at[step],
            };
        }
        at["type_ref"] = missing.clone();
        let refusal = emit::render(&serde_json::to_vec(&model).expect("serialize"))
            .expect_err("a reference to nothing is refused")
            .to_string();
        assert!(refusal.contains("mandate.core.NotDeclared"), "{refusal}");
        assert!(refusal.contains(position), "{refusal}");
    }
}

/// A type the credential walk reaches but the model does not declare is a refusal, not a pass.
#[test]
fn an_unresolvable_name_inside_the_credential_walk_is_refused() {
    let mut model: Value = serde_json::from_slice(&model()).expect("the committed IR parses");
    model["types"]["mandate.core.VerifiedContext"]["body"]["fields"]
        .as_array_mut()
        .expect("struct fields")
        .push(serde_json::json!({
            "name": "provenance",
            "type_ref": {"kind": "declared", "name": "mandate.core.NotDeclared"},
            "naming": {}
        }));
    let refusal = emit::render(&serde_json::to_vec(&model).expect("serialize"))
        .expect_err("an unresolvable name is refused")
        .to_string();
    assert!(refusal.contains("mandate.core.NotDeclared"), "{refusal}");
}

/// Two declarations that become one Rust name are refused, naming both and the name.
///
/// The naming rule drops every character Rust cannot take, so it is not injective. ESS refuses
/// this itself; an emitter that reproduced the rule without the guard would answer with two
/// declarations of one name — and where the two land in different modules, with no answer.
#[test]
fn two_declarations_that_become_one_rust_name_are_refused() {
    for (kind, name, collides_with) in [
        ("types", "mandate.core.Space_Id", "mandate.core.SpaceId"),
        (
            "events",
            "mandate.identity.Session_Revoked",
            "mandate.identity.SessionRevoked",
        ),
    ] {
        let mut model: Value = serde_json::from_slice(&model()).expect("the committed IR parses");
        let existing = model[kind][collides_with].clone();
        model[kind][name] = existing;
        let refusal = emit::render(&serde_json::to_vec(&model).expect("serialize"))
            .expect_err("a Rust name two declarations reach is refused")
            .to_string();
        assert!(refusal.contains(&emit::declaration_name(name)), "{refusal}");
        assert!(refusal.contains(name), "{refusal}");
        assert!(refusal.contains(collides_with), "{refusal}");
    }
}

/// A declaration that would collide with the `Presence` carrier is refused too.
#[test]
fn a_declaration_that_becomes_the_presence_carriers_name_is_refused() {
    let mut model: Value = serde_json::from_slice(&model()).expect("the committed IR parses");
    model["types"]["Presence"] = serde_json::json!({
        "name": "Presence",
        "body": {"kind": "newtype", "of": {"kind": "primitive", "name": "string"}, "invariants": []},
        "naming": {}
    });
    let refusal = emit::render(&serde_json::to_vec(&model).expect("serialize"))
        .expect_err("the carrier's name is taken")
        .to_string();
    assert!(refusal.contains("Presence"), "{refusal}");
}

/// An entity field that collides with what the record already carries is refused.
///
/// The emitted record is the declared identity, the declared fields and an injected `state`.
/// A declared field named `state` — or named for the identity, `id` — would be the second key
/// of that name in one record, which serde answers with a compile error in a generated file.
#[test]
fn an_entity_field_that_collides_with_the_identity_or_the_state_is_refused() {
    for name in ["state", "id"] {
        let mut model: Value = serde_json::from_slice(&model()).expect("the committed IR parses");
        model["entities"]["mandate.identity.Principal"]["fields"]
            .as_array_mut()
            .expect("entity fields")
            .push(serde_json::json!({
                "name": name,
                "type_ref": {"kind": "primitive", "name": "string"},
                "naming": {}
            }));
        let refusal = emit::render(&serde_json::to_vec(&model).expect("serialize"))
            .expect_err("a field the record already carries is refused")
            .to_string();
        assert!(refusal.contains(name), "{refusal}");
        assert!(refusal.contains("mandate.identity.Principal"), "{refusal}");
    }
}

/// An entity whose lifecycle admits no state is refused: a record no value can inhabit.
#[test]
fn an_entity_with_no_lifecycle_state_is_refused() {
    let mut model: Value = serde_json::from_slice(&model()).expect("the committed IR parses");
    model["entities"]["mandate.identity.Principal"]["lifecycle"]["states"] = serde_json::json!([]);
    model["types"]["mandate.identity.Principal.State"]["body"]["variants"] = serde_json::json!([]);
    let refusal = emit::render(&serde_json::to_vec(&model).expect("serialize"))
        .expect_err("an entity with no lifecycle state is refused")
        .to_string();
    assert!(refusal.contains("mandate.identity.Principal"), "{refusal}");
}

/// An entity whose state type does not carry its lifecycle states is refused.
#[test]
fn an_entity_whose_state_type_disagrees_with_its_lifecycle_is_refused() {
    let mut model: Value = serde_json::from_slice(&model()).expect("the committed IR parses");
    model["types"]["mandate.identity.Principal.State"]["body"]["variants"] =
        serde_json::json!(["Active", "Disabled", "Retired"]);
    let refusal = emit::render(&serde_json::to_vec(&model).expect("serialize"))
        .expect_err("a state type that disagrees with its lifecycle is refused")
        .to_string();
    assert!(refusal.contains("mandate.identity.Principal"), "{refusal}");
}

/// An optional is a record key or it is refused, in every position the model can put one.
///
/// Absence is a property of a *key*. `Presence` can be skipped out of an object and read back
/// from a missing key, and it can do neither anywhere else: the contract's own JSON Schema
/// projection spells absence in a newtype as `null` (`anyOf: [$ref, {"type": "null"}]`), in a
/// union as a content key dropped from `required`, and in a list it has no spelling at all.
/// So the enumeration below is every position `positions()` reports that is not a record key,
/// and each one is a refusal naming the declaration that carries it.
#[test]
fn an_optional_is_a_record_key_or_it_is_refused() {
    let optional = serde_json::json!({
        "kind": "optional",
        "of": {"kind": "declared", "name": "mandate.core.SessionId"}
    });

    // Inside a list, on an event field and on an error field.
    for (kind, declaration) in [
        ("events", "mandate.identity.SessionRevoked"),
        ("errors", "mandate.audit.Denied"),
    ] {
        let mut model: Value = serde_json::from_slice(&model()).expect("the committed IR parses");
        model[kind][declaration]["fields"]
            .as_array_mut()
            .expect("fields")
            .push(serde_json::json!({
                "name": "prior_ids",
                "type_ref": {"kind": "list", "of": optional.clone()},
                "naming": {}
            }));
        let refusal = emit::render(&serde_json::to_vec(&model).expect("serialize"))
            .expect_err("an optional inside a list is refused")
            .to_string();
        assert!(refusal.contains("prior_ids"), "{refusal}");
        assert!(refusal.contains(declaration), "{refusal}");
        assert!(refusal.contains("inside a list"), "{refusal}");
    }

    // A union variant.
    let mut variant: Value = serde_json::from_slice(&model()).expect("the committed IR parses");
    variant["types"]["mandate.core.AuthoritySubject"]["body"]["variants"]["team"] =
        optional.clone();
    let refusal = emit::render(&serde_json::to_vec(&variant).expect("serialize"))
        .expect_err("an optional union variant is refused")
        .to_string();
    assert!(
        refusal.contains("mandate.core.AuthoritySubject"),
        "{refusal}"
    );
    assert!(refusal.contains("union variant"), "{refusal}");

    // The value a newtype wraps.
    let mut wrapped: Value = serde_json::from_slice(&model()).expect("the committed IR parses");
    wrapped["types"]["mandate.core.Audience"]["body"]["of"] = optional.clone();
    let refusal = emit::render(&serde_json::to_vec(&wrapped).expect("serialize"))
        .expect_err("an optional newtype is refused")
        .to_string();
    assert!(refusal.contains("mandate.core.Audience"), "{refusal}");

    // An optional inside another optional, on a record key that may itself be optional.
    let mut nested: Value = serde_json::from_slice(&model()).expect("the committed IR parses");
    nested["events"]["mandate.identity.SessionRevoked"]["fields"][0]["type_ref"] =
        serde_json::json!({"kind": "optional", "of": optional.clone()});
    let refusal = emit::render(&serde_json::to_vec(&nested).expect("serialize"))
        .expect_err("an optional inside an optional is refused")
        .to_string();
    assert!(
        refusal.contains("mandate.identity.SessionRevoked"),
        "{refusal}"
    );
    assert!(refusal.contains("inside another optional"), "{refusal}");

    // And the shipped model puts an optional only on record keys, so none of this fires on it.
    let files = rendered();
    for body in files.values() {
        assert!(
            !body.contains("Presence<Presence<"),
            "a nested optional was emitted"
        );
        assert!(
            !body.contains("Vec<Presence<"),
            "an optional list element was emitted"
        );
        assert!(
            !body.contains("(pub Presence<"),
            "an optional newtype was emitted"
        );
    }
}

/// Every refusal names the declaration that carries it, and the field inside it.
///
/// A refusal that names neither is reported against a generated file, and the whole point of
/// the emitter is that a contract defect is reported against the declaration. The two that did
/// not — an unmapped primitive and an unmapped type expression — are the last of the class.
#[test]
fn every_refusal_names_the_declaration_and_the_field() {
    for type_ref in [
        serde_json::json!({"kind": "primitive", "name": "decimal"}),
        serde_json::json!({"kind": "map", "of": {"kind": "primitive", "name": "string"}}),
        serde_json::json!({"kind": "declared", "name": "mandate.core.NotDeclared"}),
        serde_json::json!({
            "kind": "list",
            "of": {"kind": "optional", "of": {"kind": "declared", "name": "mandate.core.SessionId"}}
        }),
    ] {
        for (kind, declaration) in [
            ("events", "mandate.identity.SessionRevoked"),
            ("entities", "mandate.identity.Principal"),
            ("errors", "mandate.audit.Denied"),
        ] {
            let mut model: Value =
                serde_json::from_slice(&model()).expect("the committed IR parses");
            model[kind][declaration]["fields"]
                .as_array_mut()
                .expect("fields")
                .push(serde_json::json!({
                    "name": "rate",
                    "type_ref": type_ref.clone(),
                    "naming": {}
                }));
            let refusal = emit::render(&serde_json::to_vec(&model).expect("serialize"))
                .expect_err("the emitter refuses what it cannot map")
                .to_string();
            assert!(refusal.contains(declaration), "{type_ref}: {refusal}");
            assert!(refusal.contains("rate"), "{type_ref}: {refusal}");
        }
    }
}

/// An `integer` is `serde_json::Number`, because the schema's `integer` is not an `i64`.
///
/// `{"type": "integer"}` in JSON Schema 2020-12 is any number with a zero fractional part, and
/// the projection carries no range, so `1.0` and `2^63` are both documents the contract admits
/// and neither is an `i64`. This is ESS's own mapping for the same reason.
#[test]
fn an_integer_is_the_number_the_schema_admits() {
    let files = rendered();
    assert!(files["events.rs"].contains("pub generation: ::serde_json::Number,"));
    assert!(files["entities.rs"].contains("pub generation: ::serde_json::Number,"));
    assert!(!files["events.rs"].contains("i64"));
    assert!(!files["entities.rs"].contains("i64"));
    assert!(!files["commands.rs"].contains("i64"));
    assert!(!files["types.rs"].contains("i64"));
}
