[package]
name = "mandate-model"
description = "Framework-independent canonical domain."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
mandate-types = { version = "0.1.0", path = "../mandate-types" }
serde = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
