//! The composition binary, **spawned as a child process**, completing one federated login
//! against an issuer that really signed the proof.
//!
//! # What is different here, and why the file exists
//!
//! Every case in `tests/serve.rs` builds a [`mandate_control_plane::adapters::Deployment`]
//! in-process and hands it `mandate_federation::verifier::ConstructedVerifier` — a double
//! that performs no cryptography and returns the proof it was constructed with. `src/main.rs`
//! wires `RealVerifier` over `UreqJwks`, which fetches an OIDC discovery document and a JWK
//! Set **over the network** and refuses anything that is not a signed JWT carrying a `kid`
//! that set publishes. No in-process case reaches a byte of that.
//!
//! So this case spawns `target/debug/mandate-control-plane serve` and stands a loopback HTTP
//! issuer beside it: `UreqJwks::admits` (`crates/mandate-federation/src/verifier_real.rs`)
//! admits `http` when the host is loopback, so the issuer needs no TLS. The proof is minted
//! by `mandate_token::signing_real::RealSigner` under a P-256 key generated when the case
//! runs, and the key set the issuer publishes is that signer's own `published_keys()` — so
//! the child verifies a signature made by a key it fetched, and nothing in this file can
//! make it do otherwise.
//!
//! **No key is committed.** The signing key is generated by `aws_lc_rs` on each run; the only
//! key text in this file is the public JWK the `--key` flag publishes, which carries no
//! private member.
//!
//! # The child process
//!
//! [`Served`] owns it. `Drop` kills and reaps on every path — assertion failure, panic, early
//! return — and the wait for the listener is bounded: a child that never binds fails the case
//! with its own stderr rather than hanging.

use std::io::{BufRead, BufReader, Read, Write};
use std::net::{SocketAddr, TcpListener, TcpStream};
use std::path::{Path, PathBuf};
use std::process::{Child, ChildStderr, ChildStdout, Command, Stdio};
use std::time::{Duration as HostDuration, Instant};

use aws_lc_rs::rand::SystemRandom;
use aws_lc_rs::signature::{ECDSA_P256_SHA256_FIXED_SIGNING, EcdsaKeyPair};
use mandate_token::signing_real::{
    AllowedAlgorithms, CredentialSigner, RealSigner, SigningKeyMaterial, StandardClaims,
    SystemClock,
};
use mandate_types::value::{Uuid, encode_base64};
use mandate_types::{Audience, Issuer, PrincipalId, SigningAlgorithm};

/// The client identifier the IdP issued Mandate, which a proof's `aud` must name.
const IDP_CLIENT: &str = "mandate-at-idp";

/// The `kid` the loopback issuer publishes its signing key under.
const IDP_KID: &str = "idp-key-1";

/// The algorithm the connection is configured to verify under, and the one the proof is
/// signed with. `RealVerifier` compares the header to the connection's configured name and
/// never selects from the header (`../sources/original-design.md:2527`).
const ALGORITHM: &str = "ES256";

/// The issuer identifier the served deployment publishes its own metadata under.
const AS_ISSUER: &str = "https://mandate.example";

const REDIRECT: &str = "https://client.example/callback";

/// The audience the registered resource server holds.
const TARGET_AUDIENCE: &str = "https://api.example";

/// RFC 7636 appendix B's code verifier and the S256 challenge of it.
const VERIFIER: &str = "dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk";
const CHALLENGE: &str = "E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM";

/// How far ahead the minted proof's `exp` sits. Well inside `RealVerifier`'s own ceiling on
/// a proof lifetime, which is a day.
const PROOF_TTL: u64 = 300;

/// How long the case waits for the child to bind before failing with its stderr.
const LISTEN_DEADLINE: HostDuration = HostDuration::from_secs(30);

/// A public EC JWK the `--key` flag publishes as the deployment's own key set. Public parts
/// only: RFC 7517 section 9.2's private members are refused by `read_key`, and none is here.
const AS_KEY_DOCUMENT: &str = r#"{"kty":"EC","kid":"login-key-1","use":"sig","alg":"ES256",
  "crv":"P-256","x":"f83OJ3D2xF1Bg8vub9tLe1gHMzV76e8Tus9uPHvRVEU",
  "y":"x_FEzRu9m36HLN_tue659LNpXW6pCyStikYjKIWI5a0"}"#;

fn uuid(tag: u8) -> Uuid {
    Uuid::from_bytes([tag; 16])
}

fn organization() -> Uuid {
    uuid(0x0a)
}

fn principal() -> Uuid {
    uuid(0x51)
}

fn connection() -> Uuid {
    uuid(0xc0)
}

fn client() -> Uuid {
    uuid(0x0c)
}

fn resource_server() -> Uuid {
    uuid(0x70)
}

fn external_principal() -> Uuid {
    uuid(0xe1)
}

/// The `sub` the IdP asserts. `StandardClaims` writes `sub` from a [`PrincipalId`], so the
/// external subject this case presents is that identifier's own text — the link the
/// `--connection` document seeds names exactly the same string.
fn external_subject() -> Uuid {
    uuid(0x5b)
}

// ------------------------------------------------------------------ the loopback issuer

/// The signer whose key the loopback issuer publishes, over a key generated for this run.
fn idp_signer() -> RealSigner<SystemClock> {
    let algorithm = SigningAlgorithm::new(ALGORITHM);
    let pkcs8 =
        EcdsaKeyPair::generate_pkcs8(&ECDSA_P256_SHA256_FIXED_SIGNING, &SystemRandom::new())
            .expect("a generated elliptic-curve key");
    let material = SigningKeyMaterial::from_pem(IDP_KID, &algorithm, &pem_of(pkcs8.as_ref()))
        .expect("the generated key in the PEM envelope a deployment supplies");
    RealSigner::new(
        AllowedAlgorithms::new(&[algorithm]).expect("a non-empty allowlist"),
        material,
        SystemClock,
        PROOF_TTL,
        PROOF_TTL,
    )
    .expect("an overlap no shorter than the proof lifetime")
}

/// The PKCS#8 DER in the `PRIVATE KEY` envelope [`SigningKeyMaterial::from_pem`] reads.
fn pem_of(der: &[u8]) -> String {
    let body = encode_base64(der);
    let mut wrapped = String::new();
    for chunk in body.as_bytes().chunks(64) {
        wrapped.push_str(std::str::from_utf8(chunk).expect("base64 is ASCII"));
        wrapped.push('\n');
    }
    format!("-----BEGIN PRIVATE KEY-----\n{wrapped}-----END PRIVATE KEY-----\n")
}

/// Bind a loopback HTTP issuer publishing an OIDC discovery document and `jwks`, and answer
/// with the issuer identifier it is reachable at.
///
/// The thread is detached: it lives as long as the test process, which is how the in-process
/// listener cases serve theirs, and it holds no resource the child owns.
fn issuer_publishing(jwks: String) -> String {
    let listener = TcpListener::bind("127.0.0.1:0").expect("an ephemeral port on the loopback");
    let address = listener.local_addr().expect("the bound address");
    let issuer = format!("http://{address}");
    let discovery = format!(r#"{{"issuer":"{issuer}","jwks_uri":"{issuer}/jwks"}}"#);
    std::thread::spawn(move || {
        for accepted in listener.incoming() {
            let Ok(mut stream) = accepted else { continue };
            let Some(path) = request_target(&stream) else {
                continue;
            };
            let served = if path.starts_with("/.well-known/openid-configuration") {
                Some(discovery.clone())
            } else if path.starts_with("/jwks") {
                Some(jwks.clone())
            } else {
                None
            };
            let response = match served {
                Some(body) => format!(
                    "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\
                     Content-Length: {}\r\nConnection: close\r\n\r\n{body}",
                    body.len()
                ),
                None => "HTTP/1.1 404 Not Found\r\nContent-Length: 0\r\nConnection: close\r\n\r\n"
                    .to_owned(),
            };
            let _ = stream.write_all(response.as_bytes());
            let _ = stream.flush();
            let _ = stream.shutdown(std::net::Shutdown::Both);
        }
    });
    issuer
}

/// The request target of one HTTP/1.1 request, with its header block drained off the socket.
fn request_target(stream: &TcpStream) -> Option<String> {
    let mut reader = BufReader::new(stream.try_clone().ok()?);
    let mut line = String::new();
    reader.read_line(&mut line).ok()?;
    loop {
        let mut header = String::new();
        match reader.read_line(&mut header) {
            Ok(0) => break,
            Ok(_) if header.trim().is_empty() => break,
            Ok(_) => {}
            Err(_) => break,
        }
    }
    line.split(' ').nth(1).map(ToOwned::to_owned)
}

// ------------------------------------------------------------------- the flag documents

/// Where this case's flag documents are written: cargo's own per-target scratch directory,
/// so nothing here writes outside the build tree.
fn document(name: &str, body: &str) -> PathBuf {
    let directory = Path::new(env!("CARGO_TARGET_TMPDIR")).join("end-to-end");
    std::fs::create_dir_all(&directory).expect("a writable scratch directory");
    let path = directory.join(name);
    std::fs::write(&path, body).expect("the flag document is written");
    path
}

fn stated(path: &Path) -> &str {
    path.to_str().expect("a UTF-8 path")
}

fn connection_document(issuer: &str) -> String {
    format!(
        r#"{{"connection_id":"{connection}","organization":"{organization}",
          "issuer":"{issuer}","client_id":"{IDP_CLIENT}","algorithm":"{ALGORITHM}",
          "tenant_resolution":{{"configured_organization":"{organization}"}},
          "jit_provisioning":false,
          "link":{{"principal_id":"{principal}","external_principal_id":"{external}",
            "subject":"{subject}","linked_at":"2026-09-01T00:00:00Z"}}}}"#,
        connection = connection(),
        organization = organization(),
        principal = principal(),
        external = external_principal(),
        subject = external_subject(),
    )
}

fn client_document() -> String {
    format!(
        r#"{{"client_id":"{client}","organization":"{organization}","public":true,
          "redirect_uris":["{REDIRECT}"],"pkce_method":"S256"}}"#,
        client = client(),
        organization = organization(),
    )
}

fn resource_server_document() -> String {
    format!(
        r#"{{"resource_server_id":"{target}","organization":"{organization}",
          "audience":"{TARGET_AUDIENCE}",
          "profile":{{"name":"reference","kind":"Reference","revocation":"ImmediateOnline",
            "max_ttl":"PT1H","positive_cache_ttl":"PT30S",
            "requires_online_authorization":true}},
          "allowed_exchange_sources":[]}}"#,
        target = resource_server(),
        organization = organization(),
    )
}

// --------------------------------------------------------------------- the child process

/// The spawned binary, and the two pipes it answers on.
///
/// Every field is an `Option` so that the child can be killed and reaped exactly once, from
/// either [`Served::output`] or [`Drop`], and the pipes read only after it is dead — a read
/// to end of file on a live child's stdout does not return.
struct Served {
    child: Option<Child>,
    stdout: Option<ChildStdout>,
    stderr: Option<ChildStderr>,
}

impl Served {
    /// Spawn `serve` on `address`, configured through the four flag documents.
    fn spawn(
        address: SocketAddr,
        connection: &Path,
        key: &Path,
        client: &Path,
        target: &Path,
    ) -> Self {
        let mut child = Command::new(env!("CARGO_BIN_EXE_mandate-control-plane"))
            .args([
                "serve",
                "--listen",
                &address.to_string(),
                "--issuer",
                AS_ISSUER,
                "--connection",
                stated(connection),
                "--key",
                stated(key),
                "--client",
                stated(client),
                "--resource-server",
                stated(target),
            ])
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .expect("the composition binary runs");
        let stdout = child.stdout.take();
        let stderr = child.stderr.take();
        Self {
            child: Some(child),
            stdout,
            stderr,
        }
    }

    /// Kill the child and wait for it. Idempotent, and called on every path including panic.
    fn kill_and_reap(&mut self) {
        if let Some(mut child) = self.child.take() {
            let _ = child.kill();
            let _ = child.wait();
        }
    }

    /// Whether the child has already given up, and what it said if it has.
    fn exited(&mut self) -> bool {
        self.child
            .as_mut()
            .is_none_or(|child| child.try_wait().is_ok_and(|status| status.is_some()))
    }

    /// The child's stdout and stderr, read after it is dead so both reads terminate.
    fn output(&mut self) -> (String, String) {
        self.kill_and_reap();
        let mut out = String::new();
        if let Some(mut handle) = self.stdout.take() {
            let _ = handle.read_to_string(&mut out);
        }
        let mut err = String::new();
        if let Some(mut handle) = self.stderr.take() {
            let _ = handle.read_to_string(&mut err);
        }
        (out, err)
    }

    /// Wait until the child accepts on `address`, bounded.
    ///
    /// A child that exits, or never binds within the deadline, fails the case **with its own
    /// stderr**: a composition that refused its own configuration says why on that pipe, and
    /// a case that hangs instead reports nothing at all.
    fn listening(&mut self, address: SocketAddr) {
        let deadline = Instant::now() + LISTEN_DEADLINE;
        loop {
            if TcpStream::connect_timeout(&address, HostDuration::from_millis(200)).is_ok() {
                return;
            }
            if self.exited() {
                let (out, err) = self.output();
                panic!(
                    "the child exited before it bound {address}; stdout {out:?}, stderr {err:?}"
                );
            }
            if Instant::now() >= deadline {
                let (out, err) = self.output();
                panic!("the child never bound {address}; stdout {out:?}, stderr {err:?}");
            }
            std::thread::sleep(HostDuration::from_millis(25));
        }
    }
}

impl Drop for Served {
    fn drop(&mut self) {
        self.kill_and_reap();
    }
}

// ------------------------------------------------------------------------ the HTTP calls

/// One response, as the bytes off the socket.
struct Response {
    status: u16,
    headers: Vec<(String, String)>,
    body: String,
}

impl Response {
    fn header(&self, name: &str) -> Option<&str> {
        self.headers
            .iter()
            .find(|(presented, _)| presented.eq_ignore_ascii_case(name))
            .map(|(_, value)| value.as_str())
    }
}

/// Write raw bytes to the child and read the whole response back off the socket.
fn exchange(address: SocketAddr, raw: &[u8]) -> Response {
    let mut stream = TcpStream::connect(address).expect("the child accepts");
    stream
        .set_read_timeout(Some(HostDuration::from_secs(20)))
        .expect("a read bound on the case's own socket");
    stream.write_all(raw).expect("the request is written");
    stream.flush().expect("the request is flushed");
    let mut raw = Vec::new();
    stream.read_to_end(&mut raw).expect("the response is read");
    let text = String::from_utf8_lossy(&raw).into_owned();
    let (head, body) = text
        .split_once("\r\n\r\n")
        .unwrap_or_else(|| panic!("a response with a head and a body, got {text:?}"));
    let mut lines = head.split("\r\n");
    let status_line = lines.next().expect("a status line");
    let status = status_line
        .split(' ')
        .nth(1)
        .and_then(|code| code.parse().ok())
        .unwrap_or_else(|| panic!("a status code in {status_line:?}"));
    Response {
        status,
        headers: lines
            .filter_map(|line| line.split_once(": "))
            .map(|(name, value)| (name.to_owned(), value.to_owned()))
            .collect(),
        body: body.to_owned(),
    }
}

/// Percent-encode everything outside RFC 3986's unreserved set.
fn encoded(value: &str) -> String {
    let mut out = String::new();
    for byte in value.as_bytes() {
        if byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'.' | b'_' | b'~') {
            out.push(char::from(*byte));
        } else {
            out.push_str(&format!("%{byte:02X}"));
        }
    }
    out
}

fn get(path: &str, headers: &[(&str, &str)]) -> Vec<u8> {
    let mut raw = format!("GET {path} HTTP/1.1\r\nHost: mandate.example\r\n");
    for (name, value) in headers {
        raw.push_str(&format!("{name}: {value}\r\n"));
    }
    raw.push_str("\r\n");
    raw.into_bytes()
}

fn post(path: &str, media_type: &str, body: &str, headers: &[(&str, &str)]) -> Vec<u8> {
    let mut raw = format!(
        "POST {path} HTTP/1.1\r\nHost: mandate.example\r\nContent-Type: {media_type}\r\n\
         Content-Length: {}\r\n",
        body.len()
    );
    for (name, value) in headers {
        raw.push_str(&format!("{name}: {value}\r\n"));
    }
    raw.push_str("\r\n");
    raw.push_str(body);
    raw.into_bytes()
}

fn member(body: &str, name: &str) -> String {
    let document: serde_json::Value =
        serde_json::from_str(body).unwrap_or_else(|_| panic!("a JSON body, got {body:?}"));
    document
        .get(name)
        .and_then(serde_json::Value::as_str)
        .unwrap_or_else(|| panic!("a `{name}` member in {body}"))
        .to_owned()
}

/// What the child answered, on stdout, so the run itself carries the four answers rather
/// than only the verdict.
fn answered(step: &str, response: &Response) {
    println!("{step}: {} {:?}", response.status, response.body);
    if let Some(location) = response.header("Location") {
        println!("{step}: Location {location:?}");
    }
}

// ----------------------------------------------------------------------- the acceptance

/// The acceptance of `story:served-login-end-to-end`: the spawned binary, configured through
/// four flag documents, completes one login against an issuer that really signed the proof.
#[test]
fn the_spawned_binary_completes_one_login_against_an_issuer_that_signed_the_proof() {
    let signer = idp_signer();
    let jwks = serde_json::to_string(&signer.published_keys()).expect("the published key set");
    let issuer = issuer_publishing(jwks);

    let connection_path = document("connection.json", &connection_document(&issuer));
    let key_path = document("key.json", AS_KEY_DOCUMENT);
    let client_path = document("client.json", &client_document());
    let target_path = document("resource-server.json", &resource_server_document());

    // A port nothing holds: bound to learn it, released before the child is told to take it.
    let address = {
        let probe = TcpListener::bind("127.0.0.1:0").expect("an ephemeral port on the loopback");
        probe.local_addr().expect("the bound address")
    };
    let mut served = Served::spawn(
        address,
        &connection_path,
        &key_path,
        &client_path,
        &target_path,
    );
    served.listening(address);

    // The proof, signed by the key the issuer publishes and by no other.
    let proof = signer
        .sign(
            &serde_json::Map::new(),
            &StandardClaims {
                issuer: Issuer::new(&issuer),
                subject: PrincipalId::new(external_subject()),
                audience: Audience::new(IDP_CLIENT),
                token_id: "proof-1".to_owned(),
            },
        )
        .expect("a signed proof");

    // 1. The login opens a session, which means the child fetched the discovery document and
    //    the key set off the loopback issuer and verified the signature under them.
    let login = exchange(
        address,
        &post(
            "/v1/federation/login",
            "application/json",
            &format!(
                r#"{{"connection_id":"{}","proof":"{}"}}"#,
                connection(),
                encode_base64(proof.token.as_bytes())
            ),
            &[],
        ),
    );
    answered("step 1 POST /v1/federation/login", &login);
    assert_eq!(
        login.status, 200,
        "the login answered {} {}",
        login.status, login.body
    );
    assert!(
        !member(&login.body, "session_id").is_empty(),
        "the declared `session_id` response, got {}",
        login.body
    );
    let session_proof = member(&login.body, "session_proof");

    // 2. The authorization request yields a code, which needs the `--client` and
    //    `--resource-server` documents to have seeded a client and a target.
    let authorize = exchange(
        address,
        &get(
            &format!(
                "/oauth/authorize?response_type=code&client_id={}&redirect_uri={}\
                 &code_challenge={CHALLENGE}&code_challenge_method=S256&state=xyzzy\
                 &nonce=n-0S6&target={}&scope={}",
                client(),
                encoded(REDIRECT),
                resource_server(),
                encoded("read")
            ),
            &[("Authorization", &format!("Bearer {session_proof}"))],
        ),
    );
    answered("step 2 GET /oauth/authorize", &authorize);
    assert_eq!(
        authorize.status, 302,
        "RFC 6749 section 4.1.2 answers with a redirect; got {} {}",
        authorize.status, authorize.body
    );
    let location = authorize
        .header("Location")
        .expect("a Location header")
        .to_owned();
    assert!(
        location.starts_with(REDIRECT),
        "the redirect is the one the client document registered, got {location}"
    );
    assert!(
        location.contains("state=xyzzy"),
        "RFC 6749 section 4.1.2 returns the exact state received, got {location}"
    );
    let (_, query) = location
        .split_once('?')
        .expect("a redirect carrying a query component");
    let code = mandate_proto::oauth::decode_form(query)
        .expect("an x-www-form-urlencoded query")
        .get("code")
        .expect("a code parameter")
        .to_owned();

    // 3. The token endpoint issues the credential.
    let token = exchange(
        address,
        &post(
            "/oauth/token",
            "application/x-www-form-urlencoded",
            &format!(
                "grant_type=authorization_code&client_id={}&code={}&code_verifier={VERIFIER}\
                 &redirect_uri={}",
                client(),
                encoded(&code),
                encoded(REDIRECT)
            ),
            &[],
        ),
    );
    answered("step 3 POST /oauth/token", &token);
    assert_eq!(
        token.status, 200,
        "the token endpoint answered {} {}",
        token.status, token.body
    );
    assert_eq!(member(&token.body, "token_type"), "Bearer");
    let credential = member(&token.body, "access_token");

    // 4. Introspection answers active for the credential the road just issued.
    let introspect = exchange(
        address,
        &post(
            "/oauth/introspect",
            "application/x-www-form-urlencoded",
            &format!("token={}", encoded(&credential)),
            &[("Authorization", &format!("Bearer {credential}"))],
        ),
    );
    answered("step 4 POST /oauth/introspect", &introspect);
    assert_eq!(
        introspect.status, 200,
        "introspection answered {} {}",
        introspect.status, introspect.body
    );
    let document: serde_json::Value =
        serde_json::from_str(&introspect.body).expect("RFC 7662 section 2.2's JSON");
    assert_eq!(
        document.get("active").and_then(serde_json::Value::as_bool),
        Some(true),
        "the credential the road just issued is usable; got {}",
        introspect.body
    );

    // The child is killed and reaped here, and its stdout read once it is dead. An operator
    // who cannot learn these three identities cannot call the three routes that select on
    // them, which is why the binary prints each one.
    let (out, err) = served.output();
    println!("child stdout {out:?}");
    println!("child stderr {err:?}");
    for seeded in [
        format!("seeded federation connection {}", connection()),
        format!("seeded oauth client {}", client()),
        format!("seeded resource server {}", resource_server()),
    ] {
        assert!(
            out.contains(&seeded),
            "the child prints every identity it seeded; {seeded:?} is not in {out:?}"
        );
    }
}
