//! The composition binary, **spawned as a child process**, completing one federated login
//! against an issuer that really signed the proof.
//!
//! # What is different here, and why the file exists
//!
//! Every case in `tests/serve.rs` builds a [`mandate_control_plane::adapters::Deployment`]
//! in-process and hands it `mandate_federation::verifier::ConstructedVerifier` — a double
//! that performs no cryptography and returns the proof it was constructed with. `src/main.rs`
//! wires `RealVerifier` over `UreqJwks`, which fetches an OIDC discovery document and a JWK
//! Set **over the network** and refuses anything that is not a signed JWT carrying a `kid`
//! that set publishes. No in-process case reaches a byte of that.
//!
//! So this case spawns `target/debug/mandate-control-plane serve` and stands a loopback HTTP
//! issuer beside it: `UreqJwks::admits` (`crates/mandate-federation/src/verifier_real.rs`)
//! admits `http` when the host is loopback, so the issuer needs no TLS. The proof is minted
//! by `mandate_token::signing_real::RealSigner` under a P-256 key generated when the case
//! runs, and the key set the issuer publishes is that signer's own `published_keys()` — so
//! the child verifies a signature made by a key it fetched, and nothing in this file can
//! make it do otherwise.
//!
//! **No key is committed.** The signing key is generated by `aws_lc_rs` on each run; the only
//! key text in this file is the public JWK the `--key` flag publishes, which carries no
//! private member.
//!
//! # The child process
//!
//! [`Served`] owns it. `Drop` kills and reaps on every path — assertion failure, panic, early
//! return — and the wait for the listener is bounded: a child that never binds fails the case
//! with its own stderr rather than hanging.

use std::io::{BufRead, BufReader, Read, Write};
use std::net::{SocketAddr, TcpListener, TcpStream};
use std::path::{Path, PathBuf};
use std::process::{Child, ChildStderr, ChildStdout, Command, Stdio};
use std::sync::Mutex;
use std::time::{Duration as HostDuration, Instant};

use aws_lc_rs::rand::SystemRandom;
use aws_lc_rs::signature::{ECDSA_P256_SHA256_FIXED_SIGNING, EcdsaKeyPair};
use mandate_token::signing_real::{
    AllowedAlgorithms, CredentialSigner, RealSigner, SigningKeyMaterial, StandardClaims,
    SystemClock,
};
use mandate_types::value::{Uuid, encode_base64};
use mandate_types::{Audience, Issuer, PrincipalId, SigningAlgorithm};

/// The client identifier the IdP issued Mandate, which a proof's `aud` must name.
const IDP_CLIENT: &str = "mandate-at-idp";

/// The `kid` the loopback issuer publishes its signing key under.
const IDP_KID: &str = "idp-key-1";

/// The algorithm the connection is configured to verify under, and the one the proof is
/// signed with. `RealVerifier` compares the header to the connection's configured name and
/// never selects from the header (`../sources/original-design.md:2527`).
const ALGORITHM: &str = "ES256";

/// The issuer identifier the served deployment publishes its own metadata under.
const AS_ISSUER: &str = "https://mandate.example";

const REDIRECT: &str = "https://client.example/callback";

/// The audience the registered resource server holds.
const TARGET_AUDIENCE: &str = "https://api.example";

/// RFC 7636 appendix B's code verifier and the S256 challenge of it.
const VERIFIER: &str = "dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk";
const CHALLENGE: &str = "E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM";

/// A code verifier in the declared form that is not [`VERIFIER`]: 43 characters, every one
/// of them in RFC 3986's unreserved set, differing in the last.
///
/// Well-formed on purpose. `services/sts/src/redemption.rs:228-241` refuses a malformed
/// verifier as `VerifierMalformed` **before** it digests anything, so a verifier that was
/// merely the wrong shape would drive that refusal and never reach the digest comparison
/// this case exists to drive.
const MISMATCHED_VERIFIER: &str = "dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXj";

/// An issuer identifier no connection in this file is configured for.
const FOREIGN_ISSUER: &str = "https://not-the-configured-issuer.example";

/// A client identifier no connection in this file is configured for.
const FOREIGN_CLIENT: &str = "mandate-at-some-other-idp";

/// How far ahead the minted proof's `exp` sits. Well inside `RealVerifier`'s own ceiling on
/// a proof lifetime, which is a day.
const PROOF_TTL: u64 = 300;

/// How long the case waits for the child to bind before failing with its stderr.
const LISTEN_DEADLINE: HostDuration = HostDuration::from_secs(30);

/// A public EC JWK the `--key` flag publishes as the deployment's own key set. Public parts
/// only: RFC 7517 section 9.2's private members are refused by `read_key`, and none is here.
const AS_KEY_DOCUMENT: &str = r#"{"kty":"EC","kid":"login-key-1","use":"sig","alg":"ES256",
  "crv":"P-256","x":"f83OJ3D2xF1Bg8vub9tLe1gHMzV76e8Tus9uPHvRVEU",
  "y":"x_FEzRu9m36HLN_tue659LNpXW6pCyStikYjKIWI5a0"}"#;

fn uuid(tag: u8) -> Uuid {
    Uuid::from_bytes([tag; 16])
}

fn organization() -> Uuid {
    uuid(0x0a)
}

fn principal() -> Uuid {
    uuid(0x51)
}

fn connection() -> Uuid {
    uuid(0xc0)
}

/// A second organization, for the tenant-ambiguity case and nothing else.
fn other_organization() -> Uuid {
    uuid(0x0b)
}

/// The sibling connection the tenant-ambiguity case seeds on the same issuer.
fn other_connection() -> Uuid {
    uuid(0xc1)
}

/// A connection identity no `--connection` document seeds.
fn unseeded_connection() -> Uuid {
    uuid(0xcf)
}

fn client() -> Uuid {
    uuid(0x0c)
}

fn resource_server() -> Uuid {
    uuid(0x70)
}

fn external_principal() -> Uuid {
    uuid(0xe1)
}

/// The `sub` the IdP asserts. `StandardClaims` writes `sub` from a [`PrincipalId`], so the
/// external subject this case presents is that identifier's own text — the link the
/// `--connection` document seeds names exactly the same string.
fn external_subject() -> Uuid {
    uuid(0x5b)
}

// ------------------------------------------------------------------ the loopback issuer

/// The signer whose key the loopback issuer publishes, over a key generated for this run.
fn idp_signer() -> RealSigner<SystemClock> {
    let algorithm = SigningAlgorithm::new(ALGORITHM);
    let pkcs8 =
        EcdsaKeyPair::generate_pkcs8(&ECDSA_P256_SHA256_FIXED_SIGNING, &SystemRandom::new())
            .expect("a generated elliptic-curve key");
    let material = SigningKeyMaterial::from_pem(IDP_KID, &algorithm, &pem_of(pkcs8.as_ref()))
        .expect("the generated key in the PEM envelope a deployment supplies");
    RealSigner::new(
        AllowedAlgorithms::new(&[algorithm]).expect("a non-empty allowlist"),
        material,
        SystemClock,
        PROOF_TTL,
        PROOF_TTL,
    )
    .expect("an overlap no shorter than the proof lifetime")
}

/// The PKCS#8 DER in the `PRIVATE KEY` envelope [`SigningKeyMaterial::from_pem`] reads.
fn pem_of(der: &[u8]) -> String {
    let body = encode_base64(der);
    let mut wrapped = String::new();
    for chunk in body.as_bytes().chunks(64) {
        wrapped.push_str(std::str::from_utf8(chunk).expect("base64 is ASCII"));
        wrapped.push('\n');
    }
    format!("-----BEGIN PRIVATE KEY-----\n{wrapped}-----END PRIVATE KEY-----\n")
}

/// Bind a loopback HTTP issuer publishing an OIDC discovery document and `jwks`, and answer
/// with the issuer identifier it is reachable at.
///
/// The thread is detached: it lives as long as the test process, which is how the in-process
/// listener cases serve theirs, and it holds no resource the child owns.
fn issuer_publishing(jwks: String) -> String {
    // Under [`PORT`], because this is the file's **other** ephemeral bind and taking the
    // lock only in `stand_up` left the window it claims to close wide open: every case
    // stands its issuer up first, so an issuer binding here could be handed exactly the
    // port a concurrent case's probe had just released and its child had not yet taken.
    // The listener is kept for the life of the process, so the lock is needed only for the
    // bind itself — once bound, the port can never be handed out again.
    let listener = {
        let _holding = PORT
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        TcpListener::bind("127.0.0.1:0").expect("an ephemeral port on the loopback")
    };
    let address = listener.local_addr().expect("the bound address");
    let issuer = format!("http://{address}");
    let discovery = format!(r#"{{"issuer":"{issuer}","jwks_uri":"{issuer}/jwks"}}"#);
    std::thread::spawn(move || {
        for accepted in listener.incoming() {
            let Ok(mut stream) = accepted else { continue };
            let Some(path) = request_target(&stream) else {
                continue;
            };
            let served = if path.starts_with("/.well-known/openid-configuration") {
                Some(discovery.clone())
            } else if path.starts_with("/jwks") {
                Some(jwks.clone())
            } else {
                None
            };
            let response = match served {
                Some(body) => format!(
                    "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\
                     Content-Length: {}\r\nConnection: close\r\n\r\n{body}",
                    body.len()
                ),
                None => "HTTP/1.1 404 Not Found\r\nContent-Length: 0\r\nConnection: close\r\n\r\n"
                    .to_owned(),
            };
            let _ = stream.write_all(response.as_bytes());
            let _ = stream.flush();
            let _ = stream.shutdown(std::net::Shutdown::Both);
        }
    });
    issuer
}

/// The request target of one HTTP/1.1 request, with its header block drained off the socket.
fn request_target(stream: &TcpStream) -> Option<String> {
    let mut reader = BufReader::new(stream.try_clone().ok()?);
    let mut line = String::new();
    reader.read_line(&mut line).ok()?;
    loop {
        let mut header = String::new();
        match reader.read_line(&mut header) {
            Ok(0) => break,
            Ok(_) if header.trim().is_empty() => break,
            Ok(_) => {}
            Err(_) => break,
        }
    }
    line.split(' ').nth(1).map(ToOwned::to_owned)
}

// ------------------------------------------------------------------- the flag documents

/// Where one case's flag documents are written: cargo's own per-target scratch directory,
/// so nothing here writes outside the build tree.
///
/// **The directory is the case's own.** Every case in this file writes a `connection.json`
/// and the cases run in parallel threads of one process; a shared directory would have one
/// case's child read another case's document, and the case that lost the race would fail
/// for a reason that is not the one it drives.
fn document(case: &str, name: &str, body: &str) -> PathBuf {
    let directory = Path::new(env!("CARGO_TARGET_TMPDIR"))
        .join("end-to-end")
        .join(case);
    std::fs::create_dir_all(&directory).expect("a writable scratch directory");
    let path = directory.join(name);
    std::fs::write(&path, body).expect("the flag document is written");
    path
}

fn stated(path: &Path) -> &str {
    path.to_str().expect("a UTF-8 path")
}

/// One `--connection` document, with every member a refusal case varies stated.
///
/// The accepted path is [`ConnectionDocument::accepted`] and each refusal case is that
/// value with **one** member changed, so the construction a case drives is the difference
/// between two documents and not a second document written from scratch.
struct ConnectionDocument {
    connection_id: Uuid,
    organization: Uuid,
    issuer: String,
    /// The client a proof's `aud` must name. Not varied by any case here: the audience
    /// case varies the *proof*, because a connection naming a client no proof carries and
    /// a proof naming a client no connection carries are the same refusal read from the
    /// two ends, and only the proof end is the caller's.
    client_id: &'static str,
    /// `None` writes **no member at all**, which is the operator declining to configure
    /// verification. `ConnectionSeed::algorithm` reads through `mandate_types::value::present`,
    /// so an explicit `null` is refused by the reader rather than treated as absence, and
    /// the case would never reach the road it drives.
    algorithm: Option<&'static str>,
    /// Whether the document seeds the link a login resolves its principal through.
    linked: bool,
    /// Whether this connection admits just-in-time provisioning — that is, whether a first
    /// login with no link may create the principal rather than be refused.
    jit_provisioning: bool,
}

impl ConnectionDocument {
    /// The document the accepted case is served with.
    fn accepted(issuer: &str) -> Self {
        Self {
            connection_id: connection(),
            organization: organization(),
            issuer: issuer.to_owned(),
            client_id: IDP_CLIENT,
            algorithm: Some(ALGORITHM),
            linked: true,
            jit_provisioning: false,
        }
    }

    fn rendered(&self) -> String {
        let algorithm = match self.algorithm {
            Some(named) => format!(r#""algorithm":"{named}","#),
            None => String::new(),
        };
        let link = if self.linked {
            format!(
                r#","link":{{"principal_id":"{principal}",
                  "external_principal_id":"{external}","subject":"{subject}",
                  "linked_at":"2026-09-01T00:00:00Z"}}"#,
                principal = principal(),
                external = external_principal(),
                subject = external_subject(),
            )
        } else {
            String::new()
        };
        format!(
            r#"{{"connection_id":"{connection}","organization":"{organization}",
              "issuer":"{issuer}","client_id":"{client}",{algorithm}
              "tenant_resolution":{{"configured_organization":"{organization}"}},
              "jit_provisioning":{jit}{link}}}"#,
            connection = self.connection_id,
            organization = self.organization,
            issuer = self.issuer,
            client = self.client_id,
            jit = self.jit_provisioning,
        )
    }
}

fn client_document() -> String {
    format!(
        r#"{{"client_id":"{client}","organization":"{organization}","public":true,
          "redirect_uris":["{REDIRECT}"],"pkce_method":"S256"}}"#,
        client = client(),
        organization = organization(),
    )
}

fn resource_server_document() -> String {
    format!(
        r#"{{"resource_server_id":"{target}","organization":"{organization}",
          "audience":"{TARGET_AUDIENCE}",
          "profile":{{"name":"reference","kind":"Reference","revocation":"ImmediateOnline",
            "max_ttl":"PT1H","positive_cache_ttl":"PT30S",
            "requires_online_authorization":true}},
          "allowed_exchange_sources":[]}}"#,
        target = resource_server(),
        organization = organization(),
    )
}

// --------------------------------------------------------------------- the child process

/// The spawned binary, and the two pipes it answers on.
///
/// Every field is an `Option` so that the child can be killed and reaped exactly once, from
/// either [`Served::output`] or [`Drop`], and the pipes read only after it is dead — a read
/// to end of file on a live child's stdout does not return.
struct Served {
    child: Option<Child>,
    stdout: Option<ChildStdout>,
    stderr: Option<ChildStderr>,
}

impl Served {
    /// Spawn `serve` on `address`, configured through the four flag documents.
    ///
    /// `connections` is a slice because `--connection` is repeatable (`serve`'s
    /// `connections: Vec<PathBuf>`), and the tenant-ambiguity case needs two: one
    /// connection carries one rule and could only ever resolve to zero or one
    /// organization.
    fn spawn(
        address: SocketAddr,
        connections: &[PathBuf],
        key: &Path,
        client: &Path,
        target: &Path,
    ) -> Self {
        let mut arguments = vec![
            "serve".to_owned(),
            "--listen".to_owned(),
            address.to_string(),
            "--issuer".to_owned(),
            AS_ISSUER.to_owned(),
        ];
        for connection in connections {
            arguments.push("--connection".to_owned());
            arguments.push(stated(connection).to_owned());
        }
        for (flag, path) in [
            ("--key", key),
            ("--client", client),
            ("--resource-server", target),
        ] {
            arguments.push(flag.to_owned());
            arguments.push(stated(path).to_owned());
        }
        let mut child = Command::new(env!("CARGO_BIN_EXE_mandate-control-plane"))
            .args(&arguments)
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .expect("the composition binary runs");
        let stdout = child.stdout.take();
        let stderr = child.stderr.take();
        Self {
            child: Some(child),
            stdout,
            stderr,
        }
    }

    /// Kill the child and wait for it. Idempotent, and called on every path including panic.
    fn kill_and_reap(&mut self) {
        if let Some(mut child) = self.child.take() {
            let _ = child.kill();
            let _ = child.wait();
        }
    }

    /// Whether the child has already given up, and what it said if it has.
    fn exited(&mut self) -> bool {
        self.child
            .as_mut()
            .is_none_or(|child| child.try_wait().is_ok_and(|status| status.is_some()))
    }

    /// The child's stdout and stderr, read after it is dead so both reads terminate.
    fn output(&mut self) -> (String, String) {
        self.kill_and_reap();
        let mut out = String::new();
        if let Some(mut handle) = self.stdout.take() {
            let _ = handle.read_to_string(&mut out);
        }
        let mut err = String::new();
        if let Some(mut handle) = self.stderr.take() {
            let _ = handle.read_to_string(&mut err);
        }
        (out, err)
    }

    /// Wait until the child accepts on `address`, bounded.
    ///
    /// A child that exits, or never binds within the deadline, fails the case **with its own
    /// stderr**: a composition that refused its own configuration says why on that pipe, and
    /// a case that hangs instead reports nothing at all.
    fn listening(&mut self, address: SocketAddr) {
        let deadline = Instant::now() + LISTEN_DEADLINE;
        loop {
            // **The death check comes first, and the order is the whole point.** A connect
            // that succeeds says only that *something* is accepting on this address; it
            // does not say it is this child. Reading it before `exited` reported a dead
            // child as serving whenever anyone else held the port — the case then drove a
            // deployment it had not configured, and the promise this function's own
            // documentation makes, that a child which never binds fails with its own
            // stderr, was not kept. Asking whether the child is alive first cannot report
            // a dead one as serving.
            if self.exited() {
                let (out, err) = self.output();
                panic!(
                    "the child exited before it bound {address}; stdout {out:?}, stderr {err:?}"
                );
            }
            if TcpStream::connect_timeout(&address, HostDuration::from_millis(200)).is_ok() {
                return;
            }
            if Instant::now() >= deadline {
                let (out, err) = self.output();
                panic!("the child never bound {address}; stdout {out:?}, stderr {err:?}");
            }
            std::thread::sleep(HostDuration::from_millis(25));
        }
    }
}

impl Drop for Served {
    fn drop(&mut self) {
        self.kill_and_reap();
    }
}

// ------------------------------------------------------------------------ the HTTP calls

/// One response, as the bytes off the socket.
struct Response {
    status: u16,
    headers: Vec<(String, String)>,
    body: String,
}

impl Response {
    fn header(&self, name: &str) -> Option<&str> {
        self.headers
            .iter()
            .find(|(presented, _)| presented.eq_ignore_ascii_case(name))
            .map(|(_, value)| value.as_str())
    }
}

/// Write raw bytes to the child and read the whole response back off the socket.
fn exchange(address: SocketAddr, raw: &[u8]) -> Response {
    let mut stream = TcpStream::connect(address).expect("the child accepts");
    stream
        .set_read_timeout(Some(HostDuration::from_secs(20)))
        .expect("a read bound on the case's own socket");
    stream.write_all(raw).expect("the request is written");
    stream.flush().expect("the request is flushed");
    let mut raw = Vec::new();
    stream.read_to_end(&mut raw).expect("the response is read");
    let text = String::from_utf8_lossy(&raw).into_owned();
    let (head, body) = text
        .split_once("\r\n\r\n")
        .unwrap_or_else(|| panic!("a response with a head and a body, got {text:?}"));
    let mut lines = head.split("\r\n");
    let status_line = lines.next().expect("a status line");
    let status = status_line
        .split(' ')
        .nth(1)
        .and_then(|code| code.parse().ok())
        .unwrap_or_else(|| panic!("a status code in {status_line:?}"));
    Response {
        status,
        headers: lines
            .filter_map(|line| line.split_once(": "))
            .map(|(name, value)| (name.to_owned(), value.to_owned()))
            .collect(),
        body: body.to_owned(),
    }
}

/// Percent-encode everything outside RFC 3986's unreserved set.
fn encoded(value: &str) -> String {
    let mut out = String::new();
    for byte in value.as_bytes() {
        if byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'.' | b'_' | b'~') {
            out.push(char::from(*byte));
        } else {
            out.push_str(&format!("%{byte:02X}"));
        }
    }
    out
}

fn get(path: &str, headers: &[(&str, &str)]) -> Vec<u8> {
    let mut raw = format!("GET {path} HTTP/1.1\r\nHost: mandate.example\r\n");
    for (name, value) in headers {
        raw.push_str(&format!("{name}: {value}\r\n"));
    }
    raw.push_str("\r\n");
    raw.into_bytes()
}

fn post(path: &str, media_type: &str, body: &str, headers: &[(&str, &str)]) -> Vec<u8> {
    let mut raw = format!(
        "POST {path} HTTP/1.1\r\nHost: mandate.example\r\nContent-Type: {media_type}\r\n\
         Content-Length: {}\r\n",
        body.len()
    );
    for (name, value) in headers {
        raw.push_str(&format!("{name}: {value}\r\n"));
    }
    raw.push_str("\r\n");
    raw.push_str(body);
    raw.into_bytes()
}

fn member(body: &str, name: &str) -> String {
    let document: serde_json::Value =
        serde_json::from_str(body).unwrap_or_else(|_| panic!("a JSON body, got {body:?}"));
    document
        .get(name)
        .and_then(serde_json::Value::as_str)
        .unwrap_or_else(|| panic!("a `{name}` member in {body}"))
        .to_owned()
}

/// What the child answered, on stdout, so the run itself carries the four answers rather
/// than only the verdict.
fn answered(step: &str, response: &Response) {
    println!("{step}: {} {:?}", response.status, response.body);
    if let Some(location) = response.header("Location") {
        println!("{step}: Location {location:?}");
    }
}

// ------------------------------------------------------- standing one case's child up

/// Stand the child up for one case: its own document directory, its own port, and the
/// `--connection` documents this case configures it with.
///
/// The `--key`, `--client` and `--resource-server` documents are the same for every case
/// here. Only the connection is varied, because the connection is what the resolution
/// order reads at every step except the last two.
fn stand_up(case: &str, connections: &[String]) -> (SocketAddr, Served) {
    let connection_paths: Vec<PathBuf> = connections
        .iter()
        .enumerate()
        .map(|(nth, body)| document(case, &format!("connection-{nth}.json"), body))
        .collect();
    let key_path = document(case, "key.json", AS_KEY_DOCUMENT);
    let client_path = document(case, "client.json", &client_document());
    let target_path = document(case, "resource-server.json", &resource_server_document());

    // Held from the probe's bind to the child's accept; see [`PORT`].
    let holding = PORT
        .lock()
        .unwrap_or_else(std::sync::PoisonError::into_inner);
    // A port nothing holds: bound to learn it, released before the child is told to take it.
    let address = {
        let probe = TcpListener::bind("127.0.0.1:0").expect("an ephemeral port on the loopback");
        probe.local_addr().expect("the bound address")
    };
    let mut served = Served::spawn(
        address,
        &connection_paths,
        &key_path,
        &client_path,
        &target_path,
    );
    served.listening(address);
    drop(holding);
    (address, served)
}

/// Serializes each case's **port selection and its child's bind**, and nothing else.
///
/// **Why a lock rather than a retry.** A case learns its port by binding an ephemeral one
/// and releasing it, then telling the child to take it. Between the release and the child's
/// bind the port belongs to nobody, and a second case probing inside that window is handed
/// the same one. The two children then race for it: one binds and one exits, and the
/// loser's [`Served::listening`] *succeeds* — against the winner's listener — so the loser
/// goes on to drive a deployment it did not configure, or, once the winner has been reaped,
/// finds nothing on the port at all.
///
/// Both halves of that were measured on this file's first parallel run: three of the eight
/// refusal cases failed with `Connection refused` inside [`exchange`] **after** `listening`
/// had returned, and the same eight run with `--test-threads=1` produced none. The
/// accepted case did not expose it because it was the only case in the lane.
///
/// **Every ephemeral bind in this file takes it**, and that is what makes it work rather
/// than merely look like it does. There are exactly two: the probe in [`stand_up`], and
/// [`issuer_publishing`]'s listener. Covering only the probe left the window open — every
/// case stands its issuer up first, so an issuer's bind could take a probe's just-released
/// port — and a lock held around one of two binds closes nothing. A third bind added to
/// this file without taking it would reopen the window, which is why there is one lock and
/// not a lock per call site.
///
/// Held across the window, the window is empty: every earlier case's child already holds
/// its own port when the next probe binds, so the kernel cannot hand that port out twice.
/// A poisoned lock is taken anyway — the data it guards is `()`, and a case that panicked
/// while holding it has already released its port with its child.
static PORT: Mutex<()> = Mutex::new(());

/// One proof, signed by `signer`, asserting `issuer` and `audience`.
///
/// The two claims the resolution order compares against the connection are parameters
/// because that is the whole of what the issuer and audience cases vary; the signer is a
/// parameter because the signature case varies that and nothing else.
fn proof_from(
    signer: &RealSigner<SystemClock>,
    issuer: &str,
    audience: &str,
    token_id: &str,
) -> String {
    signer
        .sign(
            &serde_json::Map::new(),
            &StandardClaims {
                issuer: Issuer::new(issuer),
                subject: PrincipalId::new(external_subject()),
                audience: Audience::new(audience),
                token_id: token_id.to_owned(),
            },
        )
        .expect("a signed proof")
        .token
}

/// `POST /v1/federation/login`, naming a connection and carrying a proof.
fn login_with(address: SocketAddr, connection_id: Uuid, proof: &str) -> Response {
    exchange(
        address,
        &post(
            "/v1/federation/login",
            "application/json",
            &format!(
                r#"{{"connection_id":"{connection_id}","proof":"{}"}}"#,
                encode_base64(proof.as_bytes())
            ),
            &[],
        ),
    )
}

/// Assert the status **and the whole body**, byte for byte.
///
/// The body is asserted entire rather than by its `error` member because the description
/// is the other half of what a caller reads, and because the whole-document form is what
/// fails when a refusal starts carrying a clause name: `ErrorBody::to_json` renders
/// exactly two members and an added one changes this string.
///
/// A case that read only the status would stay green if the binary refused **every** login
/// for one reason, which is the state it was in until `story:served-login-end-to-end`.
fn refused(step: &str, response: &Response, status: u16, body: &str) {
    answered(step, response);
    assert_eq!(
        response.status, status,
        "{step} answered {} {}",
        response.status, response.body
    );
    assert_eq!(
        response.body, body,
        "{step} answered the body {}",
        response.body
    );
}

/// The whole body a refused login carries: `Response::denied` renders this code and this
/// description, and `oauth::object` sorts the two members.
fn denied_body(code: &str) -> String {
    format!(r#"{{"error":"{code}","error_description":"the request was refused"}}"#)
}

/// The whole body a refused redemption carries. The description differs from
/// [`denied_body`]'s, which is the one thing distinguishing a refusal at the token
/// endpoint from a refusal at the login route by body alone.
fn grant_refused_body(code: &str) -> String {
    format!(r#"{{"error":"{code}","error_description":"the grant was refused"}}"#)
}

/// Kill the child, reap it, and assert **which refusal it took** — the lines it printed on
/// its own stderr — beside the connections it seeded.
///
/// # Why the status and the body are not enough, and neither is the seeding line
///
/// Five of the refusals below render the byte-identical body
/// `{"error":"access_denied","error_description":"the request was refused"}`, which is
/// RFC-correct: one `error_description` per denial, and the caller is not owed the cause.
/// The seeding line does not separate them either. An **expired proof on a fully
/// configured connection** reproduces status, body *and* the seeding line of the issuer
/// case, both signature cases and the algorithm case verbatim — a construction none of
/// them names. So did an absent link. A mutation collapsing those steps into one refusal
/// left every one of them green.
///
/// What separates them is the clause the child took, which it now records on its own
/// stderr, one line per refused request. That is a diagnosis an operator could not get
/// before and the wire still does not carry.
///
/// # Why `verification` is a separate argument
///
/// `DenialClause::ProofInvalid` is **one clause over twenty `RefusalReason`s** — a
/// malformed token, an unknown `kid`, a bad signature and an expired proof are all of them
/// (`crates/mandate-federation/src/verifier_real.rs`, `refused`). So the clause alone still
/// does not separate the two signature cases from each other or from an expired proof.
/// The reason the verifier itself refused for is recorded too, and a case that refuses at
/// the verifier names both.
///
/// `None` asserts the child recorded **no** verification refusal at all, which is what
/// makes it a discriminator rather than a label: a refusal that moved to the verifier
/// fails the case that says it does not happen there.
fn refusal_taken(
    served: &mut Served,
    command: &str,
    clause: &str,
    verification: Option<&str>,
    connections: &[Uuid],
) -> String {
    let (out, err) = served.output();
    println!("child stdout {out:?}");
    println!("child stderr {err:?}");
    for connection_id in connections {
        let line = format!("seeded federation connection {connection_id}");
        assert!(
            out.contains(&line),
            "the child seeds and prints every connection it was given; {line:?} is not in {out:?}"
        );
    }

    // Exactly one refusal, and it is this one. A count rather than a `contains` because a
    // road that refused twice for two reasons would satisfy `contains` for either.
    let refusals: Vec<&str> = err
        .lines()
        .filter(|line| line.contains(": refused "))
        .collect();
    assert_eq!(
        refusals,
        vec![format!("{CHILD}: refused {command} {clause}").as_str()],
        "the child records the one clause it refused under; stderr {err:?}"
    );

    let verifications: Vec<&str> = err
        .lines()
        .filter(|line| line.contains(": verification refused "))
        .collect();
    let expected: Vec<String> = verification
        .into_iter()
        .map(|reason| format!("{CHILD}: verification refused {reason}"))
        .collect();
    assert_eq!(
        verifications,
        expected.iter().map(String::as_str).collect::<Vec<&str>>(),
        "the child records the reason the verifier refused for, and only when it did; \
         stderr {err:?}"
    );
    out
}

/// Kill the child, reap it, and assert it recorded **no refusal at all**.
///
/// The other half of [`refusal_taken`]: an accepted login that quietly refused something on
/// the way would otherwise be indistinguishable from one that did not.
fn no_refusal_taken(served: &mut Served, connections: &[Uuid]) {
    let (out, err) = served.output();
    println!("child stdout {out:?}");
    println!("child stderr {err:?}");
    for connection_id in connections {
        let line = format!("seeded federation connection {connection_id}");
        assert!(
            out.contains(&line),
            "the child seeds and prints every connection it was given; {line:?} is not in {out:?}"
        );
    }
    let refusals: Vec<&str> = err
        .lines()
        .filter(|line| line.contains(": refused ") || line.contains(": verification refused "))
        .collect();
    assert!(
        refusals.is_empty(),
        "an accepted login records no refusal; stderr {err:?}"
    );
}

/// The prefix every line the binary prints carries.
const CHILD: &str = "mandate-control-plane";

/// The command the login route binds, as the child names it when it refuses.
const LOGIN: &str = "mandate.federation.AuthenticateFederation";

/// The command the token endpoint binds, as the child names it when it refuses.
const REDEEM: &str = "mandate.credential.RedeemAuthorizationCode";

// ----------------------------------------------------------------------- the acceptance

/// The acceptance of `story:served-login-end-to-end`: the spawned binary, configured through
/// four flag documents, completes one login against an issuer that really signed the proof.
#[test]
fn the_spawned_binary_completes_one_login_against_an_issuer_that_signed_the_proof() {
    let signer = idp_signer();
    let jwks = serde_json::to_string(&signer.published_keys()).expect("the published key set");
    let issuer = issuer_publishing(jwks);

    let (address, mut served) = stand_up(
        "accepted",
        &[ConnectionDocument::accepted(&issuer).rendered()],
    );

    // The proof, signed by the key the issuer publishes and by no other.
    let proof = proof_from(&signer, &issuer, IDP_CLIENT, "proof-1");

    // 1. The login opens a session, which means the child fetched the discovery document and
    //    the key set off the loopback issuer and verified the signature under them.
    let login = login_with(address, connection(), &proof);
    answered("step 1 POST /v1/federation/login", &login);
    assert_eq!(
        login.status, 200,
        "the login answered {} {}",
        login.status, login.body
    );
    assert!(
        !member(&login.body, "session_id").is_empty(),
        "the declared `session_id` response, got {}",
        login.body
    );
    let session_proof = member(&login.body, "session_proof");

    // 2. The authorization request yields a code, which needs the `--client` and
    //    `--resource-server` documents to have seeded a client and a target.
    let authorize = exchange(
        address,
        &get(
            &format!(
                "/oauth/authorize?response_type=code&client_id={}&redirect_uri={}\
                 &code_challenge={CHALLENGE}&code_challenge_method=S256&state=xyzzy\
                 &nonce=n-0S6&target={}&scope={}",
                client(),
                encoded(REDIRECT),
                resource_server(),
                encoded("read")
            ),
            &[("Authorization", &format!("Bearer {session_proof}"))],
        ),
    );
    answered("step 2 GET /oauth/authorize", &authorize);
    assert_eq!(
        authorize.status, 302,
        "RFC 6749 section 4.1.2 answers with a redirect; got {} {}",
        authorize.status, authorize.body
    );
    let location = authorize
        .header("Location")
        .expect("a Location header")
        .to_owned();
    assert!(
        location.starts_with(REDIRECT),
        "the redirect is the one the client document registered, got {location}"
    );
    assert!(
        location.contains("state=xyzzy"),
        "RFC 6749 section 4.1.2 returns the exact state received, got {location}"
    );
    let (_, query) = location
        .split_once('?')
        .expect("a redirect carrying a query component");
    let code = mandate_proto::oauth::decode_form(query)
        .expect("an x-www-form-urlencoded query")
        .get("code")
        .expect("a code parameter")
        .to_owned();

    // 3. The token endpoint issues the credential.
    let token = exchange(
        address,
        &post(
            "/oauth/token",
            "application/x-www-form-urlencoded",
            &format!(
                "grant_type=authorization_code&client_id={}&code={}&code_verifier={VERIFIER}\
                 &redirect_uri={}",
                client(),
                encoded(&code),
                encoded(REDIRECT)
            ),
            &[],
        ),
    );
    answered("step 3 POST /oauth/token", &token);
    assert_eq!(
        token.status, 200,
        "the token endpoint answered {} {}",
        token.status, token.body
    );
    assert_eq!(member(&token.body, "token_type"), "Bearer");
    let credential = member(&token.body, "access_token");

    // 4. Introspection answers active for the credential the road just issued.
    let introspect = exchange(
        address,
        &post(
            "/oauth/introspect",
            "application/x-www-form-urlencoded",
            &format!("token={}", encoded(&credential)),
            &[("Authorization", &format!("Bearer {credential}"))],
        ),
    );
    answered("step 4 POST /oauth/introspect", &introspect);
    assert_eq!(
        introspect.status, 200,
        "introspection answered {} {}",
        introspect.status, introspect.body
    );
    let document: serde_json::Value =
        serde_json::from_str(&introspect.body).expect("RFC 7662 section 2.2's JSON");
    assert_eq!(
        document.get("active").and_then(serde_json::Value::as_bool),
        Some(true),
        "the credential the road just issued is usable; got {}",
        introspect.body
    );

    // The child is killed and reaped here, and its stdout read once it is dead. An operator
    // who cannot learn these three identities cannot call the three routes that select on
    // them, which is why the binary prints each one.
    let (out, err) = served.output();
    println!("child stdout {out:?}");
    println!("child stderr {err:?}");
    for seeded in [
        format!("seeded federation connection {}", connection()),
        format!("seeded oauth client {}", client()),
        format!("seeded resource server {}", resource_server()),
    ] {
        assert!(
            out.contains(&seeded),
            "the child prints every identity it seeded; {seeded:?} is not in {out:?}"
        );
    }
}

// ------------------------------------------------------------------- the refusals
//
// `docs/architecture/federated-login.md` numbers **nine** steps. These cases drive the
// six that a request can be refused at — 1 select the trust relationship, 2 issuer, 3
// signature, 4 audience and client binding, 5 nonce/state/PKCE, 6 tenant claim, 7 resolve
// the external principal — plus the configuration gate that precedes all of them, and step
// 7's accepted side. Steps 8 and 9, establishing the organization context and issuing the
// session, have no refusal of their own: they are what the accepted case above asserts.
//
// An earlier revision of this comment claimed "one case per step of the resolution order"
// while step 7 had no case at all in either half. The claim is corrected rather than
// deleted, because what it should have said is what the file now does.
//
// Every one of these decisions was, before this file, reached only through
// `mandate_federation::verifier::ConstructedVerifier` in `tests/serve.rs` — a double that
// performs no cryptography, fetches nothing, and hands back the proof it was built with.
// The composition an operator deploys reaches them through `RealVerifier` over `UreqJwks`,
// and that is what is driven here.

/// Step 1, select the configured trust relationship: a `connection_id` nothing seeded.
#[test]
fn a_connection_nothing_seeded_is_refused_at_step_one() {
    let signer = idp_signer();
    let jwks = serde_json::to_string(&signer.published_keys()).expect("the published key set");
    let issuer = issuer_publishing(jwks);
    let (address, mut served) = stand_up(
        "unseeded-connection",
        &[ConnectionDocument::accepted(&issuer).rendered()],
    );

    // The accepted case's proof, unchanged and still valid. The only difference between
    // this request and the one that opens a session is the connection it names, so the
    // refusal cannot be attributed to the proof.
    let proof = proof_from(&signer, &issuer, IDP_CLIENT, "proof-connection");
    let login = login_with(address, unseeded_connection(), &proof);
    refused(
        "step 1 connection: POST /v1/federation/login",
        &login,
        400,
        &denied_body("access_denied"),
    );

    // Refused at step one and nowhere else: the clause is the connection's, and the child
    // records no verification refusal at all, because it never reached the verifier.
    let out = refusal_taken(
        &mut served,
        LOGIN,
        "ConnectionUnknown",
        None,
        &[connection()],
    );
    assert!(
        !out.contains(&format!(
            "seeded federation connection {}",
            unseeded_connection()
        )),
        "the connection this case names is seeded by no document; stdout {out:?}"
    );
}

/// Step 2, validate the issuer: the proof's `iss` is not the connection's.
#[test]
fn a_proof_whose_issuer_is_not_the_connections_is_refused_at_step_two() {
    let signer = idp_signer();
    let jwks = serde_json::to_string(&signer.published_keys()).expect("the published key set");
    let issuer = issuer_publishing(jwks);
    let (address, mut served) = stand_up(
        "issuer-mismatch",
        &[ConnectionDocument::accepted(&issuer).rendered()],
    );

    // Signed by the key the **connection's** issuer publishes, so the key set is fetched
    // and the signature verifies — `RealVerifier` resolves the `kid` against
    // `connection.issuer` and never against the proof's claim — and the proof is then
    // refused for the issuer it asserts.
    let proof = proof_from(&signer, FOREIGN_ISSUER, IDP_CLIENT, "proof-issuer");
    let login = login_with(address, connection(), &proof);
    refused(
        "step 2 issuer: POST /v1/federation/login",
        &login,
        400,
        &denied_body("access_denied"),
    );

    // The issuer is refused at the verifier, which compares the validated `iss` to the
    // connection's own — so both records name it, and neither names a signature failure.
    refusal_taken(
        &mut served,
        LOGIN,
        "IssuerMismatch",
        Some("IssuerMismatch"),
        &[connection()],
    );
}

/// Step 3, validate the signature: the issuer publishes a key set holding nothing.
#[test]
fn a_proof_whose_key_the_published_set_does_not_hold_is_refused_at_step_three() {
    let signer = idp_signer();
    // The discovery document is served as always; the key set it points at is empty, so
    // the `kid` the proof's header carries resolves to no key and no signature is checked
    // at all.
    let issuer = issuer_publishing(r#"{"keys":[]}"#.to_owned());
    let (address, mut served) = stand_up(
        "empty-key-set",
        &[ConnectionDocument::accepted(&issuer).rendered()],
    );

    let proof = proof_from(&signer, &issuer, IDP_CLIENT, "proof-empty-keys");
    let login = login_with(address, connection(), &proof);
    refused(
        "step 3 signature (empty key set): POST /v1/federation/login",
        &login,
        400,
        &denied_body("access_denied"),
    );

    // `ProofInvalid` is the clause for twenty different reasons, an expired proof among
    // them, so the clause alone would not say this case happened. `KeyIdUnknown` does: the
    // published set held no key under the `kid`, and no signature was checked.
    refusal_taken(
        &mut served,
        LOGIN,
        "ProofInvalid",
        Some("KeyIdUnknown"),
        &[connection()],
    );
}

/// Step 3, validate the signature: a proof signed by a key outside the published set.
#[test]
fn a_proof_signed_outside_the_published_key_set_is_refused_at_step_three() {
    let published = idp_signer();
    // A second key generated for this run, under the **same** `kid`. The `kid` has to
    // match, or the refusal would be the unknown-key one the case above already drives
    // and the signature itself would never be checked.
    let outside = idp_signer();
    let jwks = serde_json::to_string(&published.published_keys()).expect("the published key set");
    let other = serde_json::to_string(&outside.published_keys()).expect("the withheld key set");
    assert_ne!(
        jwks, other,
        "the two signers hold different keys, or this case drives no signature check"
    );

    let issuer = issuer_publishing(jwks);
    let (address, mut served) = stand_up(
        "foreign-signing-key",
        &[ConnectionDocument::accepted(&issuer).rendered()],
    );

    let proof = proof_from(&outside, &issuer, IDP_CLIENT, "proof-foreign-key");
    let login = login_with(address, connection(), &proof);
    refused(
        "step 3 signature (key outside the set): POST /v1/federation/login",
        &login,
        400,
        &denied_body("access_denied"),
    );

    // The same clause as the case above and a different reason, which is the whole point:
    // here the `kid` **did** resolve to a published key and the signature failed under it.
    // Nothing but the recorded reason separates these two cases from each other.
    refusal_taken(
        &mut served,
        LOGIN,
        "ProofInvalid",
        Some("SignatureInvalid"),
        &[connection()],
    );
}

/// Step 4, validate the audience and client binding: the proof's `aud` is not the
/// connection's `client_id`.
#[test]
fn a_proof_whose_audience_is_not_the_connections_client_is_refused_at_step_four() {
    let signer = idp_signer();
    let jwks = serde_json::to_string(&signer.published_keys()).expect("the published key set");
    let issuer = issuer_publishing(jwks);
    let (address, mut served) = stand_up(
        "audience-mismatch",
        &[ConnectionDocument::accepted(&issuer).rendered()],
    );

    let proof = proof_from(&signer, &issuer, FOREIGN_CLIENT, "proof-audience");
    let login = login_with(address, connection(), &proof);
    // `invalid_scope`, not `access_denied`: `DenialReason::AudienceMismatch` is the one
    // reason on this road that does not map to the by-reason default
    // (`crates/mandate-proto/src/oauth.rs`, `code_for_reason`). A case asserting only
    // `400` would not have seen that, and a case asserting only `access_denied` would
    // have been wrong.
    refused(
        "step 4 audience: POST /v1/federation/login",
        &login,
        400,
        &denied_body("invalid_scope"),
    );

    refusal_taken(
        &mut served,
        LOGIN,
        "AudienceBinding",
        Some("AudienceMismatch"),
        &[connection()],
    );
}

/// Step 5, validate nonce, state and PKCE: a code verifier that does not digest to the
/// recorded challenge.
///
/// The only refusal of the seven that is not answered by the login route. PKCE is redeemed
/// at the token endpoint, so the case walks the accepted road as far as the code and then
/// presents the wrong verifier for it.
#[test]
fn a_code_verifier_that_does_not_match_the_challenge_is_refused_at_step_five() {
    let signer = idp_signer();
    let jwks = serde_json::to_string(&signer.published_keys()).expect("the published key set");
    let issuer = issuer_publishing(jwks);
    let (address, mut served) = stand_up(
        "pkce-mismatch",
        &[ConnectionDocument::accepted(&issuer).rendered()],
    );

    let proof = proof_from(&signer, &issuer, IDP_CLIENT, "proof-pkce");
    let login = login_with(address, connection(), &proof);
    answered("step 5 pkce: POST /v1/federation/login", &login);
    assert_eq!(
        login.status, 200,
        "the login this case builds on is the accepted one; got {} {}",
        login.status, login.body
    );
    let session_proof = member(&login.body, "session_proof");

    let authorize = exchange(
        address,
        &get(
            &format!(
                "/oauth/authorize?response_type=code&client_id={}&redirect_uri={}\
                 &code_challenge={CHALLENGE}&code_challenge_method=S256&state=xyzzy\
                 &nonce=n-0S6&target={}&scope={}",
                client(),
                encoded(REDIRECT),
                resource_server(),
                encoded("read")
            ),
            &[("Authorization", &format!("Bearer {session_proof}"))],
        ),
    );
    answered("step 5 pkce: GET /oauth/authorize", &authorize);
    assert_eq!(
        authorize.status, 302,
        "the authorization this case builds on is the accepted one; got {} {}",
        authorize.status, authorize.body
    );
    let location = authorize
        .header("Location")
        .expect("a Location header")
        .to_owned();
    let (_, query) = location
        .split_once('?')
        .expect("a redirect carrying a query component");
    let code = mandate_proto::oauth::decode_form(query)
        .expect("an x-www-form-urlencoded query")
        .get("code")
        .expect("a code parameter")
        .to_owned();

    // The code the authorization just issued, presented with a verifier that is not the
    // one its challenge was derived from.
    let token = exchange(
        address,
        &post(
            "/oauth/token",
            "application/x-www-form-urlencoded",
            &format!(
                "grant_type=authorization_code&client_id={}&code={}\
                 &code_verifier={MISMATCHED_VERIFIER}&redirect_uri={}",
                client(),
                encoded(&code),
                encoded(REDIRECT)
            ),
            &[],
        ),
    );
    refused(
        "step 5 pkce: POST /oauth/token",
        &token,
        400,
        &grant_refused_body("invalid_grant"),
    );

    // `invalid_grant` is the token endpoint's answer for an expired code, a consumed code,
    // a redirect that does not match and a client that is not the code's, so the body is no
    // more discriminating here than at the login route. The clause is: the presented
    // verifier did not digest to the recorded challenge. The login that got this far
    // refused nothing, so the record names one refusal and it is the redemption's.
    refusal_taken(
        &mut served,
        REDEEM,
        "VerifierMismatch",
        None,
        &[connection()],
    );
}

/// Step 6, validate the configured organization: resolution would be **ambiguous**, and the
/// configuration is refused before a socket rather than every login through it.
///
/// The promise `docs/architecture/federated-login.md` makes on its own — *if tenant
/// resolution is ambiguous, Mandate denies rather than guesses*
/// (`architecture-addendum.md:360`) — is now kept one step earlier than this case used to
/// keep it. `mandate.federation.RegisterFederationConnection` refuses a rule another
/// organization's connection on the same issuer could match for the same proof, and its own
/// comment says why (`crates/mandate-federation/src/record.rs:946-949`): "no command
/// un-registers a connection, so the incumbent could not undo it. Refuse the configuration
/// rather than the logins." Every `--connection` document is run through that command, so
/// this pair never stands a listener up — which is the point: the deployment this case used
/// to build denied the *first* connection's login too, and that login succeeds when its
/// document is the only one given.
///
/// **The login-time clause is not gone and is not covered here.**
/// `DenialClause::TenantAmbiguous` is still reached by a deployment whose folds came from an
/// event log rather than from these flags: `Deployment::record_federation` is the replay
/// path and enforces no command guard, and `register_federation_connection` is a
/// read-then-write guard whose own comment records that storage must enforce it atomically.
/// That case is
/// `tests/serve.rs::two_connections_on_one_issuer_from_a_log_are_still_refused_as_ambiguous`.
///
/// No port is taken and no `PORT` lock is held: the child exits before it binds.
#[test]
fn an_ambiguous_tenant_resolution_is_refused_as_a_configuration_before_the_socket() {
    let signer = idp_signer();
    let jwks = serde_json::to_string(&signer.published_keys()).expect("the published key set");
    let issuer = issuer_publishing(jwks);

    let selected = ConnectionDocument::accepted(&issuer);
    let sibling = ConnectionDocument {
        connection_id: other_connection(),
        organization: other_organization(),
        // No link: the configuration is refused before any login, so a link on the sibling
        // would decide nothing and would assert a principal this case does not need.
        linked: false,
        ..ConnectionDocument::accepted(&issuer)
    };
    let case = "tenant-ambiguous";
    let paths: Vec<PathBuf> = [selected.rendered(), sibling.rendered()]
        .iter()
        .enumerate()
        .map(|(nth, body)| document(case, &format!("connection-{nth}.json"), body))
        .collect();
    let key_path = document(case, "key.json", AS_KEY_DOCUMENT);

    let refused = Command::new(env!("CARGO_BIN_EXE_mandate-control-plane"))
        .args([
            "serve",
            "--listen",
            "127.0.0.1:0",
            "--issuer",
            AS_ISSUER,
            "--connection",
            stated(&paths[0]),
            "--connection",
            stated(&paths[1]),
            "--key",
            stated(&key_path),
        ])
        .output()
        .expect("the composition binary runs");

    assert_eq!(
        refused.status.code(),
        Some(2),
        "a configuration whose logins would all be ambiguous is the operator's to correct; \
         it said {}",
        String::from_utf8_lossy(&refused.stderr)
    );
    let said = String::from_utf8_lossy(&refused.stderr);
    assert!(
        said.contains("TenantResolutionUnadmitted"),
        "the clause the registration command states for this pair, got {said}"
    );
    assert!(
        said.contains(stated(&paths[1])),
        "the refusal names the document it could not admit, got {said}"
    );
}

/// The configuration step: a `--connection` document omitting `algorithm`.
///
/// `RealVerifier` refuses to have a default at all — `jsonwebtoken`'s own would be `HS256`
/// — and a connection no algorithm was configured for verifies nothing
/// (`RefusalReason::ConnectionAlgorithmUnconfigured`). The proof this case presents is the
/// one the accepted case's connection admits, so a deployment that defaulted to the
/// signed-with algorithm would answer `200` here.
#[test]
fn a_connection_configured_for_no_algorithm_refuses_rather_than_defaulting() {
    let signer = idp_signer();
    let jwks = serde_json::to_string(&signer.published_keys()).expect("the published key set");
    let issuer = issuer_publishing(jwks);

    let unconfigured = ConnectionDocument {
        algorithm: None,
        ..ConnectionDocument::accepted(&issuer)
    };
    let (address, mut served) = stand_up("no-algorithm", &[unconfigured.rendered()]);

    let proof = proof_from(&signer, &issuer, IDP_CLIENT, "proof-algorithm");
    let login = login_with(address, connection(), &proof);
    refused(
        "configuration (no algorithm): POST /v1/federation/login",
        &login,
        400,
        &denied_body("access_denied"),
    );

    // The child bound its listener and seeded the connection, so the document was read and
    // accepted: this is a login refused at the verifier, not a configuration the binary
    // rejected at startup — which would have been an exit status and no response at all.
    // `AlgorithmPolicy` is the clause and the absent configuration is the reason, which is
    // what an expired proof on this same connection would not produce.
    refusal_taken(
        &mut served,
        LOGIN,
        "AlgorithmPolicy",
        Some("ConnectionAlgorithmUnconfigured"),
        &[connection()],
    );
}

/// Step 7, resolve the external principal: a proof this connection has no link for, on a
/// connection that does not admit provisioning.
///
/// `federation.yaml:4` gives `jit_provisioning` one meaning — a connection that does not
/// admit provisioning "denies the first login and creates nothing" — and
/// `Deployment::authenticate` reads the flag only after the login has already refused
/// `LinkAbsent`. Every earlier step passes here: the proof is the accepted one.
#[test]
fn a_first_login_a_connection_does_not_admit_provisioning_for_is_refused_at_step_seven() {
    let signer = idp_signer();
    let jwks = serde_json::to_string(&signer.published_keys()).expect("the published key set");
    let issuer = issuer_publishing(jwks);

    let unlinked = ConnectionDocument {
        linked: false,
        jit_provisioning: false,
        ..ConnectionDocument::accepted(&issuer)
    };
    let (address, mut served) = stand_up("link-absent", &[unlinked.rendered()]);

    let proof = proof_from(&signer, &issuer, IDP_CLIENT, "proof-link-absent");
    let login = login_with(address, connection(), &proof);
    refused(
        "step 7 link: POST /v1/federation/login",
        &login,
        400,
        &denied_body("access_denied"),
    );

    // The verifier refused nothing — the proof is valid and every step before this one
    // passed — so the record names the link and only the link.
    refusal_taken(&mut served, LOGIN, "LinkAbsent", None, &[connection()]);
}

/// Step 7 again, on the accepted side: the same first login, on a connection that **does**
/// admit provisioning, creates the principal and opens a session.
///
/// The two cases differ in one Boolean of one document. That is what makes the refusal
/// above a property of `jit_provisioning` rather than of anything else in the
/// configuration, and it is the only assertion in this file that the composition
/// `Deployment::authenticate` performs — authenticate, provision, authenticate again —
/// runs in the served binary at all.
#[test]
fn a_first_login_a_connection_admits_provisioning_for_opens_a_session_at_step_seven() {
    let signer = idp_signer();
    let jwks = serde_json::to_string(&signer.published_keys()).expect("the published key set");
    let issuer = issuer_publishing(jwks);

    let provisioning = ConnectionDocument {
        linked: false,
        jit_provisioning: true,
        ..ConnectionDocument::accepted(&issuer)
    };
    let (address, mut served) = stand_up("jit-login", &[provisioning.rendered()]);

    let proof = proof_from(&signer, &issuer, IDP_CLIENT, "proof-jit");
    let login = login_with(address, connection(), &proof);
    answered("step 7 jit: POST /v1/federation/login", &login);
    assert_eq!(
        login.status, 200,
        "a connection that admits provisioning opens the first login's session; got {} {}",
        login.status, login.body
    );
    assert!(
        !member(&login.body, "session_id").is_empty(),
        "the declared `session_id` response, got {}",
        login.body
    );
    // The principal is the one provisioning created, not the one the accepted case's
    // document names: no link was seeded, so this identity was minted by the child.
    assert_ne!(
        member(&login.body, "principal_id"),
        principal().to_string(),
        "a provisioned principal is not the seeded one; got {}",
        login.body
    );
    assert_eq!(
        member(&login.body, "organization_id"),
        organization().to_string(),
        "the session is opened in the connection's organization; got {}",
        login.body
    );

    // Nothing was refused on the way. The composition refuses `LinkAbsent` internally on
    // its first attempt and retries; that refusal is never rendered, so the child records
    // none — which is what distinguishes this from the case above.
    no_refusal_taken(&mut served, &[connection()]);
}
