//! The contract's Rust shapes, emitted from the compiled model.
//!
//! ESS 0.26.0 realizes Rust for type roots only, so the three kinds a Mandate reader actually
//! holds — the event payload, the command input and response, the entity record — have no
//! generated shape and nothing binds a hand-written one to its declaration. This module emits
//! them, deterministically, from `generated/ir/system.json`: the same bytes `cargo xtask
//! contracts` byte-compares, so a shape that drifts from its declaration is a failing gate.
//!
//! The emission is a pure function of those bytes. There is no clock in it, no environment and
//! no hash-order iteration — every index is walked through a `BTreeMap` — because the whole
//! value of the byte-compare is that a second emission of the same model is the same file.
//!
//! # What ESS 0.26.0's own realizer does differently
//!
//! `ess generate types --target rust` reads a JSON Schema, not the compiled model, and its
//! output is not this output renamed. At tag 0.26.0
//! (`crates/generate/schema-contract/src/realize/rust.rs`) it:
//!
//! - admits **type roots only**, which is why the three kinds above are emitted here at all;
//! - writes **one file**, `types.rs`, with its own `Cargo.toml` on edition 2021, against this
//!   emitter's four modules inside the workspace;
//! - names every enum variant **positionally** — `V0`, `V1`, … carrying `#[serde(rename)]` —
//!   where this emitter uses the declared variant name, so an ESS-realized enum is a different
//!   Rust API for the same wire values;
//! - encodes a union as `#[serde(untagged)]` with a hand-written `Deserialize` that takes the
//!   **first structurally decodable** alternative, where this emitter encodes the union
//!   adjacently, under the tag the IR declares. The content key is not declared anywhere: the
//!   IR's union body carries a tag and nothing else, and `value` is this emitter's own
//!   literal, chosen because ESS's JSON Schema projection spells every branch as an object of
//!   exactly `{<tag>, value}`. If that projection ever spells it differently, this literal is
//!   the line that has to move;
//! - carries absence as `EssPresence<T>`, whose `Deserialize` delegates straight to `T` — so
//!   `null` is refused only when `T` happens to refuse it, where [`PRESENCE`] refuses `null`
//!   itself, in every position, by name;
//! - stamps `// @generated by ESS <version>` and a source digest rather than this header.
//!
//! Its `EssPresence::Absent` does refuse to serialize, and this emitter follows it exactly.
//!
//! # Retirement
//!
//! Retiring this emitter is not a promise that ESS will one day write these bytes: the two
//! outputs differ in the API they present, and the paragraph above is the list. It is a
//! measurement — when the realizer admits events, commands and entities, emit both and
//! byte-compare the realizer's output against this one, and let the diff decide what is a
//! Mandate decision worth keeping and what was only this emitter's habit. Until that diff has
//! been read, nothing here may be deleted on the assumption that ESS agrees.

use serde_json::{Map, Value};
use sha2::{Digest, Sha256};
use std::{
    collections::{BTreeMap, BTreeSet},
    fmt::Write as _,
    fs,
    path::Path,
};

type Result<T> = std::result::Result<T, Box<dyn std::error::Error>>;

/// The derive every emitted declaration carries.
///
/// `::serde` is absolute so the emitted file is correct in any module it is included from, and
/// `PartialEq` is here because a round-trip that cannot be compared proves nothing.
const DERIVE: &str =
    "#[derive(Clone, Debug, PartialEq, ::serde::Deserialize, ::serde::Serialize)]\n";

/// Credential material: the two declarations no durable record may carry.
///
/// A command input is the message that carries a credential to be verified, so it may name
/// them. An event is the record and an entity is the projection of it, and `AGENTS.md` states
/// the obligation directly: raw credentials never enter logs, audit records, fixtures or
/// persistent domain records. A generated shape that admitted one would make that obligation
/// unenforceable by construction, so the emitter refuses instead of emitting it.
const FORBIDDEN: [&str; 2] = [
    "mandate.core.CredentialSecret",
    "mandate.core.CredentialProof",
];

/// Where the emission lands under the generated root, and what the crate's `#[path]` reads.
const DIRECTORY: &str = "rust/mandate-contract/src";

/// Every word edition 2024 will not accept as a plain field or variant name.
///
/// The strict keywords, then the reserved ones — `abstract`, `become`, `box`, `do`, `final`,
/// `macro`, `override`, `priv`, `try`, `typeof`, `unsized`, `virtual`, `yield` and `gen` — which
/// `rustc --edition 2024` rejects with `expected identifier, found reserved keyword` exactly as
/// it rejects a strict one. A declaration that names one is refused rather than escaped: `r#`
/// would make the Rust name and the declared name differ silently, and `self`, `Self`, `super`
/// and `crate` cannot be raw identifiers at all, so escaping could not be a general answer
/// even if it were a wanted one.
const KEYWORDS: [&str; 52] = [
    "Self", "abstract", "as", "async", "await", "become", "box", "break", "const", "continue",
    "crate", "do", "dyn", "else", "enum", "extern", "false", "final", "fn", "for", "gen", "if",
    "impl", "in", "let", "loop", "macro", "match", "mod", "move", "mut", "override", "priv", "pub",
    "ref", "return", "self", "static", "struct", "super", "trait", "true", "try", "type", "typeof",
    "unsafe", "unsized", "use", "virtual", "where", "while", "yield",
];

/// The `Presence` carrier, declared once in `types.rs` and shared through `super::types`.
///
/// This is the one hand-written shape in the emission, and it is here rather than in the crate
/// because the crate holds no hand-written shape at all: everything the crate compiles comes
/// out of this emitter and is byte-compared by the gate.
const PRESENCE: &str = r#"/// A declared-optional value: the key carries a value, or the key is not there.
///
/// ESS `optional` means the key may be absent from the object. It does not admit `null`, and
/// `Option<T>` does: serde accepts both a missing key and an explicit `null` for an `Option`,
/// so a shape built on it would answer for a document the contract refuses. `Presence` keeps
/// the two apart, and it keeps them apart in both directions.
///
/// Absence is a property of a *key*, not a value, so it has no JSON spelling of its own.
/// Serializing an `Absent` outside a field that skips it is therefore an error rather than a
/// `null`: a carrier that wrote `null` there would emit a document it then refuses to read
/// back, and `null` is not what the contract's JSON Schema projection admits either.
#[derive(Clone, Debug, Default, PartialEq)]
pub enum Presence<T> {
    /// The key is not in the object.
    #[default]
    Absent,
    /// The key is in the object and carries a declared value.
    Present(T),
}

impl<T> Presence<T> {
    /// Whether the key is absent: the `skip_serializing_if` of every optional field.
    pub fn is_absent(&self) -> bool {
        matches!(self, Presence::Absent)
    }
}

impl<T> ::serde::Serialize for Presence<T>
where
    T: ::serde::Serialize,
{
    fn serialize<S>(&self, serializer: S) -> ::std::result::Result<S::Ok, S::Error>
    where
        S: ::serde::Serializer,
    {
        match self {
            Presence::Absent => Err(::serde::ser::Error::custom(
                "Presence::Absent has no JSON spelling outside a skipping field; omit the key",
            )),
            Presence::Present(value) => value.serialize(serializer),
        }
    }
}

impl<'de, T> ::serde::Deserialize<'de> for Presence<T>
where
    T: ::serde::Deserialize<'de>,
{
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        struct Declared<T>(::std::marker::PhantomData<T>);

        impl<'de, T> ::serde::de::Visitor<'de> for Declared<T>
        where
            T: ::serde::Deserialize<'de>,
        {
            type Value = Presence<T>;

            fn expecting(&self, formatter: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
                formatter.write_str("a declared value, or no key at all")
            }

            fn visit_some<D>(self, deserializer: D) -> ::std::result::Result<Self::Value, D::Error>
            where
                D: ::serde::Deserializer<'de>,
            {
                T::deserialize(deserializer).map(Presence::Present)
            }

            fn visit_none<E>(self) -> ::std::result::Result<Self::Value, E>
            where
                E: ::serde::de::Error,
            {
                Err(E::custom("null is not absence: omit the key instead"))
            }

            fn visit_unit<E>(self) -> ::std::result::Result<Self::Value, E>
            where
                E: ::serde::de::Error,
            {
                Err(E::custom("null is not absence: omit the key instead"))
            }
        }

        deserializer.deserialize_option(Declared(::std::marker::PhantomData))
    }
}
"#;

/// The four files, and where a declared name is reachable from.
#[derive(Clone, Copy, PartialEq, Eq)]
enum Module {
    Types,
    Entities,
    Commands,
    Events,
}

impl Module {
    const fn file(self) -> &'static str {
        match self {
            Module::Types => "types.rs",
            Module::Entities => "entities.rs",
            Module::Commands => "commands.rs",
            Module::Events => "events.rs",
        }
    }

    const fn name(self) -> &'static str {
        match self {
            Module::Types => "types",
            Module::Entities => "entities",
            Module::Commands => "commands",
            Module::Events => "events",
        }
    }

    const fn documentation(self) -> &'static str {
        match self {
            Module::Types => concat!(
                "//! The declared types the other three kinds are built from: newtypes, enums,\n",
                "//! structs and unions, and the `Presence` carrier every optional field uses.\n",
                "//!\n",
                "//! An entity's lifecycle state enum is declared beside its entity in\n",
                "//! `entities.rs`, so every declaration the contract makes is emitted once.\n",
            ),
            Module::Entities => concat!(
                "//! The entity records: the declared identity, the declared fields and the\n",
                "//! lifecycle state, each beside the enum of the states its declaration admits.\n",
                "//!\n",
                "//! An entity is a projection of the event record and may not carry credential\n",
                "//! material; the emitter refuses to write one that reaches it.\n",
            ),
            Module::Commands => concat!(
                "//! The command messages: one input per declared command, one response for each\n",
                "//! command that declares one, and the refusal payloads the outcomes name.\n",
                "//!\n",
                "//! A command input is the message that carries a credential to be verified, so\n",
                "//! this is the one kind whose shapes may name credential material.\n",
            ),
            Module::Events => concat!(
                "//! The event payloads: one record per declared event.\n",
                "//!\n",
                "//! The event is the durable record and may not carry credential material; the\n",
                "//! emitter refuses to write one that reaches it.\n",
            ),
        }
    }
}

/// Every part of a dotted declaration path, capitalised and joined.
///
/// This reproduces ESS 0.26.0's own `declaration_name`
/// (`crates/generate/schema-contract/src/realize.rs`), so a shape this emitter writes carries
/// the name ESS will write when its Rust target admits these kinds.
/// `mandate.federation.FederationAuthenticated` becomes
/// `MandateFederationFederationAuthenticated`, and only the first letter of a part is touched.
///
/// The rule is not injective — `mandate.core.Space_Id` and `mandate.core.SpaceId` both reach
/// `MandateCoreSpaceId` — so [`Emitter::rust_names`] reproduces ESS's `name_collision` guard
/// beside it rather than the rule alone.
pub fn declaration_name(source: &str) -> String {
    let mut result = String::new();
    for part in source
        .split(|c: char| !c.is_ascii_alphanumeric())
        .filter(|part| !part.is_empty())
    {
        let mut characters = part.chars();
        if let Some(first) = characters.next() {
            result.push(first.to_ascii_uppercase());
            result.push_str(characters.as_str());
        }
    }
    result
}

/// The digest of the model the emission was read from, as it appears in every header line.
pub fn digest(model: &[u8]) -> String {
    format!("{:x}", Sha256::digest(model))
}

/// The four emitted files, by file name, from the bytes of a compiled model.
pub fn render(model: &[u8]) -> Result<BTreeMap<String, String>> {
    let parsed: Value = serde_json::from_slice(model)?;
    Emitter::new(&parsed)?.files(&digest(model))
}

/// Read `<root>/ir/system.json` and write the emission under `<root>/rust/mandate-contract`.
pub fn emit(root: &Path) -> Result<()> {
    let model = fs::read(root.join("ir/system.json"))?;
    let files = render(&model)?;
    let directory = root.join(DIRECTORY);
    fs::create_dir_all(&directory)?;
    for (name, body) in &files {
        fs::write(directory.join(name), body)?;
    }
    Ok(())
}

/// One declared type expression, and where in the model it sits.
///
/// A named record rather than a tuple because the fourth element is the one that carries a
/// rule: `outside` is what separates a record key, where an optional is admitted, from every
/// other position, where it is refused.
struct Position<'a> {
    /// The declaration that carries the expression.
    declared: String,
    /// The field, the variant label, or what a newtype wraps.
    at: String,
    /// The expression itself.
    type_ref: &'a Value,
    /// `None` at a record key; otherwise what a refusal says the optional was found in.
    outside: Option<&'static str>,
}

struct Emitter<'a> {
    model: &'a Value,
    /// The entity lifecycle state types, which `entities.rs` owns rather than `types.rs`.
    states: BTreeSet<String>,
    /// Every declared type's own declared references, in declaration order.
    references: BTreeMap<String, Vec<String>>,
}

impl<'a> Emitter<'a> {
    /// Index the model, and refuse here everything that can be refused before any text.
    ///
    /// Not every check is here. The credential walk, the identifier checks and the primitive
    /// and type-expression mapping are reached while a file is being written, because each of
    /// them needs the declaration the renderer is in the middle of. What holds regardless is
    /// that `render` is all-or-nothing: [`Emitter::files`] evaluates all four files before
    /// [`emit`] writes any of them, so a refusal from the middle of `entities.rs` leaves no
    /// half-written emission on disk for somebody's editor to open.
    fn new(model: &'a Value) -> Result<Self> {
        let types = index(model, "types")?;
        let mut states = BTreeSet::new();
        for (name, entity) in index(model, "entities")? {
            let state = entity["state_type"].as_str().ok_or("entity state type")?;
            if !types.contains_key(state) {
                return Err(format!("{name} names an undeclared state type {state}").into());
            }
            states.insert(state.to_owned());
        }
        let mut references = BTreeMap::new();
        for (name, declared) in types {
            let body = &declared["body"];
            let mut reached = Vec::new();
            match body["kind"].as_str().ok_or("type body kind")? {
                "newtype" => declared_names(&body["of"], &mut reached),
                "enum" => {}
                "struct" => {
                    for field in array(body, "fields")? {
                        declared_names(&field["type_ref"], &mut reached);
                    }
                }
                "union" => {
                    for variant in object(body, "variants")?.values() {
                        declared_names(variant, &mut reached);
                    }
                }
                other => return Err(format!("unmapped type body: {other} in {name}").into()),
            }
            references.insert(name.clone(), reached);
        }
        let emitter = Self {
            model,
            states,
            references,
        };
        emitter.resolve()?;
        emitter.rust_names()?;
        emitter.lifecycles()?;
        Ok(emitter)
    }

    /// Every type expression the model carries, with the declaration and position it sits in.
    ///
    /// One enumeration, so a check written against it holds for every kind rather than for the
    /// kind whose case was written first.
    /// Where a position sits, for the one rule that depends on it: an `optional` is a record
    /// key or it is refused. `None` is a record key; `Some(context)` is everywhere else, and
    /// the context is what the refusal says the optional was found in.
    fn positions(&self) -> Result<Vec<Position<'a>>> {
        let mut out = Vec::new();
        for (name, declared) in index(self.model, "types")? {
            let body = &declared["body"];
            match body["kind"].as_str().ok_or("type body kind")? {
                "newtype" => out.push(Position {
                    declared: name.clone(),
                    at: "the value it wraps".to_owned(),
                    type_ref: &body["of"],
                    outside: Some("as the value a newtype wraps"),
                }),
                "enum" => {}
                "struct" => {
                    for field in array(body, "fields")? {
                        out.push(Position {
                            declared: name.clone(),
                            at: field["name"].as_str().ok_or("field name")?.to_owned(),
                            type_ref: &field["type_ref"],
                            outside: None,
                        });
                    }
                }
                "union" => {
                    for (label, variant) in object(body, "variants")? {
                        out.push(Position {
                            declared: name.clone(),
                            at: label.clone(),
                            type_ref: variant,
                            outside: Some("as a union variant"),
                        });
                    }
                }
                other => return Err(format!("unmapped type body: {other} in {name}").into()),
            }
        }
        for (name, entity) in index(self.model, "entities")? {
            let identity = &entity["identity"];
            out.push(Position {
                declared: name.clone(),
                at: identity["name"].as_str().ok_or("identity name")?.to_owned(),
                type_ref: &identity["type_ref"],
                outside: None,
            });
            for field in array(entity, "fields")? {
                out.push(Position {
                    declared: name.clone(),
                    at: field["name"].as_str().ok_or("field name")?.to_owned(),
                    type_ref: &field["type_ref"],
                    outside: None,
                });
            }
        }
        for kind in ["events", "errors"] {
            for (name, declared) in index(self.model, kind)? {
                for field in array(declared, "fields")? {
                    out.push(Position {
                        declared: name.clone(),
                        at: field["name"].as_str().ok_or("field name")?.to_owned(),
                        type_ref: &field["type_ref"],
                        outside: None,
                    });
                }
            }
        }
        for (name, command) in index(self.model, "commands")? {
            for key in ["input", "response"] {
                if command.get(key).is_none() {
                    continue;
                }
                for field in array(command, key)? {
                    out.push(Position {
                        declared: name.clone(),
                        at: field["name"].as_str().ok_or("field name")?.to_owned(),
                        type_ref: &field["type_ref"],
                        outside: None,
                    });
                }
            }
        }
        Ok(out)
    }

    /// Every declared reference names a declared type, and no optional sits inside a list.
    ///
    /// A reference to nothing is the one failure that must never be a pass: it would read as
    /// "this declaration carries no credential material" to the walk below and as a plausible
    /// Rust path to the compiler, and the compiler's answer would name a generated file rather
    /// than the declaration that caused it.
    fn resolve(&self) -> Result<()> {
        let types = index(self.model, "types")?;
        for position in self.positions()? {
            let Position {
                declared,
                at,
                type_ref,
                outside,
            } = position;
            let mut named = Vec::new();
            declared_names(type_ref, &mut named);
            for name in named {
                if !types.contains_key(&name) {
                    return Err(format!(
                        "{declared} at {at:?} names {name}, which the model does not declare"
                    )
                    .into());
                }
            }
            optional_position(type_ref, &declared, &at, outside)?;
        }
        Ok(())
    }

    /// No two declarations become one Rust name.
    ///
    /// [`declaration_name`] drops every character Rust cannot take, so two declared names can
    /// reach one Rust name. ESS refuses that itself (`name_collision`), and an emitter that
    /// reproduced the rule without the guard would answer a collision with two declarations of
    /// one name in one module — which the compiler reports against the generated file, or, if
    /// they land in different modules, does not report at all.
    fn rust_names(&self) -> Result<()> {
        let mut taken: BTreeMap<String, String> =
            BTreeMap::from([("Presence".to_owned(), "the Presence carrier".to_owned())]);
        let mut claim = |rust: String, declared: &str| -> Result<()> {
            if let Some(previous) = taken.insert(rust.clone(), declared.to_owned()) {
                return Err(
                    format!("{previous} and {declared} both become the Rust name {rust}").into(),
                );
            }
            Ok(())
        };
        for kind in ["types", "entities", "events", "errors"] {
            for name in index(self.model, kind)?.keys() {
                claim(declaration_name(name), name)?;
            }
        }
        for (name, command) in index(self.model, "commands")? {
            claim(format!("{}Input", declaration_name(name)), name)?;
            if command.get("response").is_some() {
                claim(format!("{}Response", declaration_name(name)), name)?;
            }
        }
        Ok(())
    }

    /// Every entity has a lifecycle to be in, and room for the identity and state it is given.
    fn lifecycles(&self) -> Result<()> {
        let types = index(self.model, "types")?;
        for (name, entity) in index(self.model, "entities")? {
            let states = array(&entity["lifecycle"], "states")?;
            if states.is_empty() {
                return Err(format!(
                    "{name} declares no lifecycle state; a record no value can inhabit is not a shape"
                )
                .into());
            }
            let state = entity["state_type"].as_str().ok_or("entity state type")?;
            if array(&types[state]["body"], "variants")? != states {
                return Err(
                    format!("{name}'s state type does not carry its lifecycle states").into(),
                );
            }
            let identity = entity["identity"]["name"].as_str().ok_or("identity name")?;
            for field in array(entity, "fields")? {
                let field = field["name"].as_str().ok_or("field name")?;
                if field == identity || field == "state" {
                    return Err(format!(
                        "{name} declares a field named {field:?}, which the emitted record \
                         already carries as its identity or its lifecycle state"
                    )
                    .into());
                }
            }
        }
        Ok(())
    }

    fn files(&self, digest: &str) -> Result<BTreeMap<String, String>> {
        let mut files = BTreeMap::new();
        for (module, blocks) in [
            (Module::Types, self.types()?),
            (Module::Entities, self.entities()?),
            (Module::Commands, self.commands()?),
            (Module::Events, self.events()?),
        ] {
            let header = format!(
                "// Generated by cargo xtask generate from ir/system.json (sha256 {digest}) \
                 with ess 0.26.0. Do not edit.\n"
            );
            let body = format!("{header}{}\n{}", module.documentation(), blocks.join("\n"));
            files.insert(module.file().to_owned(), body);
        }
        Ok(files)
    }

    fn types(&self) -> Result<Vec<String>> {
        let mut blocks = vec![PRESENCE.to_owned()];
        for (name, declared) in index(self.model, "types")? {
            if self.states.contains(name) {
                continue;
            }
            blocks.push(self.declared_type(name, &declared["body"])?);
        }
        Ok(blocks)
    }

    fn declared_type(&self, name: &str, body: &Value) -> Result<String> {
        let mut out = String::new();
        match body["kind"].as_str().ok_or("type body kind")? {
            "newtype" => {
                writeln!(
                    out,
                    "/// `{name}` — newtype over `{}`.",
                    describe(&body["of"], name, "the value it wraps")?
                )?;
                out.push_str(DERIVE);
                out.push_str("#[serde(transparent)]\n");
                writeln!(
                    out,
                    "pub struct {}(pub {});",
                    declaration_name(name),
                    self.rust_type(Module::Types, &body["of"], name, "the value it wraps")?
                )?;
            }
            "enum" => out.push_str(&self.enumeration(name, array(body, "variants")?)?),
            "struct" => {
                out.push_str(&self.record(
                    Module::Types,
                    name,
                    &declaration_name(name),
                    "struct",
                    array(body, "fields")?,
                )?);
            }
            "union" => {
                let tag = body["tag"].as_str().ok_or("union tag")?;
                writeln!(out, "/// `{name}` — union.")?;
                out.push_str(DERIVE);
                writeln!(
                    out,
                    "#[serde(tag = \"{tag}\", content = \"value\", deny_unknown_fields)]"
                )?;
                writeln!(out, "pub enum {} {{", declaration_name(name))?;
                for (label, variant) in object(body, "variants")? {
                    let rust = declaration_name(label);
                    identifier(&rust, name)?;
                    writeln!(out, "    #[serde(rename = \"{label}\")]")?;
                    writeln!(
                        out,
                        "    {rust}({}),",
                        self.rust_type(Module::Types, variant, name, label)?
                    )?;
                }
                out.push_str("}\n");
            }
            other => return Err(format!("unmapped type body: {other} in {name}").into()),
        }
        Ok(out)
    }

    fn entities(&self) -> Result<Vec<String>> {
        let mut blocks = Vec::new();
        for (name, entity) in index(self.model, "entities")? {
            let identity = &entity["identity"];
            let state = entity["state_type"].as_str().ok_or("entity state type")?;
            let mut fields = vec![identity.clone()];
            fields.extend(array(entity, "fields")?.iter().cloned());
            self.refuse_credential_material("entity", name, &fields)?;
            fields.push(serde_json::json!({
                "name": "state",
                "type_ref": {"kind": "declared", "name": state},
            }));
            blocks.push(self.record(
                Module::Entities,
                name,
                &declaration_name(name),
                "entity record",
                &fields,
            )?);
            blocks.push(self.enumeration(
                state,
                array(&index(self.model, "types")?[state]["body"], "variants")?,
            )?);
        }
        Ok(blocks)
    }

    fn events(&self) -> Result<Vec<String>> {
        let mut blocks = Vec::new();
        for (name, event) in index(self.model, "events")? {
            let fields = array(event, "fields")?;
            self.refuse_credential_material("event", name, fields)?;
            blocks.push(self.record(
                Module::Events,
                name,
                &declaration_name(name),
                "event payload",
                fields,
            )?);
        }
        Ok(blocks)
    }

    fn commands(&self) -> Result<Vec<String>> {
        let mut blocks = Vec::new();
        for (name, command) in index(self.model, "commands")? {
            blocks.push(self.record(
                Module::Commands,
                name,
                &format!("{}Input", declaration_name(name)),
                "command input",
                array(command, "input")?,
            )?);
            if command.get("response").is_some() {
                blocks.push(self.record(
                    Module::Commands,
                    name,
                    &format!("{}Response", declaration_name(name)),
                    "command response",
                    array(command, "response")?,
                )?);
            }
        }
        for (name, error) in index(self.model, "errors")? {
            blocks.push(self.record(
                Module::Commands,
                name,
                &declaration_name(name),
                "refusal payload",
                array(error, "fields")?,
            )?);
        }
        Ok(blocks)
    }

    /// One `deny_unknown_fields` record: the shape of every declared field set.
    fn record(
        &self,
        module: Module,
        declared: &str,
        rust: &str,
        kind: &str,
        fields: &[Value],
    ) -> Result<String> {
        let mut out = String::new();
        writeln!(out, "/// `{declared}` — {kind}.")?;
        out.push_str(DERIVE);
        out.push_str("#[serde(deny_unknown_fields)]\n");
        if fields.is_empty() {
            writeln!(out, "pub struct {rust} {{}}")?;
            return Ok(out);
        }
        writeln!(out, "pub struct {rust} {{")?;
        for field in fields {
            let name = field["name"].as_str().ok_or("field name")?;
            identifier(name, declared)?;
            let type_ref = &field["type_ref"];
            if type_ref["kind"] == "optional" {
                writeln!(
                    out,
                    "    #[serde(default, skip_serializing_if = \"{}::is_absent\")]",
                    self.presence(module)
                )?;
            }
            writeln!(
                out,
                "    pub {name}: {},",
                self.rust_type(module, type_ref, declared, name)?
            )?;
        }
        out.push_str("}\n");
        Ok(out)
    }

    /// One string enum: the declared variant names, pinned to the wire by an explicit rename.
    ///
    /// The rename is redundant today — every variant is already its own wire value — and that
    /// is the point: a later Rust-side rename cannot silently move the wire form.
    fn enumeration(&self, declared: &str, variants: &[Value]) -> Result<String> {
        let mut out = String::new();
        writeln!(out, "/// `{declared}` — enum.")?;
        out.push_str(DERIVE);
        writeln!(out, "pub enum {} {{", declaration_name(declared))?;
        for variant in variants {
            let variant = variant.as_str().ok_or("enum variant")?;
            identifier(variant, declared)?;
            writeln!(out, "    #[serde(rename = \"{variant}\")]")?;
            writeln!(out, "    {variant},")?;
        }
        out.push_str("}\n");
        Ok(out)
    }

    /// Where a declared name is reachable from, given the file being written.
    fn path(&self, from: Module, declared: &str) -> String {
        let owner = if self.states.contains(declared) {
            Module::Entities
        } else {
            Module::Types
        };
        let name = declaration_name(declared);
        if owner == from {
            name
        } else {
            format!("super::{}::{name}", owner.name())
        }
    }

    fn presence(&self, from: Module) -> &'static str {
        if from == Module::Types {
            "Presence"
        } else {
            "super::types::Presence"
        }
    }

    /// The Rust type of one declared position.
    ///
    /// `declared` and `position` are carried only so that a refusal names them. A defect in
    /// the contract has to be reported against the declaration that carries it; a message
    /// naming neither is read against a generated file, which is the confusion this module
    /// exists to prevent.
    fn rust_type(
        &self,
        from: Module,
        type_ref: &Value,
        declared: &str,
        position: &str,
    ) -> Result<String> {
        match type_ref["kind"].as_str().ok_or("type expression kind")? {
            "primitive" => Ok(primitive(
                type_ref["name"].as_str().ok_or("primitive name")?,
                declared,
                position,
            )?
            .to_owned()),
            "declared" => Ok(self.path(from, type_ref["name"].as_str().ok_or("declared name")?)),
            "optional" => Ok(format!(
                "{}<{}>",
                self.presence(from),
                self.rust_type(from, &type_ref["of"], declared, position)?
            )),
            "list" => Ok(format!(
                "Vec<{}>",
                self.rust_type(from, &type_ref["of"], declared, position)?
            )),
            other => Err(format!(
                "{declared} at {position:?} declares the type expression {other:?}, \
                 which this emitter does not map"
            )
            .into()),
        }
    }

    /// Refuse a durable record that reaches credential material, naming the path that does it.
    ///
    /// Reachability, not the field's own type: a field typed `VerifiedContext` is what an
    /// indirect leak looks like at the declaration, and a check that read only the field would
    /// pass it.
    fn refuse_credential_material(&self, kind: &str, name: &str, fields: &[Value]) -> Result<()> {
        for field in fields {
            let field_name = field["name"].as_str().ok_or("field name")?;
            let mut reached = Vec::new();
            declared_names(&field["type_ref"], &mut reached);
            for declared in reached {
                if let Some(chain) = self.credential_path(&declared, &mut BTreeSet::new())? {
                    return Err(format!(
                        "{kind} {name} field {field_name:?} reaches credential material: {}",
                        chain.join(" -> ")
                    )
                    .into());
                }
            }
        }
        Ok(())
    }

    /// The chain from a declared type to credential material, or `None` if it reaches none.
    ///
    /// A name the model does not declare is an error and never a `None`: "this type is not
    /// declared" cannot be allowed to read as "this type holds no secret".
    fn credential_path(
        &self,
        declared: &str,
        seen: &mut BTreeSet<String>,
    ) -> Result<Option<Vec<String>>> {
        if FORBIDDEN.contains(&declared) {
            return Ok(Some(vec![declared.to_owned()]));
        }
        if !seen.insert(declared.to_owned()) {
            return Ok(None);
        }
        let references = self
            .references
            .get(declared)
            .ok_or_else(|| format!("{declared} is referenced but the model does not declare it"))?;
        for next in references {
            if let Some(mut chain) = self.credential_path(next, seen)? {
                chain.insert(0, declared.to_owned());
                return Ok(Some(chain));
            }
        }
        Ok(None)
    }
}

/// Every declared name a type expression names, in declaration order.
fn declared_names(type_ref: &Value, into: &mut Vec<String>) {
    match type_ref["kind"].as_str() {
        Some("declared") => {
            if let Some(name) = type_ref["name"].as_str() {
                into.push(name.to_owned());
            }
        }
        Some("optional" | "list") => declared_names(&type_ref["of"], into),
        _ => {}
    }
}

/// An `optional` is a record key, or it is refused, naming the declaration that carries it.
///
/// `Presence` is a carrier for a *key*: it is skipped out of an object on the way out and read
/// back from a missing key on the way in, and it can do neither in any other position.
/// `outside` is `None` at the top of a record key — the one place an optional is admitted —
/// and `Some(context)` everywhere else, including one step below a key that is itself optional.
///
/// The contract's own JSON Schema projection is the reason rather than Rust's convenience. It
/// spells an optional newtype as `anyOf: [$ref, {"type": "null"}]` and an optional union
/// variant as a content key dropped from `required`; a list has no spelling for it at all.
/// `Presence` reads none of those, so a shape emitted there would be one the two projections
/// of one model disagree about.
fn optional_position(
    type_ref: &Value,
    declared: &str,
    position: &str,
    outside: Option<&'static str>,
) -> Result<()> {
    match type_ref["kind"].as_str().ok_or("type expression kind")? {
        "optional" => match outside {
            Some(context) => Err(format!(
                "{declared} at {position:?} declares an optional {context}; absence is a \
                 property of a record key and has no spelling anywhere else"
            )
            .into()),
            None => optional_position(
                &type_ref["of"],
                declared,
                position,
                Some("inside another optional"),
            ),
        },
        "list" => optional_position(&type_ref["of"], declared, position, Some("inside a list")),
        _ => Ok(()),
    }
}

/// The ESS-side description of what a newtype wraps.
fn describe(type_ref: &Value, declared: &str, position: &str) -> Result<String> {
    match type_ref["kind"].as_str().ok_or("type expression kind")? {
        "primitive" | "declared" => Ok(type_ref["name"]
            .as_str()
            .ok_or("type expression name")?
            .to_owned()),
        "optional" => Ok(format!(
            "optional {}",
            describe(&type_ref["of"], declared, position)?
        )),
        "list" => Ok(format!(
            "list of {}",
            describe(&type_ref["of"], declared, position)?
        )),
        other => Err(format!(
            "{declared} at {position:?} declares the type expression {other:?}, \
             which this emitter does not map"
        )
        .into()),
    }
}

/// The Rust type of a declared primitive.
///
/// A primitive the contract grows and this table does not name is a refusal. The alternative
/// is an emitter that answers an unknown primitive with a plausible type, which is the shape
/// of defect this whole crate exists to make impossible.
fn primitive(name: &str, declared: &str, position: &str) -> Result<&'static str> {
    Ok(match name {
        // A timestamp, a duration and a uuid are strings on the wire; `bytes` is base64 in a
        // string. The crate states the structure of the contract, not its lexical constraints:
        // those are the JSON Schema projection's, and a Rust type that claimed them would be
        // claiming validation the generated shape does not do.
        "string" | "timestamp" | "duration" | "bytes" | "uuid" => "String",
        // `serde_json::Number`, as ESS's own realizer does, and for its reason: JSON Schema's
        // `integer` is any number with a zero fractional part and carries no range of its own,
        // so `1.0` and `2^63` are both values the projection admits and neither is an `i64`.
        //
        // How far that goes is worth stating rather than implying. Without the
        // `arbitrary_precision` feature a `Number` holds an `i64`, a `u64` or an `f64`, so it
        // carries every integer in `-2^63 ..= 2^64 - 1` exactly and nothing past it: `2^64 + 1`
        // comes back as `1.8446744073709552e19` and `-0` as `-0.0`. No integer this contract
        // declares is outside that range, so the bound is the edge of the contract's value
        // space rather than a limit inside it. Enforcing integrality and any declared range
        // stays the declaration's business, not this type's, and `arbitrary_precision` is
        // deliberately not enabled: it would turn every number in the crate into a
        // string-backed token to widen a range nothing uses.
        "integer" => "::serde_json::Number",
        "boolean" => "bool",
        other => {
            return Err(format!(
                "{declared} at {position:?} declares the primitive {other:?}, \
                 which this emitter does not map"
            )
            .into());
        }
    })
}

/// A name Rust can take, or a refusal naming the declaration that carries it.
fn identifier(name: &str, declared: &str) -> Result<()> {
    let head = name.chars().next().ok_or("empty name")?;
    if !(head.is_ascii_alphabetic() || head == '_')
        || !name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
    {
        return Err(format!("{declared} names {name:?}, which is not a Rust identifier").into());
    }
    if KEYWORDS.contains(&name) {
        return Err(
            format!("{declared} names {name:?}, which edition 2024 keeps as a keyword").into(),
        );
    }
    Ok(())
}

/// One of the model's top-level indexes, as a sorted map.
fn index<'a>(model: &'a Value, kind: &str) -> Result<&'a Map<String, Value>> {
    model[kind]
        .as_object()
        .ok_or_else(|| format!("the model carries no {kind} index").into())
}

fn object<'a>(value: &'a Value, key: &str) -> Result<&'a Map<String, Value>> {
    value[key]
        .as_object()
        .ok_or_else(|| format!("expected an object at {key}").into())
}

fn array<'a>(value: &'a Value, key: &str) -> Result<&'a Vec<Value>> {
    value[key]
        .as_array()
        .ok_or_else(|| format!("expected an array at {key}").into())
}
