[package]
name = "mandate-client"
description = "Rust PEP client and middleware."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
mandate-types = { version = "0.3.0", path = "../mandate-types" }
mandate-proto = { version = "0.3.0", path = "../mandate-proto" }
